### ISSUE TITLE
Problem with last FM scrobbling

### ISSUE THREAD

**Issue by dorel14** [airsonic-advanced/airsonic-advanced#110]
Hello 
i've downloaded and install latest .war and after listening for some song , i've found this in logs 
`2020-02-28 15:33:15.329  WARN --- o.a.p.s.s.LastFMScrobbler                : Failed to scrobble song 'À vouloir toucher Dieu…' at Last.fm.  Unknown response: <html><head`

i didn't had this with 10.5

**Comment by randomnicode** [comment]
Hmmm, at first glance, the bulk of the changes here are from airsonic base, which means their next stable release will have this issue.

I'll look into it

**Comment by randomnicode** [comment]
Looks like a change was accidentally reverted.

**Comment by dorel14** [comment]
thx
I test today and it's fine only if i store my password in plain-text which is not very secure
each time i have tested something else , i obtain 
`2020-03-02 20:11:37.340  WARN --- o.a.p.s.s.LastFMScrobbler                : Failed to scrobble song 'À vouloir toucher Dieu…' at Last.fm. Wrong username or password.`

**Comment by randomnicode** [comment]
Pushed out a fix. Will merge it later today.
