### ISSUE TITLE
Default number of rows in tables

### ISSUE THREAD

**Issue by randomnicode** [airsonic-advanced/airsonic-advanced#154]
Hi! Thank you for the hard work.

Would it be possible to add a user preference for the default number of rows in tables? I would like to default to "All" instead of 10.

_Originally posted by @khannurien in https://github.com/airsonic-advanced/airsonic-advanced/pull/130#issuecomment-604473536_

**Comment by randomnicode** [comment]
These are variables to be considered:
- User-specified rows for which tables
  - One per table (that's at least 3 tables, and more if other tables crop up)
  - Only specifiable for Playqueue, everything else gets a default number
- Performance
  - Large number of rows will slow down page performance
    - Will need to add the Scroller extension to keep performance
      - Will need to look at the row reordering/click handling

**Comment by khannurien** [comment]
As I'm heavily using playlists, I'm particularly interested in begin able to default to "All" for these.

Regarding "convention over configuration" -- I think the album view of all the views could be defaulted to "All" without user setting. It feels silly to have to use page 2 for one or two tracks.

**Comment by randomnicode** [comment]
Merged, @khannurien please test the merged release and see if this issue can be closed?

**Comment by randomnicode** [comment]
> I think the album view of all the views could be defaulted to "All" without user setting

Doesn't work for people working with massive directories where they dump all songs in one folder. There will be significant performance drawbacks for trying to draw that kind of large table.

Just for usecase profiling, why is it that you need to default to All? What is it that paging hinders in your normal workflow? The data is all client side so the lag time between drawing pages should be minimal and will save you some performance implications that you might get for a large table.

**Comment by khannurien** [comment]
Your patch seems to work flawlessly. Thank you!

> Just for usecase profiling, why is it that you need to default to All?

Albums usually don't exceed 20 or 30 tracks, and I'm used to being able to see every track in a playlist when I'm working on it.
I guess these are just habits, and I'm glad I'm now able to stick to it.

> Doesn't work for people working with massive directories where they dump all songs in one folder.

Fair enough, that's why I advocated for a user setting in the first place! :-)

**Comment by randomnicode** [comment]
Sorry can you please point out what the bug is?

**Comment by khannurien** [comment]
Sorry I haven't been clear enough -- it is the padding of the top bar:

![image](https://user-images.githubusercontent.com/31770422/78803782-b2944f80-79bf-11ea-9519-9e6af7498bee.png)

It used to be narrower, like that:

![image](https://user-images.githubusercontent.com/31770422/78803923-dbb4e000-79bf-11ea-99b9-2902d5950e11.png)

**Comment by randomnicode** [comment]
Yeah, thought this issue was via css, but seems like it's pretty resilient, so we're going to take heavy-handed tactics

**Comment by randomnicode** [comment]
If you've verified the fix, please feel free to close this issue

**Comment by khannurien** [comment]
Perfect!
