### ISSUE TITLE
Can not play music with external players

### ISSUE THREAD

**Issue by brandsjek** [airsonic-advanced/airsonic-advanced#174]
## Problem description

I am unable to use external (m3u) players. 

The web player does work, but I get no download for a m3u file when using external players. This did work in upstream Airsonic.

### Steps to reproduce

1. Change the player to "External player" or "External player with playlist" in Settings->Players
2. Play any song
3. Observe that there is no m3u file being downloaded

## System information

 * **Airsonic version**: 10.6.0-SNAPSHOT.20200406055614
 * **Operating system**: Debian 10.3
 * **Java version**:

```
$ java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1deb10u1, mixed mode, sharing)
```

 * **Proxy server**: nginx, configured for websockets
 * **Client**: Tried in Chrome and Firefox
 * **Language**: English US

**Comment by randomnicode** [comment]
👀

**Comment by randomnicode** [comment]
@brandsjek #178 was merged, is that an acceptable solution?

**Comment by brandsjek** [comment]
Works as intended now. Thanks for your work
