### ISSUE TITLE
Passwords are not usable unless all other credentials for a user are removed from a PostgreSQL database

### ISSUE THREAD

**Issue by brandsjek** [airsonic-advanced/airsonic-advanced#176]
## Problem description

A user (I have only tried this with the default `admin` user but it seems likely that this will also happen with other users) can not sign in with new credentials after changing them. Only the first supplied credential (in the case of the `admin` user that password is `admin`) is usable to successfully sign in. I am using a PostgreSQL database.

### Steps to reproduce

1. Change the default users' password
2. Observe that a new row in the `user_credentials` table has been created
3. Attempt to sign in with the changed password
4. Observe that the newly supplied password fails
5. Attempt to sign in with the old password
6. Observe that sign-on was successful.

## System information

 * **Airsonic version**: 10.6.0-SNAPSHOT.20200406055614
 * **Operating system**: Debian 10.3
 * **Java version**: 

```
$ java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1deb10u1, mixed mode, sharing)
```

 * **Proxy server**: nginx, configured for websockets
 * **Client**: N/A as this is a server issue
 * **Language**: N/A for aforementioned reason

## Additional notes

A workaround would be to remove all rows from `user_credentials` except for the row containing the newly created password.

**Comment by randomnicode** [comment]
Hmmm, I'm completely unable to reproduce this bug.

The MultipleCredsMatchingAuthenticationProvider provides for this exact scenario and seems to work exactly as intended.

Is there anything in the logs that might clue us in to what's going on?

There are routine test cases for 4 or 5 login credentials for the default admin user, and logging with any of them seems to work.

**Comment by brandsjek** [comment]
Nope, can't reproduce on a new install anymore. Will close and reopen if I run across this again.
