### ISSUE TITLE
Playlist weird web reactions when passing the mouse over it.

### ISSUE THREAD

**Issue by jobenvil** [airsonic-advanced/airsonic-advanced#177]
## Problem description

I'm using the following `java` command to start airsonic:

`/usr/bin/java -Xmx700m -Dairsonic.home=/media/sda/airsonic/config -Dserver.context-path=/airsonic -Dserver.host=0.0.0.0 -Dserver.port=8070 -Djava.awt.headless=true -Dserver.use-forward-headers=true -verbose:gc -jar /media/sda/airsonic/airsonic.war --illegal-access=warn`

Maybe you already noticed it. Moving the mouse over the playlist section, produces weird quick movement. See the animated gif.

## System information

 * **Airsonic version**: `

*  **10.6.0-SNAPSHOT.20200406171011** – April 6, 2020 at 7:10:11 PM CEST`
 * **Operating system**:  `Ubuntu 19.10 (GNU/Linux 5.3.0-29-generic x86_64)`
 * **Java version**: `zulu13.29.9-ca-jdk13.0.2-linux_amd64 / OpenJDK11U-jre_x64_linux_openj9_11.0.6_10_openj9-0.18.1 / OpenJDK13U-jre_x64_linux_openj9_13.0.2_8_openj9-0.18.0.tar`
 * **Proxy server**:  `nginx nginx/1.17.8`

 * **Client**: `Version 80.0.3987.163 (Offizieller Build) (64-Bit)`
  
 * **Language**: `UTF8`

As usual, thanks for your intensive work.

![Alt Animated Gif](https://hiperborea.de/seafile/f/0aa19d5a81d24e618042/?dl=1)

**Comment by randomnicode** [comment]
As in the sliding effect (slide up)?

That's actually intended as a UI thing. It was kinda disabled in base Airsonic due to some tech issues (specifically for newer versions of Chrome).

We can remove it if folks want it to be removed (or decrease the slide up animation time).

Alternatively, you may also choose to not have autohide enabled (in Settings >> Personal >> Autohide play queue)

**Comment by jobenvil** [comment]
Is not the sliding up effect, moreover the padding effect and shifting of the borders page at the same time, producing a strange movement (not only from down to the top). The displacement effect is observable on the right side of the window.

**Comment by randomnicode** [comment]
Hmmm, do you think it's maybe it's the browser redrawing and recalculating the newly displayed flex container dimensions that just was unhidden and appeared in the layout?

**Comment by jobenvil** [comment]
Maybe the effect is better recognizable in the [video here](https://hiperborea.de/seafile/f/9741df8a8df9448bb4c3/?dl=1)

**Comment by jobenvil** [comment]
Hi man, you fixed it 🥇 many thanks!

**Comment by randomnicode** [comment]
👍
