### ISSUE TITLE
Ui Issue on left side (artist names)

### ISSUE THREAD

**Issue by dorel14** [airsonic-advanced/airsonic-advanced#181]
## Problem description
On left column the arrow which permit to hide all artist beginning by a letter doesn't work anymore

### Steps to reproduce

Click on the arrow near the A lettter on left side

## System information

 * **Airsonic version**: 10.6.0-SNAPSHOT.20200408045448 – 8 avril 2020 à 04:54:48 UTC
 * **Operating system**: Debian 10

 * **Java version**: OpenJDK 11
 * **Proxy server**: Nginx
 * **Client**: Chrome

 * **Language**: French

**Comment by randomnicode** [comment]
Hmm, do you mind posting an image?

Which arrow near the A letter in the left panel?

**Comment by dorel14** [comment]
Hi 
Excuse me , it's working but not as i thought . I close
