### ISSUE TITLE
Layout issue with play queue slider

### ISSUE THREAD

**Issue by khannurien** [airsonic-advanced/airsonic-advanced#186]
Hi,

I just noticed a (new) layout issue that might be related to your recent fixes to the top iframe.

When the current queue is slided down, there is a useless right sidebar in the browser:

![1](https://user-images.githubusercontent.com/31770422/78988259-babfcc80-7b30-11ea-8a4b-ed3c4c493a0b.png)

When the queue is slided up, things get worse since I need to scroll down the right sidebar in order to get play controls to show up:

![2](https://user-images.githubusercontent.com/31770422/78988263-bdbabd00-7b30-11ea-9e44-f0e914e0b238.png)

Please tell me if the screenshots are not clear enough (I obfuscated most of it...)

**Comment by randomnicode** [comment]
@khannurien Fixed

**Comment by khannurien** [comment]
Yes, perfect.
