### ISSUE TITLE
Multi-select download of podcasts frequently fails

### ISSUE THREAD

**Issue by openscallion** [airsonic-advanced/airsonic-advanced#197]
## Problem description

Single select downloads of podcasts work as expected; however, selecting two or more and clicking "download selected" either does nothing or throws a 400 internal error when three or more are selected.

### Steps to reproduce

1. Add a podcast
2. Select more than one episode
3. Click 'download selected'
4. Download does not start (exactly two or three) or (usually) fails in frame (4+)

## System information

 * 10.6.0-SNAPSHOT.20200414043004
 * docker on unraid
 * java 11.0.6
 * nginx 1.16.1
 * Firefox 74.0.1
 * English

## Additional notes

Log of 4+ failure attached. Nothing in console or logs for the "nothing happens" failures. Tested with multiple podcasts (Welcome to Nightvale, This American Life, Darknet Diaries, Reply All, others) that all downloaded OK with vanilla airsonic regardless of number.
[multiselect_four_or_more_trace.txt](https://github.com/airsonic-advanced/airsonic-advanced/files/4485711/multiselect_four_or_more_trace.txt)

**Comment by randomnicode** [comment]
The podcast pages are pretty decent candidates to get converted to websockets. For now the problematic JS has been fixed. Future considerations:
- Convert to websockets
- Add ability to toggle between album thumb and list view (similar to mediaMain)
