### ISSUE TITLE
Container crash when clicking settings button in player panel

### ISSUE THREAD

**Issue by openscallion** [airsonic-advanced/airsonic-advanced#198]
## Problem description

Attempting to use the settings icon in the player panel causes container crash requiring restart.

### Steps to reproduce

1. Click the settings icon in the player panel
2. 502 error in center frame
2. Be unable to load anything until container is restarted

## System information

 * 10.6.0-SNAPSHOT.20200414043004
 * docker on unraid
 * java 11.0.6
 * nginx 1.16.1
 * Firefox 74.0.1
 * English

## Additional notes

Container log (this error usually appears twice in a row):
`Inconsistency detected by ld.so: dl-lookup.c: 112: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!`

Browser console (appears immediately following clicking that icon):
```
Whoops! Lost connection to https://mydomain.com/music/websocket stomp-4.0.8.min.js:9:2502
Disconnected 
Object { type: "close", bubbles: false, cancelable: false, timeStamp: 1587025226100, wasClean: false, code: 1006, reason: "permanent" }
index:131:29
Error Whoops! Lost connection to https://mydomain.com/music/websocket
```

This also occurs when not behind a reverse proxy, although a simple "unable to connect" appears in the center frame instead of a 502. Similar behavior but including for completeness.

**Comment by randomnicode** [comment]
Hmmm, this is a weird one, because everything online suggests that this is an Ubuntu JDK issue, but the Docker images being built aren't Ubuntu, they're AdoptOpenJDK on Alpine.

We could switch to jdk instead of jre and see if that works? Or switch to a different version altogether though that's not really desirable... Are other folks having this issue?

**Comment by randomnicode** [comment]
@openscallion Container switched to 14-jre and Ubuntu base instead of alpine. Try now?

**Comment by openscallion** [comment]
Worked great! Thank you so much! Closing.

Hopefully it works for #267 as well.
