### ISSUE TITLE
Can't log in with DSub

### ISSUE THREAD

**Issue by randomnicode** [airsonic-advanced/airsonic-advanced#212]
When trying to switch from vanilla airsonic to this implementation I realized that the mobile app I am currently using (DSub, https://github.com/daneren2005/Subsonic) fails to connect to the server, most likely due to the changes in credentials management. Are you aware of mobile applications (android) that work with airsonic-advanced?

_Originally posted by @chrstn-hntschl in https://github.com/airsonic-advanced/airsonic-advanced/issues/183#issuecomment-615279496_

**Comment by randomnicode** [comment]
This is a latent bug you've surfaced. It'll be fixed here: https://github.com/airsonic-advanced/airsonic-advanced/pull/211

DSub should work fine after that.

Notes:
- DSub seems to use the t+s auth mechanism
- Airsonic-Advanced migrates in a backwards-compatible way currently.
  - Your creds stay in the encoding they're in. Please voluntarily migrate to a more secure encoding. Use the UI. Do NOT stay `legacy*`.
  - Next MAJOR release (likely 11.0) may forcibly upgrade you to a more secure encoding.
    - If you can't log into DSub then, then you've likely been migrated to a _nondecodable_ encoder (which DSub can't use). Just create a new credential with a _decodable_ encoder
- Because you use DSub (which uses t+s), make sure whatever login credentials you use _for logging into DSub_ are encoded with a _decodable_ encoder (preferably the `encoded-AES-GCM` instead of something else)
- An example config for you would be:
  - 2 creds: 1 `bcrypt` (passwordA) and 1 `encrypted-AES-GCM` (passwordB)
  - On the web (or other supported clients), you can log in with either
  - On DSub, you can only use passwordB, because passwordA is not decodable for t+s (used by DSub)
  - passwordA and passwordB may be the same (less secure, but perhaps more convenient for you)

You can also have just one password (with `encrypted-AES-GCM`) and use it for everything, but it'll be less secure than say a credential with `bcrypt` in the DB. You may ask DSub devs to switch to the alternate auth mechanism, which will allow you to store your creds even more securely.

Regardless of whatever you do, `encrypted-AES-GCM` is still way more secure than storing openly (vanilla airsonic).

**Comment by randomnicode** [comment]
Merged, please try the next version of airsonic-advanced, once the CD pipeline releases it (usually ~10-15 mins)

**Comment by randomnicode** [comment]
Btw, you can use the official Subsonic app, which works fine with `bcrypt` and other nondecodable encoders. I'm sure there are others in the ecosystem.

**Comment by chrstn-hntschl** [comment]
Cool - thanks a lot for your explanations and implementations! I'll give it a try tonight!

**Comment by SyntrophicConsortium** [comment]
It looks like I broke my Airsonic-advanced login when trying to change the credential settings. I was unable to login using the Subsonic Android app, so I tried following your suggestion here. I accidentally set the "initial legacy migration" credential to bcrypt (instead of creating a new credential), and now I'm getting a 404 not found when I access the login page from my web browser. I don't see a way to change it back in the GUI. 

I'm still logged in via another tab, so I tried setting up different credentials using various non-decodable encoders, but I'm still getting a 404 when accessing the login page.

**Comment by SyntrophicConsortium** [comment]
I'm not able to get this to work. I can't connect to my server with Subsonic, so I tried adding a new credential using bcrypt, but now I'm getting a 404 error when I try to login from a web browser (and I still can't connect with Subsonic).

**Comment by randomnicode** [comment]
Okay, let's debug it.
- Which airsonic-advanced version are you using? Try with the latest snapshot. There was an older version that had an issue that was fixed in https://github.com/airsonic-advanced/airsonic-advanced/pull/211
- No matter what type of encoder you have (decodable or nondecodable), you should always be able to log in via the web. The Subsonic app will also support both. So if you're using the Subsonic app (or the web), `bcrypt` is fine (and recommended). No need to add additional less secure creds. Migrating your initial legacy to bcrypt is okay too.
- You should only use decodable encoders if you use an app like DSub that does not use a more secure method for server storage.
- Nondecodable passwords cannot be changed to a different encoding. That's because, by definition, they're nondecodable, we don't actually store the password itself at all. Thus a `bcrypt` can't be changed to anything else. 
- A 404 isn't something you should be seeing for an incorrect cred. Are you sure you're going to the correct page? Has the server crashed?

**Comment by SyntrophicConsortium** [comment]
I found a backup of my Airsonic folder, so I'm going to start over with this. 

I downloaded the latest snapshot. The current credential is legacyhex. I added a new credential that uses bcrypt. The "preferred non-decodable encoder" is set to bcrypt, and "use non-decodable password wherever possible" is checked. 

What steps should I take so I Subsonic will connect? Currently it gives me the error, "Didn't understand the reply" if I try to do anything while in online mode in Subsonic (for example, if I tap on "recently added"). 

If I click the button "migrate (use non-decodable)" Airsonic displays an error, "Invalid encoder or specified encoder not supported for that location" next to the "preferred non-decodable encoder" setting (which is set to bcrypt).

I suspect I am misunderstanding how this works. I'm not particularly knowledgeable about authentication methods. Do I have to delete the legacy credential?

**Comment by randomnicode** [comment]
> The current credential is legacyhex. I added a new credential that uses bcrypt.

You could have just converted your `legacyhex` one to `bcrypt`, but adding a new is fine. Before converting or adding, maybe add a new server to Subsonic app and Test the connection with your `legacyhex` creds? Then add a new server in the App and add the `bcrypt` creds and Test connection.

> The "preferred non-decodable encoder" is set to bcrypt, and "use non-decodable password wherever possible" is checked.

These are just options for defaults.

> What steps should I take so I Subsonic will connect? Currently it gives me the error, "Didn't understand the reply" if I try to do anything while in online mode in Subsonic (for example, if I tap on "recently added").

This should not be happening. Are you sure you have the right app? Did you add a new server with the correct URL and creds? Did you click on Test connection? Did you switch your server to your new added one in the main menu before clicking on most recent (if you don't switch servers it, it'll stay on the old demo server if you just downloaded it)? Maybe post screenshots? Many folks use this app without any issues.

> If I click the button "migrate (use non-decodable)" Airsonic displays an error, "Invalid encoder or specified encoder not supported for that location" next to the "preferred non-decodable encoder" setting (which is set to bcrypt).

This is totally a bug. A fix has been issued here: https://github.com/airsonic-advanced/airsonic-advanced/pull/242 and will be merged shortly (use the latest binary)

**Comment by SyntrophicConsortium** [comment]
Apparently I had to add a new server in Subsonic, despite the fact that all the settings in the previous server are correct. Credentials and address have not changed. Maybe there's a reason for this that I don't see. 

I saw the new release and I will grab that. Thanks.
