### ISSUE TITLE
Opening album of last played song instead of home site

### ISSUE THREAD

**Issue by Faeb35** [airsonic-advanced/airsonic-advanced#221]
## Problem description

When I recently played some songs and opening Airsonic Advanced and then just entering the URL of Airsonic (aka refresh), Airsonic opens the album of the last played song. 
I would expect to get the home site instead.
Not sure if this is a issue or a feature though ;-)

### Steps to reproduce

1. Play any song
2. Press F5 or open a new tab and browse to Airsonic
3. Your getting the album of the last played song instead of the home page

## System information

 * **Airsonic version**: Edge Release 10.6.0-SNAPSHOT.20200414043004
 * **Operating system**: Windows Server 2012
 * **Java version**: Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
 * **Proxy server**: IIS
 * **Client**: Tested in Firefox
 * **Language**: English

**Comment by randomnicode** [comment]
This is deliberately a design decision. We actually look for what you were playing and directly opens on that page.

**Comment by randomnicode** [comment]
Close this issue please?

**Comment by Faeb35** [comment]
Hi randomnicode
Thank you very much! As I'm listening most of the time randomly and not certain albums, for me this behavior doesn't fit. But probably for the way others are using Airsonic (listening to albums) it does.
