### ISSUE TITLE
"Show X entries" not saved and in wrong order

### ISSUE THREAD

**Issue by Faeb35** [airsonic-advanced/airsonic-advanced#224]
## Problem description

Like in the playing queue or when opening an album you get the following option:
![grafik](https://user-images.githubusercontent.com/9485516/79765771-56b6b880-8327-11ea-90b3-6307b8223f5f.png)
Two things with this drop down:
1. Is there a place, where I can set a default value for that? Or should this be saved automatically when changing the value? For me it always goes back to 40.
2. 40 is on the bottom instead after 20 and before 50.

## System information

 * **Airsonic version**: Edge Release 10.6.0-SNAPSHOT.20200414043004
 * **Operating system**: Windows Server 2012
 * **Java version**: Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
 * **Proxy server**: IIS
 * **Client**: Tested in Firefox
 * **Language**: English

**Comment by randomnicode** [comment]
`40` is a custom non-standard option and therefore appears separately and not in order. For some reason earlier versions of airsonic used 40 as the default before and so you're now seeing it.

Newer users I think have one of the standard pagination options autoselected (put in airsonic-advanced).

Yes, it can be customized here: Settings -> Personal -> Pagination size for tables (-1 shows everything)

**Comment by randomnicode** [comment]
Close this issue please?

**Comment by Faeb35** [comment]
Hi randomnicode
Thank you very much for the explanation and your time!
Now I remember, I was the person who set the value of 40 there! What a shame :-(
Very very sorry for opening this unecessary issue!

**Comment by awsms** [comment]
> Yes, it can be customized here: Settings -> Personal -> Pagination size for tables (-1 shows everything)

 If I set it to -1, 249 or even 294502592, it will still show 7 elements on a page. I'm using the latest stable release 10.6.0

**Comment by randomnicode** [comment]
I think you're looking at the subdirectories table. That is hardcoded to 7.
https://github.com/airsonic-advanced/airsonic-advanced/blob/416e772afd7ba62d118d3b9edf171c5f27d89c20/airsonic-main/src/main/webapp/WEB-INF/jsp/mediaMain.jsp#L438-L439

The regular files table is populated with the user preference
