### ISSUE TITLE
NoSuchFileException on service start if podcast episode is missing

### ISSUE THREAD

**Issue by SyntrophicConsortium** [airsonic-advanced/airsonic-advanced#246]
I'm running Stable Release 10.6.0, but I have the same problem with the 2 subsequent releases as well. 

Airsonic crashes on service start if a podcast episode file is missing (no such file exception). The process continues to run, but I cannot access the interface in my browser. I get a "page can't be displayed" error in Firefox. Dev console shows a get request made to /login, but no response code from the server.

I didn't manually delete the file in question. I confirmed the file is missing. I assume Airsonic is deleting the file because I have it set to only keep 10 or so.

Deleting the folder for the particular podcast, e.g. /Podcasts/Podcast title/ allows me access Airsonic in the browser again.

Here is the relevant log output:

> 2020-04-24 16:43:10.550  WARN --- o.a.p.service.MediaFileService           : Could not retrieve children for /media/mp3/Podcasts/Behind the Bastards/HSW71630825051.mp3.java.nio.file.NoSuchFileException: /media/mp3/Podcasts/Behind the Bastards/HSW71630825051.mp3	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[na:na]	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:428) ~[na:na]	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:465) ~[na:na]	at java.base/java.nio.file.Files.list(Files.java:3527) ~[na:na]	at org.airsonic.player.service.MediaFileService.createMediaFile(MediaFileService.java:498) [classes!/:10.6.0-SNAPSHOT]	at org.airsonic.player.service.MediaFileService.checkLastModified(MediaFileService.java:164) [classes!/:10.6.0-SNAPSHOT]	at org.airsonic.player.service.MediaFileService.getMediaFile_aroundBody0(MediaFileService.java:107) [classes!/:10.6.0-SNAPSHOT]	at org.airsonic.player.service.MediaFileService$AjcClosure1.run(MediaFileService.java:1) [classes!/:10.6.0-SNAPSHOT]	at org.springframework.cache.aspectj.AbstractCacheAspect.ajc$around$org_springframework_cache_aspectj_AbstractCacheAspect$1$2bc714b5proceed(AbstractCacheAspect.aj:64) [spring-aspects-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.springframework.cache.aspectj.AbstractCacheAspect$AbstractCacheAspect$1.invoke(AbstractCacheAspect.aj:71) [spring-aspects-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:351) [spring-context-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.springframework.cache.aspectj.AbstractCacheAspect.ajc$around$org_springframework_cache_aspectj_AbstractCacheAspect$1$2bc714b5(AbstractCacheAspect.aj:80) [spring-aspects-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.airsonic.player.service.MediaFileService.getMediaFile(MediaFileService.java:99) [classes!/:10.6.0-SNAPSHOT]	at org.airsonic.player.service.MediaFileService.getMediaFile(MediaFileService.java:88) [classes!/:10.6.0-SNAPSHOT]	at org.airsonic.player.service.MediaFileService.getMediaFile(MediaFileService.java:132) [classes!/:10.6.0-SNAPSHOT]	at org.airsonic.player.service.PodcastService.lambda$9(PodcastService.java:251) [classes!/:10.6.0-SNAPSHOT]	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492) ~[na:na]	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]	at org.airsonic.player.service.PodcastService.addMediaFileIdToEpisodes(PodcastService.java:258) [classes!/:10.6.0-SNAPSHOT]	at org.airsonic.player.service.PodcastService.getEpisodes(PodcastService.java:212) [classes!/:10.6.0-SNAPSHOT]	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492) ~[na:na]	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[na:na]	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408) ~[na:na]	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736) ~[na:na]	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[na:na]	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[na:na]	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:na]	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]	at org.airsonic.player.service.PodcastService.init(PodcastService.java:120) [classes!/:10.6.0-SNAPSHOT]	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]	at org.airsonic.player.Application.main(Application.java:78) ~[classes!/:10.6.0-SNAPSHOT]	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[airsonic.war:10.6.0-SNAPSHOT]	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[airsonic.war:10.6.0-SNAPSHOT]	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[airsonic.war:10.6.0-SNAPSHOT]	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58) ~[airsonic.war:10.6.0-SNAPSHOT]

**Comment by SyntrophicConsortium** [comment]
I'm still seeing this even after #247 was merged. I tried the latest snapshot but I have a different issue with that (#250). 

It looks like it's now continuing to start despite the errors (now it skips), but then logging just stops. The webserver and audio player services appear to not load (and Airsonic doesn't load in the browser, no server response code)
2020-04-25 10:08:35.816  WARN --- o.a.p.service.MediaFileService           : Could not retrieve and update all the children for /media/win_hdd/music/mp3/Podcasts/TBTL- Too Beautiful to Live/tbtl_20200415_64.mp3. Will skipjava.nio.file.NoSuchFileException: /media/win_hdd/music/mp3/Podcasts/TBTL- Too Beautiful to Live/tbtl_20200415_64.mp3	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[na:na]	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:428) ~[na:na]	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:465) ~[na:na]	at java.base/java.nio.file.Files.list(Files.java:3527) ~[na:na]	at org.airsonic.player.service.MediaFileService.updateChildren(MediaFileService.java:379) [classes!/:11.0.0-SNAPSHOT]	at org.airsonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:199) [classes!/:11.0.0-SNAPSHOT]	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:307) [classes!/:11.0.0-SNAPSHOT]	at org.airsonic.player.service.MediaScannerService.lambda$23(MediaScannerService.java:309) [classes!/:11.0.0-SNAPSHOT]	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492) ~[na:na]	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[na:na]	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603) ~[na:na]	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[na:na]2020-04-25 10:08:35.817  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 31095 entries.2020-04-25 10:08:35.823  INFO --- o.a.p.s.MediaScannerService              : Persisting albums2020-04-25 10:08:36.194  INFO --- o.a.p.s.MediaScannerService              : Persisting artists2020-04-25 10:08:36.234  INFO --- o.a.p.s.MediaScannerService              : Marking non-present albums.2020-04-25 10:08:36.244  INFO --- o.a.p.s.MediaScannerService              : Album persistence complete2020-04-25 10:08:36.297  INFO --- o.a.p.s.MediaScannerService              : Marking present files2020-04-25 10:08:36.300  INFO --- o.a.p.s.MediaScannerService              : Persisting genres2020-04-25 10:08:36.304  INFO --- o.a.p.s.MediaScannerService              : Updating genres2020-04-25 10:08:36.330  INFO --- o.a.p.s.MediaScannerService              : Genre persistence successfully complete: true2020-04-25 10:08:36.332  INFO --- o.a.p.s.MediaScannerService              : Marking non-present artists.2020-04-25 10:08:36.333  INFO --- o.a.p.s.MediaScannerService              : Artist persistence complete2020-04-25 10:09:08.416  INFO --- o.a.p.s.MediaScannerService              : Marking non-present files.2020-04-25 10:09:08.426  INFO --- o.a.p.s.MediaScannerService              : File marking complete2020-04-25 10:09:08.426  INFO --- o.a.p.s.MediaScannerService              : Completed media library scan.2020-04-25 10:09:09.214  INFO --- o.a.p.s.MediaScannerService              : Media library scan took 94s2020-04-25 10:09:09.214  INFO --- o.a.p.service.PlaylistService            : Starting playlist import.2020-04-25 10:09:09.214  INFO --- o.a.p.service.PlaylistService            : Completed playlist import.

Is there a way to turn on more verbose logging, or is this as verbose as it gets?
> 2020-04-25 10:08:35.816  WARN --- o.a.p.service.MediaFileService           : Could not retrieve and update all the children for /media/mp3/Podcasts/TBTL- Too Beautiful to Live/tbtl_20200415_64.mp3. Will skipjava.nio.file.NoSuchFileException: /media/mp3/Podcasts/TBTL- Too Beautiful to Live/tbtl_20200415_64.mp3	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[na:na]	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:428) ~[na:na]	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:465) ~[na:na]	at java.base/java.nio.file.Files.list(Files.java:3527) ~[na:na]	at org.airsonic.player.service.MediaFileService.updateChildren(MediaFileService.java:379) [classes!/:11.0.0-SNAPSHOT]	at org.airsonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:199) [classes!/:11.0.0-SNAPSHOT]	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:307) [classes!/:11.0.0-SNAPSHOT]	at org.airsonic.player.service.MediaScannerService.lambda$23(MediaScannerService.java:309) [classes!/:11.0.0-SNAPSHOT]	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492) ~[na:na]	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[na:na]	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603) ~[na:na]	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[na:na]2020-04-25 10:08:35.817  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 31095 entries.2020-04-25 10:08:35.823  INFO --- o.a.p.s.MediaScannerService              : Persisting albums2020-04-25 10:08:36.194  INFO --- o.a.p.s.MediaScannerService              : Persisting artists2020-04-25 10:08:36.234  INFO --- o.a.p.s.MediaScannerService              : Marking non-present albums.2020-04-25 10:08:36.244  INFO --- o.a.p.s.MediaScannerService              : Album persistence complete2020-04-25 10:08:36.297  INFO --- o.a.p.s.MediaScannerService              : Marking present files2020-04-25 10:08:36.300  INFO --- o.a.p.s.MediaScannerService              : Persisting genres2020-04-25 10:08:36.304  INFO --- o.a.p.s.MediaScannerService              : Updating genres2020-04-25 10:08:36.330  INFO --- o.a.p.s.MediaScannerService              : Genre persistence successfully complete: true2020-04-25 10:08:36.332  INFO --- o.a.p.s.MediaScannerService              : Marking non-present artists.2020-04-25 10:08:36.333  INFO --- o.a.p.s.MediaScannerService              : Artist persistence complete2020-04-25 10:09:08.416  INFO --- o.a.p.s.MediaScannerService              : Marking non-present files.2020-04-25 10:09:08.426  INFO --- o.a.p.s.MediaScannerService              : File marking complete2020-04-25 10:09:08.426  INFO --- o.a.p.s.MediaScannerService              : Completed media library scan.2020-04-25 10:09:09.214  INFO --- o.a.p.s.MediaScannerService              : Media library scan took 94s2020-04-25 10:09:09.214  INFO --- o.a.p.service.PlaylistService            : Starting playlist import.2020-04-25 10:09:09.214  INFO --- o.a.p.service.PlaylistService            : Completed playlist import.

**Comment by randomnicode** [comment]
Hmm, whatever the issue is, this stack trace isn't describing it. It just says it's skipping a file. Need more details.
