### ISSUE TITLE
Duration minutes of podcasts displayed wrong

### ISSUE THREAD

**Issue by Faeb35** [airsonic-advanced/airsonic-advanced#249]
## Problem description

Duration minutes of podcasts displayed wrong.
When I browse to the podcast section, open a certain podcast and look through the list of episodes the duration of minutes is calucalted wrong. 
![grafik](https://user-images.githubusercontent.com/9485516/80281527-0adf8700-870c-11ea-902a-9b4d582f1726.png)

Seems like hours are not subtracted from the minutes.

Duration showing in Windows Explorer.
![grafik](https://user-images.githubusercontent.com/9485516/80281540-264a9200-870c-11ea-8531-6fc79b91b2cc.png)

### Steps to reproduce

1. Download some podcast episodes
2. Open the list of episodes
3. See the duration

## System information

 * **Airsonic version**: Edge Release 10.6.0-SNAPSHOT.20200424035525
 * **Operating system**: Windows Server 2012
 * **Java version**: Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
 * **Proxy server**: IIS
 * **Client**: Tested in Firefox
 * **Language**: English

**Comment by randomnicode** [comment]
Please test the snapshot release for the PR and close the issue if it works

**Comment by Faeb35** [comment]
I just tested the newest snapshot, 11.0.0-SNAPSHOT.20200426041328, but the minutes are still displayed the same as before.

**Comment by randomnicode** [comment]
Hmmm.

How did you test? The fix is forward-looking only.

The incorrect durations are now stored in the DB, so just going to the webpage isn't going to affect it.

Perhaps try refreshing the podcast? That will refresh the dates in the DB.

**Comment by Faeb35** [comment]
Ohh you're right!
I just removed a Podcast and added it again to dowload everything againg. Issue is definitly fixed!
Just refreshing the episodes doesn't help. But that's fine as it is.

Before:
![grafik](https://user-images.githubusercontent.com/9485516/80311421-dd640d80-87df-11ea-871d-554a24955c4a.png)

After:
![grafik](https://user-images.githubusercontent.com/9485516/80311475-1dc38b80-87e0-11ea-8a6a-5776f9f39468.png)
