### ISSUE TITLE
Player is broken

### ISSUE THREAD

**Issue by lud0v1c** [airsonic-advanced/airsonic-advanced#267]
## Problem description
Just installed this to replace the original Airsonic. After uploading, scanning everything and restoring the original settings, I can't play anything, nothing gets added to the queue and the Settings tab "Players" always gives me a 404 Bad Gateway (and logs me out).

Am running it with a docker compose file almost equal to the one I had with the original Airsonic, routing trafic to Traefik 2.0.

### Steps to reproduce

Really just try to play anything, add something to the queue, and go to the "Players" tab

## System information

 * **Airsonic version**: *11.0.0-SNAPSHOT.20200429045733 – April 29, 2020 at 4:57:33 AM GMT*
 * **Operating system**: *Ubuntu Server 18.04*
 * **Java version**: *java 11.0.7*
 * **Proxy server**: *It's in a network proxy for Traefik 2.0*
 * **Client**: *Latest Firefox*
 * **Language**: *English*

## Additional Information

This is what the log shows after trying to play a track:
```
2020-04-29 14:00:54.491  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /var/music/Albums/Alaska & Nucleus/1998 - Project Two _ Persistence of Vision | EventType: CREATED | Old value: null | New value: 1998 - Project Two _ Persistence of Vision
2020-04-29 14:03:23.131  INFO --- o.a.p.service.PodcastService             : Starting scheduled Podcast refresh.
2020-04-29 14:03:23.133  INFO --- o.a.p.service.PodcastService             : Completed scheduled Podcast refresh.
Inconsistency detected by ld.so: dl-lookup.c: 112: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
LOGBACK: No context given for c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1636050357
```

**Comment by randomnicode** [comment]
It wasn't mentioned here, so just checking: are you using the docker images? Or are you creating your own docker images copying in the war?

This bug was mentioned #198 also and seems to be specific to Java 11 on Ubuntu (and not related to Airsonic). Since Airsonic is also going to switch to Java 11 soon, you'll suffer this issue there too soon.

We're going to try and push up the container to a different JRE version and see if it helps

**Comment by lud0v1c** [comment]
> 
> 
> It wasn't mentioned here, so just checking: are you using the docker images? Or are you creating your own docker images copying in the war?
> 
> This bug was mentioned #198 also and seems to be specific to Java 11 on Ubuntu (and not related to Airsonic). Since Airsonic is also going to switch to Java 11 soon, you'll suffer this issue there too soon.
> 
> We're going to try and push up the container to a different JRE version and see if it helps

Yes I am, airsonic-advanced:latest. Thanks for the quick reply! Java can be a pain sometimes, hope that solves it.

**Comment by randomnicode** [comment]
merged.

please try now

**Comment by lud0v1c** [comment]
The container doesn't start now :/ 
When starting the container I get 
```
"OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"tini\": executable file not found in $PATH": uknown
```

**Comment by randomnicode** [comment]
Are you modifying the entrypoint?

**Comment by randomnicode** [comment]
added tini to the PATH. So your override should work now

**Comment by lud0v1c** [comment]
It's working now 👍 Docker logs don't show anything wrong, however it shows as "Unhealthy" on portainer, so maybe it was some old checks going on that don't work now.
Noone of the settings tabs crash it, I can add stuff to queue and play now.

**Comment by randomnicode** [comment]
👍
