### ISSUE TITLE
Can't change admin user password

### ISSUE THREAD

**Issue by znedw** [airsonic-advanced/airsonic-advanced#271]
## Problem description

This may be a silly question, but I can't see how to change the admin password in the web UI.

### Steps to reproduce

1. Settings > User > Admin, there's no password change input boxes?
![](https://u.teknik.io/clYts.png)

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20200430000326 – April 30, 2020 at 10:03:26 AM AEST

**Comment by openscallion** [comment]
This is now managed in 'credentials' tab. Look at #193 for more information. You need to create new credentials for the admin account and remove the default credentials.

**Comment by znedw** [comment]
Perfect, thank-you for that, I understand creds vs users now, I should have searched better!
