### ISSUE TITLE
Export Playlist not working

### ISSUE THREAD

**Issue by Adrian-Rasmussen** [airsonic-advanced/airsonic-advanced#279]
## Problem description
Attempting to export a playlist fails, showing 
```
The webpage at http://localhost:4040/exportPlaylist.view?id=2 might be temporarily down or it may have moved permanently to a new web address.
```

Logs show:
```
2020-05-03 16:24:14.492 ERROR --- o.a.p.s.LoggingExceptionResolver : 172.20.0.1: An exception occurred while loading http://localhost:4040/exportPlaylist.view?id=2
```

### Steps to reproduce
1. Create Playlist
2. Click Export

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20200430193915
 * **Operating system**: docker on WSL2
 * **Java version**: 14.0.1
 * **Proxy server**:  None
 * **Client**: Vivaldi 3.0.1874.33
 * **Language**: English

**Comment by SyntrophicConsortium** [comment]
I'm not the developer but I thought I would mention that I can't reproduce this, I get an open/save dialogue from my browser. I'm not using Docker. Maybe an issue specific to a Docker setup? Does Download playlist give you the same error?

**Comment by Adrian-Rasmussen** [comment]
Not sure if anything related actually changed, but export of playlists is working for me now on `11.0.0-SNAPSHOT.20200508144739`

Still having issues automatically importing playlists but that's a separate issue
