### ISSUE TITLE
Airsonic Not Saving New Admin Password

### ISSUE THREAD

**Issue by Alcatraz077** [airsonic-advanced/airsonic-advanced#291]
## Problem description

Installed airsonic-advanced docker container, used default admin/admin to login. Went to Settings -> User, changed password, saved. Logged out, tried to login with new password, Airsonic advised it was incorrect, and still had the `Airsonic is not secured. Please log in with username and
password "admin". Then change the password immediately.` message. Airsonic did accept admin/admin as the correct credentials. 

Stopped the docker, removed the image, removed the appdata folder, reinstalled the docker container. Repeated the process, issue persists. Tried multiple browsers, issue persists.

### Steps to reproduce

1. Install docker container
2. Change password to something else and save

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20200508144739 – May 8, 2020 at 9:47:39 AM CDT
 * **Operating system**: Linux/Unraid 6.8.3, using airsonicadvanced/airsonic-advanced:latest docker image.
 * **Java version**: 14.0.1
 * **Proxy server**: Let'sEncrypt/Nginx
 * **Client**: Firefox 75.0/Vivaldi 3.0.1874.33
 * **Language**: English

**Comment by toboshii** [comment]
You currently need to go to the Credentials tab in settings and delete the legacy Admin credential:
![](https://s.56k.pw/a/1mpK9Ak.png)

It seems to prefer the legacy credential over the bcrypt one so admin/admin continues to work and the new credential doesn't.

**Comment by Alcatraz077** [comment]
That fixed it, thanks @toboshii!
