### ISSUE TITLE
Impossible to assign proper timezone when using docker version

### ISSUE THREAD

**Issue by kdmn2** [airsonic-advanced/airsonic-advanced#292]
Hello,

It is currently impossible to set up a proper timezone when using docker version of the app.
That prevents last.fm scrobbling from working.
I have tried setting up -e TZ=Europe/Paris as well as mounting /etc//timezone and /etc/localtime.
Docker is using UTC timezone, while I'm in CEST.
Thanks

**Comment by randomnicode** [comment]
Hmmm...

Off the top of my head, can't recall anything other than the creation of new empty playlists (from the left controller), and in the UI maybe the last used/played tags that uses/needs a timezone.

The timestamps in the DB are all stored in UTC, no matter which timezone the JVM is in.
Also don't see how/why LastFM should be affected, given that scrobbling data is sent (by spec) in epoch and therefore requires UTC.

Nevertheless, if you'd like to change your default TZ, try passing in the JVM `user.timezone` system property (`-Duser.timezone="Europe/Paris"`) to the JVM inside docker via the `JAVA_OPTS` env var

**Comment by kdmn2** [comment]
Looks like it was just a glitch, I have re-dployed the whole system (for unrelated resason) and the issue went away.
