### ISSUE TITLE
Not an issue just some help

### ISSUE THREAD

**Issue by dorel14** [airsonic-advanced/airsonic-advanced#300]
## Problem description
I'd like to exclude some folders from being scanned, but i'am not a great specilist of Regex
Can someone help in excluding allfoldrs beginnig with _

### Steps to reproduce
Got to Parameters , in Media set excluding pattern 

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20200508144739 
 * **Operating system**: Debian 10

 * **Java version**: OPenJdk 11
 * **Proxy server**: Nginx
 * **Client**: Chrome
 * **Language**: French

Thx in advance

**Comment by randomnicode** [comment]
I don't know how you can do only _folders_ beginning with `_`, but you can exclude _paths_

you're looking for something like `^_.*`

^ = beginning of string/path
_ = underscore
.* = any number of characters after

**Comment by dorel14** [comment]
Thx perfect
