### ISSUE TITLE
subDirsTable always fix lenght of 7

### ISSUE THREAD

**Issue by Faeb35** [airsonic-advanced/airsonic-advanced#316]
I discovery that the subDirsTable in the mediaMain.jsp is always (re)set to a pageLength of 7 when loading the page.
As the value "7" is also listed in the lengthMenu array, I'm guessing this is on purpose. 

Shouldn't this setting follow the paginationSize setting from the personalSettings.jsp? If not, would it make sense to save this setting in the background locally in the browser LocalStorage?

**Comment by randomnicode** [comment]
Yeah, originally was trying to keep the subfolders table height within the image boundaries on the left.

Don't know if it's a good or bad idea.
