### ISSUE TITLE
After changing admin password, admin/admin still works

### ISSUE THREAD

**Issue by volcs0** [airsonic-advanced/airsonic-advanced#325]
## Problem description

After changing the password for 'admin', password = admin still works.
Can create new user that has admin privileges, but cannot remove original admin user.

### Steps to reproduce

1. Log in initial install with admin/admin
2. Go Users/Credentials --> Change the admin password
3. Logout
4. Log in with new credentials --> works fine
5. Logout
6. Log in with admin/admin --> also still works

## System information

Version:  11.0.0-SNAPSHOT.20200603112807 – June 3, 2020 at 6:28:07 AM CDT
Docker: airsonicadvanced/airsonic-advanced:latest
OS: unRAID 6.8.3
Client: Chrome browser (mac) and Audinaut (Android)
Language: English

**Comment by pandiloko** [comment]
I'm doing some tests with clean installations and have been able to easily to reproduce this issue. 

Both login credentials are shown under Settings>Credentials and it is trivial to get rid of the original one:

![2020-06-08_16:52](https://user-images.githubusercontent.com/10230449/84044923-79b92c80-a9a8-11ea-87a6-794b103fb8b5.png)

Nevertheless this should be taken care of.

**Comment by randomnicode** [comment]
This has been extensively covered, answered and even documented, for instance, https://github.com/airsonic-advanced/airsonic-advanced/issues/193

For ANY user, INCLUDING admin, you can ONLY do two things for creds: DELETE credentials or ADD credentials.  Credentials, once entered are immutable.

What you did was ADDED new credentials (it says that on the button when you typed in the new password). But that does NOT remove the old ones. The old ones are still there. You need to DELETE the old ones in order to remove the old credentials.

**Comment by volcs0** [comment]
Thank you for taking the time to explain this. I agree that the system acts as you describe. I'm sorry for not seeing the other issue report.

I am pointing out, however, that the way this screen looks, a user might think that this is _changing_ the admin password. I agree with you - **it does not say that**. But I got this wrong, and I like to think I have more experience than the average user. Even a warning next to "Add credentials" that says, "Note: This will not change the password - it adds a new one," would go a long way towards making this safer. Given how most systems handle user/password management, the idea of adding an additional password seems out of the ordinary.

Now that you have explained it, I see that this is not a bug. As you say, the system is behaving as intended. Just realize that a proportion of users are going to get this wrong and have admin/admin still working, thinking they changed the password. That's all.

![Screenshot 2020-06-09 16 55 18](https://user-images.githubusercontent.com/799188/84205094-0b40a100-aa72-11ea-841b-a9437dace4cd.png)

**Comment by randomnicode** [comment]
> Even a warning next to "Add credentials" that says, "Note: This will not change the password - it adds a new one," would go a long way towards making this safer.

Agreed and noted. This is a good idea.
