### ISSUE TITLE
sonos: is search supposed to work?

### ISSUE THREAD

**Issue by colinhowe** [airsonic-advanced/airsonic-advanced#330]
I've successfully connected sonos in multi-user mode and can browse/play songs no problem. I'm not seeing any search results in sonos for airsonic though. Is that expected?

I'm on the latest build: 11.0.0-SNAPSHOT.20200603112807

**Comment by randomnicode** [comment]
I'm not quite sure, I suspect it's not currently hooked up yet.

**Comment by randomnicode** [comment]
Feel free to submit a PR?

**Comment by colinhowe** [comment]
Do you have any pointers on where to start with sonos integration? Specifically, docs for their end of the integration. I probably won't get time to look at this, but, I can at least have a read and see!

**Comment by colinhowe** [comment]
Closing this issue. Retried the integration today and it works. My best guess is that the daily sync needs to have happened.
