### ISSUE TITLE
Sonos Settings Broken Error 500

### ISSUE THREAD

**Issue by ice954pw** [airsonic-advanced/airsonic-advanced#332]
## Problem description

Sonos on Latest Build is Broken

### Steps to reproduce

Click on Settings, Sonos, Crashes.

PreparedStatementCallback; bad SQL grammar [select username, linkcode, householdid, initiator, initiated from sonoslink]; nested exception is java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: INITIATOR in statement [select username, linkcode, householdid, initiator, initiated from sonoslink]

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20200602200558
 * **Operating system**: Debian
 * **Java version**: Java 13
 * **Proxy server**: OpenBSD Reverse Accelerator  Proxy
 * **Client**: Firefox/Chrome/IE

## Additional notes
Not sure where to go searching on how to fix this issue. Otherwise What a great job AA's team has done.

**Comment by randomnicode** [comment]
Hmmm... he initiator column definitely exists in the migration:

https://github.com/airsonic-advanced/airsonic-advanced/blob/master/airsonic-main/src/main/resources/liquibase/11.0/add-sonos-table-link.xml#L17

This implies either of 3 options
1. The migration didn't run correctly for some reason
2. The DB is somehow corrupted
3. The user was changed after migration

If you have access to a db tool, can you check your airsonic DB for the sonoslink table?
You could also put a link to your db folder and see if someone can diagnose it here?

**Comment by ice954pw** [comment]
Want me to host the db?

**Comment by ice954pw** [comment]
@randomnicode https://www.dropbox.com/s/l5zwven9plz8q16/db.tar.gz?dl=0 There's my DB. See if you can see anything. I'm wondering if it's torched, however I'd like to hopefully save it if possible.

**Comment by randomnicode** [comment]
Ah, here is the issue:
You must've run some migration from a different non-official branch(es) of vanilla airsonic (maybe some of the sonos forked branches). Those branches created a table of the same name in your airsonic db.

The AA migrations see the existing table, don't want to overwrite it and skip their own migrations instead.

Solution:
*If you have a db tool:*
1. you can just open the db and blow away the public.sonoslink table and the sonoslink migration row(s) recorded in dbchangelog table.

*If you don't have a db tool:*
1. make sure your airsonic-advanced is shutdown
2. open the /var/airsonic/db/airsonic.script file with a text editor
3. search for and delete all lines with the keyword "sonoslink" (delete the whole line)
4. save and restart

that should rerun the airsonic-advanced migrations needed

**Comment by ice954pw** [comment]
I did, didn't even think of it, just did restarted works great! Thanks!
