### ISSUE TITLE
Migration failing

### ISSUE THREAD

**Issue by CHBMB** [airsonic-advanced/airsonic-advanced#334]
## Problem description

Trying to a migration of an existing airsonic install that was using `linuxserver/airsonic` to `airsonic-advanced/airsonic-advanced:stable` fails.

## Steps to reproduce

My previous install

```
docker run -d \
--name=airsonic \
-e PUID=99 \
-e PGID=100 \
-e JAVA_OPTS=-Xms256m -Xmx512m \
-p 4040:4040/tcp \
-v /home/chbmb/music/:/music \
-v /home/chbmb/playlists/:/playlists \
-v /home/chbmb/podcasts/:/podcasts \
-v /opt/airsonic/:/config \
linuxserver/airsonic 
```

Airsonic Advanced install 
(prior to attempt at starting I have stopped the existing airsonic container and done a `cp -R /opt/airsonic/ /opt/airsonic-advanced`)

```
docker run -d \
--name=airsonic-advanced \
-e PUID=99 \
-e PGID=100 \
-e JAVA_OPTS=-Xms256m -Xmx512m \
-p 4040:4040/tcp \	
-v /home/chbmb//music/:/var/music \
-v /home/chbmb/playlists/:/var/playlists \
-v /home/chbmb/podcasts/:/var/podcasts \
-v /opt/airsonic-advanced/:/var/airsonic \
airsonicadvanced/airsonic-advanced:stable 
```

## Logs

[Full pastebin of logs](https://pastebin.com/rc3s4BvQ)

#### **Airsonic version**: 
  - **Docker:**`airsonicadvanced/airsonic-advanced:stable`
  - **Digest:** `sha256:c931c4d9c105662097c8485422ebab00e309254d8fa10c4ec1dbe852c1163789`
#### **Operating system**: 
  - **Distribution:** `Unraid v6.9.0 beta 22`
  - **Kernel:** `5.72`
 - **Docker Version:** `19.03.11`
#### **Java version**: 
 - **Version In Docker Image:**`openjdk 11.0.7 2020-04-14`
#### **Proxy server**:
  - **None**
#### **Client**: 
 - **Firefox 77.01 on Ubuntu 18.04**
#### **Language**: 
 - **English**

## Additional Information

A fresh setup works perfectly as one might expect.

**Comment by randomnicode** [comment]
Seems like one of your passwords for a user in your user table is null?

Perhaps you can set a password and then retry the migration?

**Comment by CHBMB** [comment]
Ah, that worked.  I've been experimenting with LDAP on regular airsonic, so I think it was a leftover dummy user from that.

Managed to migrate without issue once I deleted that user.  Thanks for the heads up.
