### ISSUE TITLE
Album 'songCount' and 'duration' properties get incremented with every scan

### ISSUE THREAD

**Issue by SteveDinn** [airsonic-advanced/airsonic-advanced#349]
## Problem description

Each time a scan is performed the 'duration' and 'songCount' are not being *set* to the sum of all the songs' values, but rather *incremented* by that amount.

### Steps to reproduce

1. Add an album. Take note of the songCount and duration properties returned by the Subsonic API.
2. Run a scan.
3. Note that the songCount and duration properties have gone up by the amount of the summed songs' values.

## System information

 * **Airsonic version**:  11.0.0-SNAPSHOT.20200708175952 (docker image)
 * **Operating system**: Linux Mint 19.3
 * **Java version**: Airsonic-Advanced docker container
 * **Proxy server**: NGINX latest, but that doesn't really apply here.
 * **Client**: Any client that shows album duration and songCount album properties
 * **Language**: English

**Comment by SteveDinn** [comment]
I'm no Java dev or I'd submit a PR for this myself, but I believe that in the MediaScannerService.updateAlbum() method, the first time you encounter an album on a re-scan the duration should be set to that track's duration, and the songCount should be set to 1. Then for subsequent tracks in that album, increment by the track's values as normal.

**Comment by randomnicode** [comment]
@SteveDinn did the newest snapshot fix it?

**Comment by SteveDinn** [comment]
Yep! I brought up a new docker container, re-scanned, and all counts and durations are good again.
