### ISSUE TITLE
Connection failure: Wrong username or password

### ISSUE THREAD

**Issue by jdewoody71** [airsonic-advanced/airsonic-advanced#360]
**Problem description:**

Using 3 different subsonic/airsonic apps for Android, if I change from the default credentials of admin/admin, the player will no longer work. 

**Steps to reproduce:**

1. Download Android app (I've tried Audinaut, Ultrasonic, & airsonic Player).
2. Change password on Airsonic Advanced server and delete the old credentials. 
3. Update password on mobile app and test connection.
4. Receive message **Connection failure: Wrong username or password**

**System information**

Server: Docker image pulled from airsonicadvanced/airsonic-advanced:latest
11.0.0-SNAPSHOT.20200717173203 – July 17, 2020 at 12:32:03 PM CDT
No proxy server, just using port forwarding.
Phone OS: Android v10, security patch level 8/5/20
English language

**Additional notes**

I have deleted the Docker and set it up 3 times now to verify that it is repeatable.
On the Audinaut player, it has the option to "Open in browser" and I can log in and use it just fine.

**Comment by SteveDinn** [comment]
What type of encryption are you using for the credentials? Most subsonic clients don't do well with bcrypt (Airsonic-advanced's default) try other encryption methods for the credentials and you'll find one that work. I went through this myself.

**Comment by jdewoody71** [comment]
Thank you very much @SteveDinn, that worked.
