### ISSUE TITLE
Playback stops after song 1

### ISSUE THREAD

**Issue by OlivierFerriot** [airsonic-advanced/airsonic-advanced#361]
## Problem description

Playback works for 1 song. That's it.
After that 99% of the time it will switch to the next song and never start playback.
If playback doesn't start on the 2nd song it will never start for the session. Very rarely a session will work correctly (emphasis on the VERY rarely)
This must be coming from airsonic as android app don't suffer from this ever (from my testing)

### Steps to reproduce

No idea there. I tried using playlist, strait adding to queue, shuffling order. Nothing seems to change the fact it never plays the next song (but it does load it).

## System information

* **Airsonic version** : Version | 11.0.0-SNAPSHOT.20200717173203 – July 17, 2020 at 7:32:03 PM CEST
 * **Operating system**: Windows 10 pro
 * **Java version**: no idea, installed as a docker on unraid latest stable version
 * **Proxy server**: None
 * **Client**: chrome latest
 * **Language**: English

## Additional notes

Maybe add an option to force playback to avoid this problem if you can't pinpoint it exactly.

**Comment by randomnicode** [comment]
Are you still connected to the server by the time the second song is supposed to play back? (Look at the Connected/Disconnected icons).

Can you open Chrome Dev Tools and see if any logs are present in the console?

**Comment by randomnicode** [comment]
> Maybe add an option to force playback to avoid this problem if you can't pinpoint it exactly.

Don't know how playback may be "forced" if we can't diagnose the issue?

**Comment by OlivierFerriot** [comment]
Ok, so I checked the log visible in the about page on airsonic :

```
2020-08-20 12:45:31.234 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: /var/music | EventType: EXPIRED | Old value: music | New value: null
2020-08-20 12:45:31.234 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: /var/music | EventType: CREATED | Old value: null | New value: music
2020-08-20 12:45:31.336 INFO --- o.a.p.c.StreamController : 192.168.x.x: Username listening to music/Jason Derulo - Swalla (ft. Nicki Minaj & Ty Dolla $ign).mp3
2020-08-20 12:45:31.337 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: /var/music/Jason Derulo - Swalla (ft. Nicki Minaj & Ty Dolla $ign).mp3 | EventType: REMOVED | Old value: Swalla (ft. Nicki Minaj & Ty Dolla $ign) | New value: null
2020-08-20 12:45:31.390 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: Username | EventType: REMOVED | Old value: Username ["JUKEBOX","COVERART","PODCAST","SETTINGS","DOWNLOAD","COMMENT","SHARE","UPLOAD","STREAM"] | New value: null
2020-08-20 12:45:31.391 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: /var/music/Jason Derulo - Swalla (ft. Nicki Minaj & Ty Dolla $ign).mp3 | EventType: CREATED | Old value: null | New value: Swalla (ft. Nicki Minaj & Ty Dolla $ign)
2020-08-20 12:45:34.683 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: Username | EventType: CREATED | Old value: null | New value: Username ["JUKEBOX","COVERART","PODCAST","SETTINGS","DOWNLOAD","COMMENT","SHARE","UPLOAD","STREAM"]
```

This are the lines corresponding to me starting playback and when  it stops after loading the next song

As for the console log in chrome here it is :
[192.168.x.x-1597919772184.log](https://github.com/airsonic-advanced/airsonic-advanced/files/5102463/192.168.x.x-1597919772184.log)


And also I'm always connected. All I need to do is to click play and the next song then starts playing. It's as if airsonic thinks there is only 1 song in the queue and then stops. Even with the repeat (Off / 1 / All) the outcome is the same.

As for what I meant by force, I don't know how the playback function works so I can't really say but I was thinking something like :
- When your start the playback, save the total song number from the queue in a variable,
- each time a song is starting subtract 1 to that var,
- then for each new song that load (which they always do atm, they just don't play after loading) unless songRemaining = 0 force playback of the queue by simulating a clic on the play button or maybe something more elegant.


Hoping that will help finding my problem :)

**Comment by randomnicode** [comment]
Hi @OlivierFerriot 

These are the (simplified view of the) operative pieces of code that makes the playback work for web players:

The songs and statuses and state carrying vars are actually stored in the vars defined here:
https://github.com/airsonic-advanced/airsonic-advanced/blob/44f4214df92b200f694b566241359fd299a21620/airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp#L72-L85

which are populated here:
https://github.com/airsonic-advanced/airsonic-advanced/blob/44f4214df92b200f694b566241359fd299a21620/airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp#L915-L916

which is called at the beginning of the pageload, or every time the server declares that the playlist has updated thereafter:
https://github.com/airsonic-advanced/airsonic-advanced/blob/44f4214df92b200f694b566241359fd299a21620/airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp#L419-L422

Now given that the page itself has all the playqueue song data, we load the audio player at pageload, and register a callback for any song's end:
https://github.com/airsonic-advanced/airsonic-advanced/blob/44f4214df92b200f694b566241359fd299a21620/airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp#L568-L569

which can be followed, and we can see that it just calls the method to go to the next song:
https://github.com/airsonic-advanced/airsonic-advanced/blob/44f4214df92b200f694b566241359fd299a21620/airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp#L549-L551

which, in turn, just looks at the repeat status and based on that either skips to the next song or keeps the same song:
https://github.com/airsonic-advanced/airsonic-advanced/blob/44f4214df92b200f694b566241359fd299a21620/airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp#L749-L756

Skipping to a particular song for web player can be followed down, as an update of the state carrying vars:
https://github.com/airsonic-advanced/airsonic-advanced/blob/44f4214df92b200f694b566241359fd299a21620/airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp#L679-L681

followed by the actual update of the audioplayer's stream and then play:
https://github.com/airsonic-advanced/airsonic-advanced/blob/44f4214df92b200f694b566241359fd299a21620/airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp#L720-L725

--

So in short, a more nuanced version of the suggestion you're making is already in place and works for most folks. Songs play and auto advance to the next song without a hitch for these folks.

Suspect there might be an issue with some browser extension that you use that may be blocking a method from performing its function (likely something in player.play() maybe?). You can put some debug points in your chrome dev tools around the code pieces we've highlighted and step through and try and figure out which extension is causing which method to block. As pointed about, the following might be relevant as it would be a susceptible target for blocking by extensions (such as Nano Defender, which you seem to use):
https://github.com/airsonic-advanced/airsonic-advanced/blob/44f4214df92b200f694b566241359fd299a21620/airsonic-main/src/main/webapp/WEB-INF/jsp/playQueue.jsp#L716-L743

Goodluck in finding your culprit.

**Comment by OlivierFerriot** [comment]
Ok, so in the last episode of "I'm a dumb fuck" I forgot to deactivate my chrome addon to stop video autoplay.....
So yeah, all works great now that I connected my brain and changed the addon so I can whitelist my airsonic address..
So you can close it all is great. 
Thanks for the help :)
