### ISSUE TITLE
make volume slider more effective at lower volumes

### ISSUE THREAD

**Issue by wabkia** [airsonic-advanced/airsonic-advanced#380]
## Problem description

the distance from silent to 75% volume on the web gui volume slider seems to happen in the first 1/8th of the slider, and then the rest of the slider controls the remaining 25% volume level. it would be nice if there was a larger range of lower volumes in the slider.

### Steps to reproduce

1) play music
2) slide slider around.

## System information

11.0.0-SNAPSHOT.20200910051238 – September 9, 2020 at 10:12:38 PM PDT
server os is freebsd
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-2)
OpenJDK 64-Bit Server VM (build 11.0.7+10-2, mixed mode)
NGINX w/ socket configuration
firefox, also verified on safari
english

## Additional notes

this is sort of difficult to describe in text. i can maybe record a video if its elusive.

thank you for airsonic-advanced!

**Comment by tari** [comment]
The player controls are all part of [mediaelement](https://github.com/mediaelement/mediaelement), so I think any changes would be best done there.

However I think the problem may be your system- it looks like mediaelement just translates its volume to the scale of whatever the current renderer uses, so I'd guess either your client OS has some weird things going on with volume control or your output devices are very nonlinear.

**Comment by randomnicode** [comment]
As @tari mentioned, this is not within the scope of airsonic-advanced, it just delegates to mejs, which in turn uses the system renderer. May we close the issue?
