### ISSUE TITLE
Service failed starting on fresh install

### ISSUE THREAD

**Issue by dorel14** [airsonic-advanced/airsonic-advanced#387]
## Problem description

Hello i am changing my vps sever and making a fresh install with the airsonic tutorial
when i try starting with java -jar airsonic.war , everything is ok 
when i try to start as a service with the systemd files given by airsonic tuto it doesn't start and in status i have this error
"""
airsonic.service: Failed at step USER spawning /usr/bin/java: Invalid argument
"""

I'am trying to start as User = root / group = root

### Steps to reproduce

1 make a fresh install with airsonic tutorial 
[https://airsonic.github.io/docs/install/war-standalone/](url)
and try to start as a service

## System information

 * **Airsonic version**: Edge Release 11.0.0-SNAPSHOT.20200916081536
 * **Operating system**: *Debian 9.
   Linux, what distribution; Stretch*
 * **Java version**: *OpenJdk11
 * **Proxy server**: Not for the moment

## Additional notes
My systemd file
"""
[Unit]
Description=Airsonic Media Server
After=remote-fs.target network.target
AssertPathExists=/var/airsonic

[Service]
Type=simple
Environment="JAVA_JAR=/var/airsonic/airsonic.war"
Environment="JAVA_OPTS=-Xmx512m"
Environment="AIRSONIC_HOME=/var/airsonic"
Environment="PORT=4040"
Environment="CONTEXT_PATH=/"
Environment="JAVA_ARGS="
EnvironmentFile=-/etc/default/airsonic
ExecStart=/usr/bin/java \
          $JAVA_OPTS \
          -Dairsonic.home=${AIRSONIC_HOME} \
          -Dserver.servlet.contextPath=${CONTEXT_PATH} \
          -Dserver.port=${PORT} \
          -jar ${JAVA_JAR} $JAVA_ARGS
User=root
Group=root
"""

**Comment by jobenvil** [comment]
@dorel14  I ended up with this configuration:

```
desigual@apollo:~$ sudo service airsonic status
● airsonic.service - Airsonic Media Server
     Loaded: loaded (/etc/systemd/system/airsonic.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2020-09-24 16:50:31 CEST; 1 weeks 1 days ago
       Docs: https://airsonic.github.io/docs/
   Main PID: 596 (java)
      Tasks: 109 (limit: 9392)
     Memory: 605.0M
     CGroup: /system.slice/airsonic.service
             └─596 /usr/local/src/jdk-11.0.6+10-jre/bin/java -Xmx700m -Dairsonic.home=/media/sda/airsonic/config -Dserver.servlet.contextPath=/airsonic -Dserver.host=0.0.0.0 -Dserver.port=8070 -Djava.>

Okt 02 03:00:04 apollo java[596]: 2020-10-02 03:00:04.264  INFO --- o.a.p.s.MediaScannerService              : Artist persistence complete
Okt 02 03:00:04 apollo java[596]: 2020-10-02 03:00:04.264  INFO --- o.a.p.s.MediaScannerService              : Genre persistence successfully complete: true
Okt 02 03:00:04 apollo java[596]: 2020-10-02 03:00:04.956  INFO --- o.a.p.s.MediaScannerService              : Marking non-present files.
Okt 02 03:00:04 apollo java[596]: 2020-10-02 03:00:04.961  INFO --- o.a.p.s.MediaScannerService              : File marking complete
Okt 02 03:00:04 apollo java[596]: 2020-10-02 03:00:04.962  INFO --- o.a.p.s.MediaScannerService              : Completed media library scan.
Okt 02 03:00:05 apollo java[596]: 2020-10-02 03:00:05.489  INFO --- o.a.p.s.MediaScannerService              : Media library scan took 4s
Okt 02 03:00:05 apollo java[596]: 2020-10-02 03:00:05.489  INFO --- o.a.p.service.PlaylistService            : Starting playlist import.
Okt 02 03:00:05 apollo java[596]: 2020-10-02 03:00:05.490  INFO --- o.a.p.service.PlaylistService            : Completed playlist import.
Okt 02 16:57:21 apollo java[596]: 2020-10-02 16:57:21.454  INFO --- o.a.p.service.PodcastService             : Starting scheduled Podcast refresh.
Okt 02 16:57:21 apollo java[596]: 2020-10-02 16:57:21.456  INFO --- o.a.p.service.PodcastService             : Completed scheduled Podcast refresh.


desigual@apollo:~$ cat /etc/systemd/system/airsonic.service
[Unit]
Description=Airsonic Media Server
Documentation=https://airsonic.github.io/docs/
After= network.target
#remote-fs.target
#AssertPathExists=/var/airsonic
AssertPathExists=/media/sda/airsonic

[Service]
Type=simple
#Type=forking
Restart=on-failure
#ExecStop=-/usr/bin/kill -HUP $MAINPID
PIDFile=/run/airsonic.pid
ExecReload=/usr/bin/kill -HUP $MAINPID
SuccessExitStatus=143
#KillMode=process
#Environment="JAVA_JAR=/var/airsonic/airsonic.war"
Environment="JAVA_JAR=/media/sda/airsonic/airsonic.war"
Environment="JAVA_OPTS=-Xmx700m"
#Environment="AIRSONIC_HOME=/var/airsonic"
Environment="AIRSONIC_HOME=/media/sda/airsonic/config"
Environment="PORT=8070"
Environment="CONTEXT_PATH=/airsonic"
Environment="JAVA_ARGS="
EnvironmentFile=-/etc/default/airsonic
#ExecStart=/usr/bin/java \
#ExecStart=/usr/local/src/jdk8u242-b08-jre/bin/java \
ExecStart=/usr/local/src/jdk-11.0.6+10-jre/bin/java \
          $JAVA_OPTS \
          -Dairsonic.home=${AIRSONIC_HOME} \
#          -Dserver.context-path=${CONTEXT_PATH} \
          -Dserver.servlet.contextPath=${CONTEXT_PATH} \
          -Dserver.host=0.0.0.0 \
          -Dserver.port=${PORT} \
          -Djava.awt.headless=true \
          -Dserver.use-forward-headers=true \
#          -Ddebug \
#         -verbose:gc \
          -jar ${JAVA_JAR} $JAVA_ARGS
#User=airsonic
User=desigual
#Group=airsonic
Group=desigual

# See https://www.freedesktop.org/software/systemd/man/systemd.exec.html
# for details
#DevicePolicy=closed
#DeviceAllow=char-alsa rw
#NoNewPrivileges=yes
#PrivateTmp=yes
#PrivateUsers=yes
#ProtectControlGroups=yes
#ProtectKernelModules=yes
#ProtectKernelTunables=yes
#RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
#RestrictNamespaces=yes
#RestrictRealtime=yes
#SystemCallFilter=~@clock @debug @module @mount @obsolete @privileged @reboot @setuid @swap
#ReadWritePaths=/var/airsonic
#ReadWritePaths=/media/sda/airsonic

# You can uncomment the following line if you're not using the jukebox
# This will prevent airsonic from accessing any real (physical) devices
#PrivateDevices=yes

# You can change the following line to `strict` instead of `full`
# if you don't want airsonic to be able to
# write anything on your filesystem outside of AIRSONIC_HOME.
#ProtectSystem=full

# You can uncomment the following line if you don't have any media
# in /home/…. This will prevent airsonic from ever reading/writing anything there.
#ProtectHome=true

# You can uncomment the following line if you're not using the OpenJDK.
# This will prevent processes from having a memory zone that is both writeable
# and executeable, making hacker's lifes a bit harder.
#MemoryDenyWriteExecute=yes


[Install]
WantedBy=multi-user.target

desigual@apollo:~$ ps -ef| grep -i airsonic
desigual     596       1  0 Sep24 ?        00:35:19 /usr/local/src/jdk-11.0.6+10-jre/bin/java -Xmx700m -Dairsonic.home=/media/sda/airsonic/config -Dserver.servlet.contextPath=/airsonic -Dserver.host=0.0.0.0 -Dserver.port=8070 -Djava.awt.headless=true -Dserver.use-forward-headers=true -jar /media/sda/airsonic/airsonic.war --illegal-access=warn
```

I use a specific user, like you can see, if you change your your mind to not use root.

**Comment by dorel14** [comment]
Thx 
My systemd file
'''
[Unit]
Description=Airsonic Media Server
After=remote-fs.target network.target
AssertPathExists=/var/airsonic

[Service]
Type=simple
Environment="JAVA_JAR=/var/airsonic/airsonic.war"
Environment="JAVA_OPTS=-Xmx512m"
Environment="AIRSONIC_HOME=/var/airsonic"
Environment="PORT=4040"
Environment="CONTEXT_PATH=/"
Environment="JAVA_ARGS="
EnvironmentFile=-/etc/default/airsonic
ExecStart=/usr/bin/java \
          $JAVA_OPTS \
          -Dairsonic.home=${AIRSONIC_HOME} \
          -Dserver.context-path=${CONTEXT_PATH} \
          -Dserver.port=${PORT} \
          -jar ${JAVA_JAR} $JAVA_ARGS
User=root
Group=root

# See https://www.freedesktop.org/software/systemd/man/systemd.exec.html
# for details
DevicePolicy=closed
DeviceAllow=char-alsa rw
NoNewPrivileges=yes
PrivateTmp=yes
#PrivateUsers=yes
ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
RestrictNamespaces=yes
RestrictRealtime=yes
SystemCallFilter=~@clock @debug @module @mount @obsolete @privileged @reboot @setuid @swap
ReadWritePaths=/var/airsonic

# You can uncomment the following line if you're not using the jukebox
# This will prevent airsonic from accessing any real (physical) devices
#PrivateDevices=yes

# You can change the following line to `strict` instead of `full`
# if you don't want airsonic to be able to
# write anything on your filesystem outside of AIRSONIC_HOME.
ProtectSystem=full

# You can uncomment the following line if you don't have any media
# in /home/…. This will prevent airsonic from ever reading/writing anything there.
#ProtectHome=true

# You can uncomment the following line if you're not using the OpenJDK.
# This will prevent processes from having a memory zone that is both writeable
# and executeable, making hacker's lifes a bit harder.
#MemoryDenyWriteExecute=yes


[Install]
WantedBy=multi-user.target
'''
