### ISSUE TITLE
Problem playing MP3 files with periods or spaces in filename

### ISSUE THREAD

**Issue by glenstewart** [airsonic-advanced/airsonic-advanced#388]
## Problem description

Song won't play.  Log:

2020-10-02 14:29:40.595 WARN --- o.a.p.service.MediaFileService : Could not retrieve and update all the children for /home/mp3/mad_at_the_world/Hope/01.Healing On Planet Earth.mp3. Will skip
--
 
java.nio.file.NotDirectoryException: /home/mp3/mad_at_the_world/Hope/01.Healing On Planet Earth.mp3
at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:431) ~[na:na]

### Steps to reproduce

Name a MP3 file this way:  01.Healing On Planet Earth.mp3  in a folder hierarchy named mad_at_the_world/Hope/

Index collection.

Set default sort mode for all folders as "Recent"

Click on folder icon for "Hope"

Click on play button on song 01.Healing On Planet Earth.mp3

For me, nothing happens, but Log shows error at top.  If I type ls -l "/home/mp3/mad_at_the_world/Hope/01.Healing On Planet Earth.mp3" I get a hit.

## System information

 * **Airsonic version**: Happens on latest 10.x and 11.x
 * **Operating system**: Linux
   Linux, what distribution; Lubuntu 20.04
 * **Java version**: 14.0.1
 * **Proxy server**: None
 * **Client**: Opera, Firefox, Chromium - latest versions
 * **Language**: English

**Comment by randomnicode** [comment]
Cannot reproduce. This seems like an issue with your file system. It seems to think that mp3 is a directory.

Spaces and periods are a regular part of filenames, including some files that are in the test harness that automatically get tested with each build. If there was an issue with periods or spaces in the filename, these tests would fail. Out of curiosity, this exact naming scheme you recommended was also checked but didn't cause an issue (the file played just fine).
