### ISSUE TITLE
[Solved] Unable to log Dsub into Airsonic server

### ISSUE THREAD

**Issue by the1poet** [airsonic-advanced/airsonic-advanced#394]
## Problem description

When trying to log Dsub into my AA server (local ip and port), I get:
Error
Connection Failutre. Wrong username or password.

### Steps to reproduce

1. Open Dsub
2. Go into Dsub server settings
3. Enter the LAN IP and port
4. Enter user/pass
5. Select "Test connection"

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20201007202626 – October 8, 2020 at 7:26:26 AM AEDT
 * **Operating system**: unraid 6.9.0 beta30, running from airsonicadvanced/airsonic-advanced:latest docker
 * **Proxy server**: None
 * **Client**: Dsub
 * **Language**: English

## Additional notes
I have used the original Airsonic distro and had no issues loggin in with the Dsub android app

**Comment by SteveDinn** [comment]
Create credentials in Airsonic-advanced using the less secure encryption methods. DSub just doesn't like Advanced's default of bcrypt. I use AES.

**Comment by the1poet** [comment]
> 
> 
> Create credentials in Airsonic-advanced using the less secure encryption methods. DSub just doesn't like Advanced's default of bcrypt. I use AES.

Hi, thanks. That worked!

**Comment by khannurien** [comment]
By the way, it seems an error code can be returned by the API to allow the client to reconnect:
https://github.com/daneren2005/Subsonic/issues/1029#issuecomment-722142634

**Comment by randomnicode** [comment]
Can we please test this now on DSub?
