### ISSUE TITLE
Error with Docker Compose

### ISSUE THREAD

**Issue by Trufax** [airsonic-advanced/airsonic-advanced#406]
## Problem description

HI,

i cannot start the airsonicadvanced docker image when using docker-compose

### Steps to reproduce

Created the following docker-compose file in the home directory:

> version: "2.1"
> services:
> airsonic:
>     image: airsonicadvanced/airsonic-advanced
>     container_name: airsonic
>     environment:
>       - PUID=1000
>       - PGID=1000
>       - TZ=Europe/Berlin
>     volumes:
>       - /media/asadata/data:/config
>       - /media/asadata/music:/music
>       - /media/asadata/playlists:/playlists
>       - /media/asadata/data/podcasts:/podcasts
>    ports:
>       - 4040:4040
>     restart: always
> 

when i use the command `docker-compose up` i get the following error: 

> XXXXXX@airsonic:~/asad$ docker-compose up
> Starting airsonic ... done
> Attaching to airsonic
> airsonic    | Docker USER id: 0
> airsonic    | Docker PUID env: 1000
> airsonic    | Docker USER group: 0
> airsonic    | Docker PGID env: 1000
> airsonic    | usermod: no changes
> airsonic    | Process will run as:
> airsonic    | User: 1000
> airsonic    | Group: 1000
> airsonic    | mkdir: cannot create directory ‘/var/airsonic/transcode’: Permission denied

## System information

 * **Airsonic version**: latest docker image
 * **Operating system**: Ubuntu 20.04.1 LTS

**Comment by gimmelemons** [comment]
Hi, did you check if the user has permissions to access `/var/airsonic` ?

Most likely `chown -R <user>:<user> <airsonic directory>` should fix it.

**Comment by nishantbb** [comment]
Was this resolved?

**Comment by Trufax** [comment]
Yes i had set the wrong permissions on the folders.
