### ISSUE TITLE
Mutliple songs added to queue

### ISSUE THREAD

**Issue by dorel14** [airsonic-advanced/airsonic-advanced#410]
## Problem description

When i click on the arrow for playing in album view , ir adds the song and all the  songs after the one i click to the play queue

### Steps to reproduce

*Describe how somebody else could observe the same behavior you do. If possible,
include relevant configuration or files that cause the problem. If sharing media
files, ensure you are legally permitted to share copies!*

1. *Go to album view
2. *Click on the arrow for playing the first song
3. *=> all the album is added to play queue

## System information

 * **Airsonic version**: *11.0.0-SNAPSHOT.20201007202626 
 * **Operating system**: *Debian 9
 * **Java version**: *OpenJdK 11
 * **Proxy server**: *NGINX
 * **Client**: *Chrome
 * **Language**: *French

**Comment by randomnicode** [comment]
We cannot reproduce this behavior. Is this behavior still persisting? If not, can we close this issue please?

**Comment by dorel14** [comment]
Perhaps it was a cache issue so it doesn't download all js correctly 
Ok i close , it's now working
