### ISSUE TITLE
Cannot authenticate REST calls using salted hash

### ISSUE THREAD

**Issue by FoxxMD** [airsonic-advanced/airsonic-advanced#413]
## Problem description

I cannot authenticate REST calls using the [salted password hash](http://www.subsonic.org/pages/api.jsp#authentication) described in the subsonic api docs. The response is always Code 40 `Wrong username or password.` In my logs I see
```
2020-12-08 13:54:32.950 INFO --- o.a.p.s.GlobalSecurityConfig : Login failed from [xxx.xxx.x.x]
```

I am able to authenticate using the plaintext method. I'm also confident my hashing code is fine because the salted hash approach works using a regular airsonic instance.

### Steps to reproduce

* Salt and hash your password
* Visit a rest endpoint with an authentication query string

EX (using viewable page)
```
http://localhost:4040/airsonic/rest/ping.view?u=yourUsername&t=2df2780e12a60d12a886d531d6afaed9&s=9a29a22b8eaa3ddc00d7&v=1.15.0&c=myapp&f=json
```

## System information

I am using the `latest` tag from [dockerhub](https://hub.docker.com/r/airsonicadvanced/airsonic-advanced)

 * **Airsonic version**: 11.0.0-SNAPSHOT.20201007202626 – October 7, 2020 at 4:26:26 PM EDT

 * **Client**: `superagent@^6.1.0`

**Comment by The-Exterminator** [comment]
Try to Create credentials in Airsonic-advanced using the less secure encryption methods. I use AES.

**Comment by FoxxMD** [comment]
That worked. I had to create new credentials using one of the **Decodable** options.
