### ISSUE TITLE
Checking further because the ID3 Tag ends at

### ISSUE THREAD

**Issue by The-Exterminator** [airsonic-advanced/airsonic-advanced#414]
Hello.

Some .mp3 files get this error : 
Checking further because the ID3 Tag ends at 0x73749 but the mp3 audio doesnt start until 0x73953
Checking further because the ID3 Tag ends at 0x2748d but the mp3 audio doesnt start until 0x2762e
The numbers in the error is not allways the same.

But how can i repair the error. ???

Thanks.

## System information
airsonic-advanced:        Edge Release 11.0.0-SNAPSHOT.20201007202626
Server version name:    Apache Tomcat/9.0.31 (Debian)
Server built:                  Jul 15 2020 11:43:33 UTC
Server version number: 9.0.31.0
JVM Version:               11.0.9.1+1-post-Raspbian-1deb10u2
JVM Vendor:                Raspbian

**Comment by randomnicode** [comment]
airsonic is not an audio file repair tool. I imagine ffmpeg could do it but you'd have to ask them

**Comment by The-Exterminator** [comment]
But the error is not on the airsonic, only on the advance version.

**Comment by randomnicode** [comment]
Airsonic and advanced use same libraries for decoding id3 data
