### ISSUE TITLE
Informations

### ISSUE THREAD

**Issue by dorel14** [airsonic-advanced/airsonic-advanced#415]
Hello
Linked to #404 , is there a way (api or something else)  to add music to the play queue ?
Perhaps i can make an external thing in python 

## System information

 * **Airsonic version**: *11.0.0-SNAPSHOT.20201007202626
 * **Operating system**: *debian 9

 * **Java version**: *OPENJDK 11
 * **Proxy server**: *Nginx
 * **Client**: *Chrome
 * **Language**: *French

**Comment by randomnicode** [comment]
via rest:
to the Playqueue: no
to a playlist: yes

the standard subsonic api is defined here:
http://www.subsonic.org/pages/api.jsp

we could make additions, but they'd be airsonic additions to the subsonic api

note the webpage makes changes via websockets to the playqueue

**Comment by dorel14** [comment]
OK thx
