### ISSUE TITLE
many podcast issues when using mariadb

### ISSUE THREAD

**Issue by jmgant** [airsonic-advanced/airsonic-advanced#416]
## Problem description
I am using airsonic-advanced with mariadb in docker.
I immediately ran into an issue when adding podcasts.
I no longer have the exact error, but the gist was that my 'description' column in the podcast_channel table was too small to accommodate the new podcast. I manually changed it from varchar 384 (the default) to varchar 2400. I did the same with podcast_episode description.
After that podcasts were successfully added to the library.
However now, when selecting the podcast tab in the web client, airsonic hangs. For minutes the page simply does not load.
It does eventually load properly. But after a long wait. Is the reason for the hang to do with the resizing of those columns I mentioned?

**Comment by randomnicode** [comment]
>I am using airsonic-advanced with mariadb in docker.
which mariadb?

> I no longer have the exact error, but the gist was that my 'description' column in the podcast_channel table was too small to accommodate the new podcast.  I manually changed it from varchar 384 (the default) to varchar 2400. I did the same with podcast_episode description.

I think depending on your mariadb version and collation and charset, this may be an issue

> Is the reason for the hang to do with the resizing of those columns I mentioned?

Possibly?

I think we should make the description column a text column. this issue has come up too many times...

**Comment by randomnicode** [comment]
Btw, for more reading: https://github.com/airsonic/airsonic/issues/1563
