### ISSUE TITLE
[Feature Request] Longer timeline

### ISSUE THREAD

**Issue by Trufax** [airsonic-advanced/airsonic-advanced#422]
Hi,

i switched from Subsonic to Airsonic and everything seems to work well for now, thanks for all the effort keeping the Software up an running! The only big drawback i see now is this tiny timeline i have to scroll through the tracks.

I know there is various projects to rebuild the WebUI but none of them seem to be mature enough to switch to it jet. So i would like to open a feature request to extend the length of the timeline so its easier to scroll through long sets (like 1h+) (similar to Subsonic).

Thank you!

**Comment by randomnicode** [comment]
Does this work? It should automatically flex to take the space available in your window

**Comment by Trufax** [comment]
Hello, thanks for the feedback. I have to admit iam a github noob so iam not sure how to confirm the change is good. According to your post it should start with 300px but extend based on the space available ? Is there a way for me to test this? I run the official docker container at the moment. And thank you for considering this change in the first place !

Iam happy to test if someone can tell me how =)

**Comment by randomnicode** [comment]
The new docker image should have it.

New docker images are built every time there is a merge on this repo.

**Comment by Trufax** [comment]
I did an update of the docker container and now i have the long timeline, thanks for that! However the content of all folders is shown as empty. I seems to be related to nginx config since its works without porxy however i did not chance any config on the proxy side so its wierd it stopped working after the airsonic update.

**Comment by Trufax** [comment]
Issue resolved with commit: https://github.com/airsonic-advanced/airsonic-advanced/pull/434
