### ISSUE TITLE
BUG: Long tracks are stopped at a random point

### ISSUE THREAD

**Issue by Trufax** [airsonic-advanced/airsonic-advanced#423]
## Problem description

Long tracks (tested 1h+) are stopped at a random position (most of the time at 50 minutes +) and than it jumps to the next track in the playlist. Also buffering is only happening in portions i never see the full track time in the timline until the very end of the track (if it reaches it and does not skip)

### Steps to reproduce

Play a track with 2h, at some point airsonic will just jump to the next track in the playlist. I Can upload a test track if required. 

## System information

 * **Airsonic version**: *the version listed on the About page*
 11.0.0-SNAPSHOT.20201007202626
 * **Operating system**: *the operating system you're running Airsonic on.
 Ubuntu Server 20.04.1
 * **Java version**: *the Java version you are using to run Airsonic.*
 java 14.0.2
 * **Proxy server**: *if running Airsonic behind a proxy, what server and
 No
 * **Client**: *what browser and version you use to access the Airsonic web
Firefox 84.01 on Windows
 * **Language**: *which langauge/internationalization is in use*
EN

**Comment by The-Exterminator** [comment]
I drive the airsonic adv on a raspberry 4, and have not the problem.

**Comment by Trufax** [comment]
Thanks for the reply. I think it might be related to transcoded tracks. Because it only seem to happen for transcoded material.

**Comment by The-Exterminator** [comment]
I drive the standar transcode

**Comment by Trufax** [comment]
Yes i do this as well. Its seems that it only appears for long sets.

**Comment by Trufax** [comment]
i will close the bug until i further investigate. I did not figure out yet when it happens but it seem to be linked to very long sets (1h+).
