### ISSUE TITLE
Video player has no fullscreen option

### ISSUE THREAD

**Issue by bolinocroustibat** [airsonic-advanced/airsonic-advanced#446]
## Problem description

There is no fullscreen option on the integrated video player.

## System information

AirSonic 11.0.0-SNAPSHOT.20201007202626
Debian 10
OpenJDK version 11.0.9
Running under Apache 2.4 proxy
Client Chrome 86

**Comment by randomnicode** [comment]
we should probably revamp how video is done period.

**Comment by bolinocroustibat** [comment]
In the meantime, is there any previous version of Airsonic advanced we could use to have the fullscreen option on the video player?

**Comment by randomnicode** [comment]
The video player code hasn't really been touched, so it's the same as vanilla Airsonic.
We'll see about adding a fullscreen option for now.
