### ISSUE TITLE
Big track not cached as fast as it should

### ISSUE THREAD

**Issue by dorel14** [airsonic-advanced/airsonic-advanced#448]
## Problem description

I some flac files more than 50mb and for these file i can see the cache not being pushed as fast as it should be so my song is cut multiple times since cache is OK 

It nevers happens for songs less than 50mb

### Steps to reproduce

Try to listen for a track more than 50mb in flac with no reencoding set 

## System information

 * **Airsonic version**: *11.0.0-SNAPSHOT.20210119054517
 * **Operating system**: *Debian 9

 * **Java version**: OPen JDK 11.
 * **Proxy server**: *Nginx 
 * **Client**: *Chrome
 * **Language**: *FR-fr

## Additional notes
My nginx conf
~~~
# Redirect HTTP to HTTPS
server {
    listen      80;
    server_name myserver.tk;
    return      301 https://$server_name$request_uri;
}

server {

    # Setup HTTPS certificates
    listen  443 default ssl ;
    server_name  myserver.tk;
    ssl_certificate     /etc/letsencrypt/live/myserver.tk/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/myserver.tk/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


    # Proxy to the Airsonic server
    location / {
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "Upgrade";
        proxy_set_header Origin '';
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host  $http_host;
        proxy_set_header Host              $http_host;
        proxy_max_temp_file_size           0;
        proxy_pass                         http://127.0.0.1:4040;
        proxy_redirect                     http:// https://;
        proxy_buffering off;
        proxy_request_buffering off;


        client_max_body_size 500M;

        access_log      /var/log/nginx/airsonic_access.log;
        error_log       /var/log/nginx/airsonic_error.log;
       #access_log      off;
}
}

~~~

**Comment by randomnicode** [comment]
>  i can see the cache not being pushed as fast as it should be

Which cache?

>my song is cut multiple times 

What does cut here mean?

**Comment by dorel14** [comment]
Hello 
Reading the song is stopped until the cache charge something like 10sec to 1mns and after ths charging stopped /charge/play til the end of the song

**Comment by randomnicode** [comment]
This is likely a mediaelement issue because browser related elements are simply delegated to mejs.

I don't think the server is affected or is unable to respond to the request, it's just that the browser doesn't make the request
