### ISSUE TITLE
Issues with access through nginx

### ISSUE THREAD

**Issue by cascooscuro** [airsonic-advanced/airsonic-advanced#453]
## Problem description

With latest releases I'm seeing issues connecting to airsonic UI through nginx proxy.
The disconnected/connected icon always shows disconnected. Trying to browse Albums inside artists or songs inside albums  always shows as "No data available in table".

I'm running nginx with this config:

'''

    location /airsonica {
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "Upgrade";
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host  $http_host;
        proxy_set_header Host              $http_host;
        proxy_max_temp_file_size           0;
        proxy_pass                         http://x.x.x.x:8081;
        proxy_redirect                     http:// https://;
        proxy_buffering off;
        proxy_request_buffering off;
        client_max_body_size 0;
'''  

If I connect directly to instance bypassing nginx it works ok. 

With version 11.0.0-SNAPSHOT.20201007202626 it also works ok.

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20210122223024
 * **Operating system**: *Linux*
 * **Java version**: Apache Tomcat/9.0.41, java 11.0.10, Linux (1.18 GB / 1.49 GB)*
 * **Proxy server**: *nginx/1.19.6*

**Comment by randomnicode** [comment]
Suspect has to do with the new Origin stuff
Try adding the following line to your config
```
proxy_set_header Origin            '';
```

**Comment by cascooscuro** [comment]
Fixed!!!

Thank your very much.

In case others may face similar issues, the working config now is:

'''

    location /airsonica {
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "Upgrade";
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host  $http_host;
        proxy_set_header Host              $http_host;
        proxy_max_temp_file_size           0;
        proxy_pass                         http://x.x.x.x:xxxx;
        proxy_redirect                     http:// https://;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_set_header Origin            '';
        client_max_body_size 0;

'''
