### ISSUE TITLE
Linking Airsonic to Sonos

### ISSUE THREAD

**Issue by PascalBu** [airsonic-advanced/airsonic-advanced#458]
## Problem description

Cannot link Airsonic Advanced to Sonos (SYMFONISK)

### Steps to reproduce

Fresh Airsonic Advanced Docker install on Synology NAS
Adding Sonos service in Airsonic settings results in "No controllers found"
In Sonos app no service is displayed so adding Airsonic service through instructions http://www.subsonic.org/pages/sonos.jsp, login results in access denied with partial logs below

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20210122223024
 * **Operating system**: Docker on Synology NAS
 * **Java version**: java 14.0.2
 * **Proxy server**:  None
 * **Client**: Chrome (works fine), Sonos v2 app
 * **Language**: English

## Additional notes

[_AirsonicAdvanced_logs.txt](https://github.com/airsonic-advanced/airsonic-advanced/files/5879254/_AirsonicAdvanced_logs.txt)

**Comment by randomnicode** [comment]
Hmm, seems like a login issue.

Not sure how it works on Subsonic, but airsonic-advanced actually has two mechanisms for Sonos integration: an anonymous mode and a user-based mode. The airsonic-advanced link process is described here: https://github.com/simojenki/airsonic-docs/blob/master/configure/sonos.md

First things: Your log file is incomplete. Please send the full log file. Second, What is your status of the link in Settings->Sonos?

**Comment by PascalBu** [comment]
RTFM, sorry. Completely missed the docs! All working fine now! Thanks
