### ISSUE TITLE
No folder content after upgrading from 20201007105549 to 20210130073922

### ISSUE THREAD

**Issue by bolinocroustibat** [airsonic-advanced/airsonic-advanced#462]
## Problem description

After updating from 20201007105549 to 20210130073922, no subdirectory nor files are listed anymore when a directory is clicked from the sidebar.
It was also the case with a recent version around week ago. I tried reindexing with no success.
Is there a DB version update to take into account, or a reindexing to do?
I rollbacked to 20201007105549 both times and it was fine again, with no need to reindex.

## System information

AirSonic 11.0.0-SNAPSHOT.20210130073922
Debian 10
OpenJDK version 11.0.9
Running under Apache 2.4 proxy
Client Chrome 86

Airsonic is using the default integrated DB.

**Comment by randomnicode** [comment]
There are DB migrations but no DB version change between them.

Are you connected to the server in the top-right (does it say Connected?)

And it mentions you're behind a proxy. So this may apply also (the comment is for nginx, but the equivalent for Apache should apply, you need to add an Origin Header that the proxy is passing back to Airsonic-Advanced)
https://github.com/airsonic-advanced/airsonic-advanced/issues/453#issuecomment-767024237

**Comment by bolinocroustibat** [comment]
Thanks! Indeed I use an Apache reverse proxy, and it says "disconnected. I tried connecting with no success. So I guess your diagnosis is correct.

I have been trying the Apache directive:
Header              add             Access-Control-Allow-Origin "*"
...with no success for now. Will inquire more and update if I find.

**Comment by randomnicode** [comment]
>  Header add Access-Control-Allow-Origin "*"

Wrong header name, value and in the wrong direction.
The name is `Origin`, the value is empty `''` (NOT `*`), and it's for the incoming request TO airsonic (not outbound FROM airsonic)

Try this, maybe this'll work:
```
RequestHeader set Origin ''
```

**Comment by bolinocroustibat** [comment]
I tried it as well, unfortunately doesn't.

**Comment by cfitzw** [comment]
+1 Also having this exact issue running behind Apache reverse proxy.

**Comment by bolinocroustibat** [comment]
@cfitzw Didn't find the directive that solves the issue until now.
This is currently the content of my Apache vhost for Airsonic:

```
ProxyPass                  /airsonic       http://127.0.0.1:8080/airsonic
ProxyPassReverse    /airsonic       http://127.0.0.1:8080/airsonic
RequestHeader         set                X-Forwarded-Proto "https"
RequestHeader         set                Origin ''
```

**Comment by lolomin** [comment]
Hi,

Can confirm the same problem with an Apache Reverse Proxy 2.4.46 under Fedora 33 ...
Tried a lot of configurations but unable to find a way to make it working.


-rw-r--r--  1 airsonic airsonic 95084385 Oct  7 22:34 airsonic-advanced_v11.0.0-SNAPSHOT.20201007202626.war
-> Everything is OK

-rw-r--r--  1 airsonic airsonic 95299920 Jan 19 06:52 airsonic-advanced_v11.0.0-SNAPSHOT.20210119054517.war
-rw-r--r--  1 airsonic airsonic 95089926 Feb  2 17:50 airsonic-advanced_v11.0.0-SNAPSHOT.20210202164746.war
-> Playlists are empty, folder content empty, got some 403 and 500 in Apache logs ...

Regards,

lolo

**Comment by luxdi** [comment]
I can confirm the same issue with Caddy reverse proxy on Raspbian.

**Comment by cfitzw** [comment]
PR #467 resolved the issue. No changes or updates were required on the Apache reverse proxy.

**Comment by randomnicode** [comment]
can we close this issue?

**Comment by bolinocroustibat** [comment]
Yes, just tested with 11.0.0-SNAPSHOT.20210204213421 under Apache 2.4 reverse proxy, runs fine now! Thanks!
