### ISSUE TITLE
Can't disable transcoding.

### ISSUE THREAD

**Issue by hboetes** [airsonic-advanced/airsonic-advanced#466]
Version: `11.0.0-SNAPSHOT.20210202164746 – February 2, 2021 at 5:47:46 PM CET`

I don't want to use transcoding, so I tried to disable this setting at settings→transcoding:
```Enable transcoding settings for all existing and new players.```

And to my surprise you can't really switch it off. It's switched back on after a reload of the page.

**Comment by xenouch** [comment]
Same issue.

Transcoding stay enable after i disable this setting.

When a create new player all transcoding checkbox is checked.

**Comment by xenouch** [comment]
Any update ?
