### ISSUE TITLE
Duplicate entries whilst paging through getAlbumList2 API responses

### ISSUE THREAD

**Issue by ctedgar** [airsonic-advanced/airsonic-advanced#483]
## Problem description

*Hello, I'm seeing duplicate album entries whilst paging through [getAlbumList2 ](http://www.subsonic.org/pages/api.jsp#getAlbumList2) API responses, in particular, when paging through the "newest" albums. E.g. I execute the request to get the first 20 newest albums (size=20 and offset=0). I then execute the request to get the next 20 newest albums (size=20 and offset=20) and item 18 from the first request appears in the second request.

I've snooped around the code base and it seems this is partly to do with how the "created" field of an album is being populated when the file is scanned (many albums have the exact same created time - I would think this would be highly unlikely given the timestamp should be precise enough). 

Another reason is due to the way the query to retrieve the albums from the datastore is executed. Looking at the [code to retrieve the newest albums](https://github.com/randomnicode/airsonic-advanced/blob/3a3edfc20b1a26a741d34f6ee115b7e2b520518d/airsonic-main/src/main/java/org/airsonic/player/dao/AlbumDao.java#L248),  we are ordering solely by the "created" field. For albums with the exact same "created" field, we have no guarantees for ordering (at least I'm not seeing any...). I think adding "id" to the order by would solve this as it's unique (see screenshots below). I have only noticed this in the getAlbumList responses but I suspect this can happen in any of the pageable API request where ordering by a timestamp field is an option.

Addressing either one or both would fix this - with the latter (adding "id" to the order by) being the most straight forward.

### Steps to reproduce

Connect to your airsonic DB 

1. Execute the query that airsonic uses to obtain the newest albums with a size of 20 and offset of 0
![image](https://user-images.githubusercontent.com/23557307/108001932-c0eec700-6fe5-11eb-975e-fa5d0e10f7e2.png)

2. Execute the query that airsonic uses to obtain the newest albums with a size of 20 and offset of 20
![image](https://user-images.githubusercontent.com/23557307/108002046-365a9780-6fe6-11eb-89b9-007fdf43880f.png)

Note how ordering is not guaranteed as there is a handful of albums with a "created" timestamp of "04:45:31:000".

Adding id to the order by resolves the issue by guaranteeing order
Running same query with id in order by, size 20 and offset 0
![image](https://user-images.githubusercontent.com/23557307/108002234-ddd7ca00-6fe6-11eb-979c-428f595e98c3.png)

Running same query with id in order by, size 20 and offset 20
![image](https://user-images.githubusercontent.com/23557307/108002273-06f85a80-6fe7-11eb-903b-ee8df1eb2540.png)

## System information

 * **Airsonic version**: *11.0.0-SNAPSHOT.20210130073922*
 * **Operating system**: *Linux (Raspbian)*
 * **Java version**: *java 11.0.9.1*
 * **Server**: *Apache Tomcat/9.0.31*
 * **Database**:*Postgres*
 * **Client**: *Postman*
 * **Language**: *English*

**Comment by randomnicode** [comment]
Thanks @ctedgar!
