### ISSUE TITLE
Downloading rules on a per podcast basis

### ISSUE THREAD

**Issue by jajpater** [airsonic-advanced/airsonic-advanced#488]
I already made this issue at https://github.com/airsonic/airsonic/issues/1857

I'd like to see an option where you can set downloading rules on a per podcast basis. Of some podcasts I listen every episode of others I only listen some if I have time. Of some podcasts I want to keep every episode, of other podcasts I only want to keep the last five. Now I'm forced to download everything and keep everything and delete the ones I don't want.

**Comment by dsiminiuk** [comment]
@jajpater Good idea!

In addition, it would be nice if you could set the local destination folder for each podcast rather than relying on the name data in the RSS xml.

This was an enhancement I asked for in Subsonic and it was never addressed.
