### ISSUE TITLE
"Random albums" menu on Dsub also shows random songs.

### ISSUE THREAD

**Issue by nonylours** [airsonic-advanced/airsonic-advanced#498]
## Problem description

Hi,
When I open the "Album List -> Random" menu on Dsub, the server returns a mix of songs and albums instead of just returning albums.
![image](https://user-images.githubusercontent.com/49427382/109454022-b1b45280-7a96-11eb-8c69-89ba773686f3.png)

I tried with another android app (Ultrasonic), same problem.
The problem only happens if the "Browse by Tags" option is unchecked in the Dsub Settings -> Servers Menu.
The problem doesn't happen with the regular Airsonic or Subsonic servers.

The log doesn't show any information except a bunch of "INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key" lines
## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20210221091539
 * **Operating system**: Windows 10 japanese.
 * **Java version**: Openjdk version 11.0.10
 * **Proxy server**: None
 * **Client**: Dsub 5.5.2R2
 * **Language**: English

Thanks.

**Comment by randomnicode** [comment]
This is strange and would only happen if some files are being classified as folders.

Does this happen to anyone else?

**Comment by nonylours** [comment]
I did a full rescan of my entire library and it solved the problem

However, during the scan it stopped scanning for new files twice and I had to "Ctrl+C" in the command window to make it continue. Maybe there are some malformed files in my library causing problems.
