### ISSUE TITLE
Podcasts aren't downloading, file contents is html with an error

### ISSUE THREAD

**Issue by llakssz** [airsonic-advanced/airsonic-advanced#502]
## Problem description

Podcasts don't download properly, probably as a result of https://github.com/airsonic-advanced/airsonic-advanced/issues/470?

Taking this feed as an example: https://anchor.fm/s/1f6ce87c/podcast/rss
When trying to download an audio file (here, I have chosen the oldest one), Airsonic creates a file with a nice, escaped filename `127163677-44100-2-30cce9877efe5.m4a`, and this is the contents:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /s/1f6ce87c/podcast/play/13414326/https:/d3ctxlq1ktw2nl.cloudfront.net/staging/2020-10-10/127163677-44100-2-30cce9877efe5.m4a</pre>
</body>
</html>
```

Before #470, the audio file downloaded fine - but the filename was messy.

### Steps to reproduce

Add the feed, download the a file. Check the file contents.

## System information

 * **Airsonic version**: Edge Release 11.0.0-SNAPSHOT.20210308063729
 * **Operating system**: FreeBSD 12.2
 * **Java version**: OpenJDK 11

**Comment by randomnicode** [comment]
Hmmmph, it most certainly is that fix, but begs the question what do we do about urls like those

Maybe we'll unsanitize them and sanitize only for the filename
