### ISSUE TITLE
Podcasts download multiple times, and have numbers appended to the end of the file name

### ISSUE THREAD

**Issue by llakssz** [airsonic-advanced/airsonic-advanced#505]
## Problem description

I'm not exactly sure under what circumstances this happens, but sometimes a podcast will download multiple times.
![image](https://user-images.githubusercontent.com/10378832/110680151-3f362780-81a6-11eb-8de3-b3f46dd8aa32.png)
![image](https://user-images.githubusercontent.com/10378832/110680260-5ecd5000-81a6-11eb-811a-9581edacdc72.png)

I've noticed this before and [seen other people encounter it](https://github.com/airsonic/airsonic/issues/1733), and have a feeling it may be a little bit difficult to diagnose.
Whatever information that can help, I'm happy to work with you to resolve it.

One way to fix this would be to check if the file already exists before trying to write. (Although, something similar must already be implemented, otherwise the filename wouldn't have an incrementing number appended to it, right?)

If, when attempting a download and Airsonic sees that the file already exists and uses that version instead, this would be useful and let us 'import' files already downloaded elsewhere by simply putting them where they need to go.

### Steps to reproduce

Not sure what caused it... happy to keep testing if you have some ideas.

1. Added a feed (fresh Airsonic instance, nothing else in the database)
2. Let the feed download automatically
4. Duplicate files get created/file downloads multiple times

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20210309214438
 * **Operating system**: FreeBSD 12.2
 * **Java version**: OpenJDK 11

**Comment by llakssz** [comment]
P.S. Thanks for the podcast filename fix, works great!

**Comment by rpi-maker** [comment]
I noticed the same issue.  A Podcast episode would download completely, and on the next automatic update it would download the same episode with an appended a sequential number (i.e. 0,1,2,3,4,...) at the end of the filename.

Can someone please look at the code to see if the podcast episode is already downloaded and complete (probably need to compare downloaded podcast file size to source file size), then skip otherwise try podcast episode download again?



Version | 11.0.0-SNAPSHOT.20210612032051 – June 11, 2021 at 10:20:51 PM CDT
-- | --
Server | Apache Tomcat/9.0.46, java 11.0.11, Linux (136.9 MB / 158.4 MB)


```
 lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-post-Raspbian-1deb10u1)
OpenJDK Server VM (build 11.0.11+9-post-Raspbian-1deb10u1, mixed mode)
```

**Related Issues**
Same podcast episode is downloaded infinitely #1607
https://github.com/airsonic/airsonic/issues/1607

Re-downloading completed podcast episodes #1733
https://github.com/airsonic/airsonic/issues/1733

**Comment by Yetangitu** [comment]
I'm looking into updating the podcast/netcast section in AA, one of my goals is to get rid of duplicate episodes. One of the problems I've found is that the code currently tries to detect duplicate episodes based on the URL. seemingly assuming it to be immutable for a given episode. Unfortunately this is not the case as can be seen by the following example (from which I removed the episodes which did not have duplicates):

```
airsonic=# select url from podcast_episode where channel_id=113 order by url;
                                url                                
-------------------------------------------------------------------
 https://traffic.megaphone.fm/WWO1215628126.mp3?updated=1623793590
 https://traffic.megaphone.fm/WWO1215628126.mp3?updated=1623870514

 https://traffic.megaphone.fm/WWO3553165684.mp3?updated=1623793177
 https://traffic.megaphone.fm/WWO3553165684.mp3?updated=1623870569

 https://traffic.megaphone.fm/WWO3562546263.mp3?updated=1623795592
 https://traffic.megaphone.fm/WWO3562546263.mp3?updated=1623870463

 https://traffic.megaphone.fm/WWO4432538469.mp3?updated=1623792193
 https://traffic.megaphone.fm/WWO4432538469.mp3?updated=1623870573

 https://traffic.megaphone.fm/WWO4894061157.mp3?updated=1623795570
 https://traffic.megaphone.fm/WWO4894061157.mp3?updated=1623870497

 https://traffic.megaphone.fm/WWO6871632087.mp3?updated=1623796029
 https://traffic.megaphone.fm/WWO6871632087.mp3?updated=1623870545

 https://traffic.megaphone.fm/WWO8355157724.mp3?updated=1623792173
 https://traffic.megaphone.fm/WWO8355157724.mp3?updated=1623870583
```
As can be seen the duplicated episodes have URLs which differ only in the "updated" attribute, the downloaded files are identical:

```
$ md5sum WWO3562546263.mp3\?updated\=1623*
1888ac0daf5349e53a892f6b06be74a4  WWO3562546263.mp3?updated=1623795592
1888ac0daf5349e53a892f6b06be74a4  WWO3562546263.mp3?updated=1623870463%0A%0A
```

The canonical way to avoid downloading duplicates is to check the GUID attribute:
> The episode’s globally unique identifier (GUID) If you uploaded subscriber audio in Apple Podcasts Connect and need to link it to an episode in your RSS feed, you can use the Apple Podcasts Episode ID in the GUID tag. Learn more about how to set up your show for a subscription.
> 
> It is very important that each episode have a unique GUID and that it never changes, even if an episode’s metadata, like title or enclosure URL, do change.
> 
> Globally unique identifiers (GUID) are case-sensitive strings. If a GUID is not provided, an episode’s enclosure URL will be used instead. If a GUID is not provided, make sure that an episode’s enclosure URL is unique and never changes.
> 
> _Failing to comply with these guidelines may result in duplicate episodes being shown to listeners,_ inaccurate data in Analytics, and can cause issues with your podcasts’s listing and chart placement in Apple Podcasts.

(https://help.apple.com/itc/podcasts_connect/#/itcb54353390)

It is clear that URLs can not be assumed to be immutable so the first step would be to add a check for a GUID. This necessitates a change to the database schema which currently lacks a GUID field.

An extra check for the combination of a title and publish date could be used to avoid duplicates, this can be done without updating the schema.

More later.
