### ISSUE TITLE
java version problem

### ISSUE THREAD

**Issue by hs6666** [airsonic-advanced/airsonic-advanced#509]
## Problem description

Hello, trying to run on a pi3 (latest raspbian version) but getting the following java error ....

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/airsonic/player/Application has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
-bash: syntax error near unexpected token `('

running "java -version" gives....

openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-1~deb9u1-b01)
OpenJDK Client VM (build 25.275-b01, mixed mode)

Above happens when trying to run latest war file ....  "https://github.com/airsonic-advanced/airsonic-advanced/releases/tag/11.0.0-SNAPSHOT.20210309214438" using "java -jar airsonica.war" in terminal  

Thanks

**Comment by afprusin** [comment]
@hs6666 The error indicates that your war was compiled with a newer version of Java (11, I think), but you are attempting to run the war with an older version (1.8).  Consider installing a newer Java version and making sure it's set as your default JRE, or re-compiling the war with Java 1.8

**Comment by randomnicode** [comment]
Install a more recent Java. The Java requirements are listed on the [Usage portion of the README](https://github.com/airsonic-advanced/airsonic-advanced#usage)

If you want to use an older version of Java (like 1.8), you need to use an older version of the program (10.6.2).
For more recent versions/edge snapshots, please use at least Java 11

**Comment by hs6666** [comment]
will this work on my Pi, or is there a quick apt install command which will automatically install the latest version so keeping it upto date later after running apt update?

thanks

**Comment by dsiminiuk** [comment]
If AA is all you need Java for then you only need one. Uninstall the old, install the new.

sudo apt install -y openjdk-11-jdk

**Comment by randomnicode** [comment]
may we close this issue?

**Comment by hs6666** [comment]
> 
> 
> If AA is all you need Java for then you only need one. Uninstall the old, install the new.
> 
> sudo apt install -y openjdk-11-jdk

hi, currently I have following java installed...

# java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) Client VM (build 25.201-b09, mixed mode)

which must be used by subsonic (which I have to constantly renstall because of database corruption - have a large music/podcast database)), so to confirm....

1) remove this java version .... command would be?

2) run sudo apt install -y openjdk-11-jdk

3) remove subsobic and install airsonic-advanced - or is there a set of commands which will install airsonic-advanced using my eisting subsonic database, then remove the subsonic service from starting but leave it installed?

?

thanks

**Comment by randomnicode** [comment]
I think when you install java 11, it automatically points everything to wherever 11 was installed

1. Run sudo apt install -y openjdk-11-jdk
2. Open console and run java -version again to check the version pointed to now
3. Stop the old subsonic war if it is running, and run the new airsonic war again. If you want to use the same database (airsonic will upgrade it), then point the airsonic data directory to the subsonic data directory.

**Comment by randomnicode** [comment]
may we close this issue?
