### ISSUE TITLE
Example of an airsonic-advance instance fully running in docker-compose with external database 

### ISSUE THREAD

**Issue by qwertyAcabtino** [airsonic-advanced/airsonic-advanced#510]
## Problem description

**Not a problem**

Just dropping here a repo with an example of a docker-compose.yml & configuration files in order to run a full airsonic-advance instance with external database.

Hope this can be useful for internal documentation, examples or other peers trying to / thinking of doing this very same thing themselves.

Link: https://github.com/qwertyAcabtino/airsonic-advance-docker-compose-external-db

**Comment by randomnicode** [comment]
Hey some of those property names in the docker-compose file posted are old or no longer in use:
      - DatabaseConfigType=embed --> not used
      - DatabaseConfigEmbedDriver=org.mariadb.jdbc.Driver --> generally not needed (configured via URL), but migrated to spring.datasource.driver-class-name
      - DatabaseConfigEmbedUrl=jdbc:mariadb://db:3306/airsonic --> Migrated to spring.datasource.url
      - DatabaseConfigEmbedUsername=XXX --> Migrated to spring.datasource.username
      - DatabaseConfigEmbedPassword=XXX  --> Migrated to spring.datasource.password
      - AIRSONIC_DIR=/opt/airsonic --> not strictly necessary (defaults to /var/airsonic)

Thank you for the template though!

**Comment by qwertyAcabtino** [comment]
I'll update the template then. To be honest, the properties came from an old issue of someone migrating to an external db as well, but, did not see anywhere in the docs (my bad?) the reference to the new properties...

PS: is any action on you side desired with this data or shall the issue be closed?

**Comment by randomnicode** [comment]
No action needed on our part, you can close the issue and someone searching for something similar can just come across it and use the template.
