### ISSUE TITLE
Unable to get Sonos working with Airsonic

### ISSUE THREAD

**Issue by Ramses26** [airsonic-advanced/airsonic-advanced#519]
## Problem description
I'm running Airsonic-advnaced on unraid Docker, but unable to get Sonos to work with Airsonic. I manually added AirSonic to Sonos, but and used multi-user, Sonos sees Airsonic but tells me there was a problem getting started. Please check your network connection. The other thing I noticed in AirSonic, is I don't have options to enable single or multi user, in the settings the only option I have is Enable sonos Music service, and the Music Service name, and nothing else

 * **Airsonic version**: *the version listed on the About page*
 * 

10.6.0.20200424173747 – April 24, 2020 1:37:47 PM EDT
--

 * **Operating system**: *the operating system you're running Airsonic on.
Docker Unraid

Thanks,

**Comment by randomnicode** [comment]
Hi, seems you're using an old version of Airsonic-advanced (at least a year old). Think sonos support was officially added in 11.x series. You seem to be using the 10.6.x series.

So please use a more recent version of Airsonic-advanced. Use the airsonicadvanced/airsonic-advanced:latest tag to download the latest docker images from Docker Hub.

Read the Sonos [instructions](https://github.com/airsonic-advanced/airsonic-advanced/blob/master/SONOS.md)

**Comment by Ramses26** [comment]
Yup you're right, Binhex docker is not running the latest, changed the repository and everything is working correctly. Thank you
