### ISSUE TITLE
"Play top song" button missing

### ISSUE THREAD

**Issue by Jisagi** [airsonic-advanced/airsonic-advanced#531]
## Problem description

The "Play top songs" does not appear imediatly, but only after toggling list mode on (and off again).

### Steps to reproduce

1. Open any artist the queried database/website has data to show for
2. Check the box with artist information
3. The "Start Radio" button appears just fine, but the "Play top song" does not

I did find a temporary "fix" for: Change the view to list mode and the button appear instantly and even persists to be there after you change it back to initial mode. Starting with list mode does not help either, you ahve to switch it once to the other one respectivly for the button to appear.

## System information

 * **Airsonic version**: latest master c51c99ac19552b7d75d434aedea5edd78b76f27b
 * **Operating system**: Running inside a docker on debian 10
 * **Java version**:  The one the docker image brings with it
 * **Proxy server**: apache2 (v2.4.38) with https
 * **Client**: Chrome 90
 * **Language**: English

**Comment by johann1525** [comment]
jup. same thing happens for me. Thank you for the workaround! 👍  

It would be also cool to have a table below the info box with lets say the 20 top most titles. It would help seeing the info without requiring to play them. Convenient to be able to click one of them directly when searching for something.
