### ISSUE TITLE
Question about Docker: integrate nano editor.

### ISSUE THREAD

**Issue by The-Exterminator** [airsonic-advanced/airsonic-advanced#532]
can we install nano in the docker images like ??

FROM debian
RUN apt update -y && apt install nano

**Comment by The-Exterminator** [comment]
i have to do this, to get it to work :
curl http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb --output libseccomp2_2.5.1-1_armhf.deb
sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb

**Comment by uSlackr** [comment]
Curious as to why you want nano in the container?

**Comment by The-Exterminator** [comment]
I have to write in the airsonic.pro file.
