### ISSUE TITLE
CONTEXT_PATH ignored @ 11.0.0-SNAPSHOT.20210504201650

### ISSUE THREAD

**Issue by 3Dscrewer** [airsonic-advanced/airsonic-advanced#535]
Edge Release 11.0.0-SNAPSHOT.20210504201650

Ubuntu Server 20.xx LTS

Stand-alone Nginx Reverse Proxy

Stand-alone configuration as original Airsonic documentation.

CONTEXT_PATH=/airsonic 
/etc/default/airsonic is ignored 

Even forwarding to the subfolder doesn’t work for me, getting Bad Gateway.
Only this silly domain:port/airsonic is working.

Switching back to latest 10.xxx everything is fine again, using context path or forwarding to subfolder.

**Comment by jobenvil** [comment]
Please have a look here https://github.com/airsonic-advanced/airsonic-advanced/issues/88#issuecomment-588423532

and here https://github.com/airsonic-advanced/airsonic-advanced/issues/145

**Comment by 3Dscrewer** [comment]
@jobenvil 
Thanks for the hint, I guess 
server.servlet.contextPath=/airsonic
will do the job.
The other Nginx configuration I have already found.

**Comment by randomnicode** [comment]
may we close this issue if the resolution has been found?

**Comment by 3Dscrewer** [comment]
I have no time to check that out, I was going back to latest 10 Snapshot, but I guess it should work.
If not someone may reopen…
