### ISSUE TITLE
Can't load any media from Android apps (DSub, Ultrasonic)

### ISSUE THREAD

**Issue by KevinThomas0** [airsonic-advanced/airsonic-advanced#538]
## Problem description
After successfully connecting to my server from DSub or Ultrasonic, I don't see any of my songs at all.

What I want to happen: After connecting to my server on DSub (test connection passes), I can refresh my library and see all my songs.

What happens: I connect to my server on DSub, navigate to my library, and no data shows up (DSub shows the message "No data".

### Steps to reproduce
1. Run `airsonic-advanced 11.0.0-SNAPSHOT.20210610174915` using the airsonic.war file and openjdk11.
2. Setup behind an nginx proxy
3. Create a normal user, setup music folders, add decodeable credential (AES)
4. Use DSub or Ultrasonic to connect to the server using the credential, verify the the connection works by tapping "test connection"
5. Observe that no music is showing up in the app's library

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20210610174915
 * **Operating system**: Alpine Linux v3.13 x86_64
 * **Java version**: 11.0.9
 * **Proxy server**: nginx/1.18.0
 * **Client**: DSub 5.5.2, Ultrasonic 2.21.0
 * **Language**: English

## Additional notes

* I get no airsonic logs at all when attempting to load the music on DSub.
* The relevant nginx logs I get look like this (this is when I try and load the different album lists in DSub, all of them return "No data" inside the app):
```
162.158.146.176 - kevin [10/Jun/2021:21:42:22 -0700] "GET /rest/getPlaylists.view?u=kevin&s=rjln1vba3gtumt34tt2v0mpnl1&t=41725c2d6b2b3b662b874d68a4ce722b&v=1.2.0&c=DSub HTTP/1.1" 200 161 "-" "DSub"
162.158.146.176 - kevin [10/Jun/2021:21:42:23 -0700] "GET /rest/getRandomSongs.view?u=kevin&s=c82lnnrl0jitdl8gmet183d5gq&t=6a873df8134198a67944cfc7979babf1&v=1.2.0&c=DSub&size=50 HTTP/1.1" 200 163 "-" "DSub"
162.158.146.176 - kevin [10/Jun/2021:21:45:58 -0700] "GET /rest/getRandomSongs.view?u=kevin&s=c82lnnrl0jitdl8gmet183d5gq&t=6a873df8134198a67944cfc7979babf1&v=1.2.0&c=DSub&size=50 HTTP/1.1" 200 163 "-" "DSub"
162.158.146.176 - kevin [10/Jun/2021:21:46:00 -0700] "GET /rest/getAlbumList2.view?u=kevin&s=c82lnnrl0jitdl8gmet183d5gq&t=6a873df8134198a67944cfc7979babf1&v=1.2.0&c=DSub&type=newest&size=20&offset=0 HTTP/1.1" 200 162 "-" "DSub"
162.158.146.176 - kevin [10/Jun/2021:21:46:02 -0700] "GET /rest/getAlbumList2.view?u=kevin&s=c82lnnrl0jitdl8gmet183d5gq&t=6a873df8134198a67944cfc7979babf1&v=1.2.0&c=DSub&type=newest&size=20&offset=0 HTTP/1.1" 200 162 "-" "DSub"
162.158.146.176 - kevin [10/Jun/2021:21:46:08 -0700] "GET /rest/getAlbumList2.view?u=kevin&s=c82lnnrl0jitdl8gmet183d5gq&t=6a873df8134198a67944cfc7979babf1&v=1.2.0&c=DSub&type=random&size=20&offset=0 HTTP/1.1" 200 162 "-" "DSub"
162.158.146.176 - kevin [10/Jun/2021:21:46:09 -0700] "GET /rest/getAlbumList2.view?u=kevin&s=c82lnnrl0jitdl8gmet183d5gq&t=6a873df8134198a67944cfc7979babf1&v=1.2.0&c=DSub&type=alphabeticalByName&size=20&offset=0 HTTP/1.1" 200 162 "-" "DSub"
162.158.146.176 - kevin [10/Jun/2021:21:46:11 -0700] "GET /rest/getStarred2.view?u=kevin&s=c82lnnrl0jitdl8gmet183d5gq&t=6a873df8134198a67944cfc7979babf1&v=1.2.0&c=DSub HTTP/1.1" 200 160 "-" "DSub"
```
* I am able to play music using my user on the web interface
* I have tried creating both AES and plain text credentials to use with DSub, it seemed to have no effect
* The same behavior happened when I tried to access my server directly by its local IP on my local network
* On both DSub and Ultrasonic, the "test connection" button returns successful, and if I put in the wrong password it fails, so the apps seem to recognize that I'm sending the correct credentials
* Here is the relevant part of my nginx config:
```
server {
    ...
    location / {
	proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "Upgrade";
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host  $http_host;
        proxy_set_header Host              $http_host;
        proxy_set_header Origin            '';                      # edited+added 25.01.2021 due to #453 may help here
        proxy_max_temp_file_size           0;
        proxy_pass                         http://127.0.0.1:8080;
        proxy_redirect                     http:// https://;
        proxy_buffering off;
        proxy_request_buffering off;

        client_max_body_size 0;

        access_log      /var/log/nginx/airsonic_access.log;
        error_log       /var/log/nginx/airsonic_error.log;
    }
}
```

Any help would be appreciated, thank you!

**Comment by KevinThomas0** [comment]
Hmm I opened the apps today and everything is there now? Maybe I had to wait for something to sync? Honestly not sure, I guess I can close this lol.

**Comment by czadikem** [comment]
I had the same issue all I did was go to settings and click scan media folders now.
