### ISSUE TITLE
Is it possible to build ffmpeg with fdk-aac support?

### ISSUE THREAD

**Issue by bvdgrift** [airsonic-advanced/airsonic-advanced#549]
## Problem description

It's not a problem, more a feature request.

### Steps to reproduce

N/A

## System information

N/A

## Additional notes

For the iPhone users it would be nice to be able to convert to aac with a high quality encoder like fdk_aac.

**Comment by randomnicode** [comment]
airsonic-advanced merely uses ffmpeg. Whatever ffmpeg you'd like to provide, with whatever options, it will use.
In the Docker image, the default ffmpeg is installed from ppa:savoury1/ffmpeg4 with whatever options come with it. fdk_aac may have licensing issues (non GPL) that restrict it from being enabled on a public repo.

You can obviously install and provide your own encoder/decoder (fdk_aac) in your own docker container (or machine) and change the preferences in your airsonic to use that encoder for encoding aac files
