### ISSUE TITLE
Fails to start when file called 'config' is present in airsonichome

### ISSUE THREAD

**Issue by ghenry22** [airsonic-advanced/airsonic-advanced#564]
## Problem description

I am bundling airsonic advanced into a package for synolgoy NAS devices.  This is all working well with one problem.  The synology package format requires me to have a file called config in the same folder as airsonic-advanced.  This file is used by the synology system to generate some elements in the UI.

If this file is present then I receive the error in the attachment when trying to start airsonic-advanced.  If I remove the file airsonic starts and runs fine but then I am missing elements in the Synology UI.

This was not an issue with vanilla airsonic and I think it's related to updated spring framework which by default now looks in /config for application.yaml files to load. In my case /config is a file though so it blows up.

As airsonic-advanced does not use this location/config file is it possible to disable the default behaviour that tries to check for config?

### Steps to reproduce

Create a file called config in airsonichome
start airsonic
watch the log for the error as in the attachment

## System information

Edge Release 11.0.0-SNAPSHOT.20210702161646
Linux (synology)
Java 11

![2021-07-08 10_00_01-192 168 86 98 (admin)](https://user-images.githubusercontent.com/7463213/124851905-fcf6e880-dfd5-11eb-82c3-7f3c2842d960.jpg)
![2021-07-08 10_00_12-192 168 86 98 (admin)](https://user-images.githubusercontent.com/7463213/124851906-fec0ac00-dfd5-11eb-8819-c09ce8141261.jpg)

**Comment by randomnicode** [comment]
There are a few considerations here regarding what is going on. The list of folders candidates are:
- the current folder
- the location of the war folder
- the airsonic home folder

[Spring documentation](https://docs.spring.io/spring-boot/docs/2.5.2/reference/html/features.html#features.external-config) specifies that it only looks at *current* folder when looking for the config folder. Even so, it can be overridden.

You have two possible solutions:
1. Separate the three folders. Effectively your folder structure can be something like the following, and in your starting sh command make sure you're in the airsonic_war folder and not the root folder when issuing your "java -jar" command (also specify airsonic.home as airsonic_home)
  - root
    - config
    - airsonic_home
      - db
      - transcode
      - index
      - other files...
    - airsonic_war
      - airsonic.war
2. Override config location via the spring boot parameter in your starting command:
  - `java -D... -jar airsonic.war --spring.config.location=optional:classpath:/;optional:classpath:/config/,optional:file:./`
  - [Default locations seem to be: `optional:classpath:/;optional:classpath:/config/,optional:file:./;optional:file:./config/;optional:file:./config/*/` Note we took out the config file locations in the command above]

**Comment by randomnicode** [comment]
may we close this issue now if it has been addressed?

**Comment by ghenry22** [comment]
Yep can close this, I will look at re-structuring the package deployment. Thanks for the suggestions, that is pretty much the conclusion that I came to when I worked out what was going on here.
