### ISSUE TITLE
Development Support / Packaging

### ISSUE THREAD

**Issue by ghenry22** [airsonic-advanced/airsonic-advanced#569]
@randomnicode apologies for spamming the issues here but I wanted to get in touch and see if I could help contribute to Airsonic-Advanced and to discuss a few ideas.

I'm the developer for the subsonic client substreamer and I maintain the synology build for the original subsonic and recently created packaged synology builds for airsonic and airsonic-advanced.  I'd like to look at setting up builds for installers for different platforms to make adoption easier / less technical and to discuss some potential extensions to the REST API to enable features in the web UI to be added to a client application so airsonic-advanced could be fully controlled from the app.

You can get me at ghenry22.apps@gmail.com

**Comment by randomnicode** [comment]
All contributions welcome! It's a GPL fork and everything for the betterment of community!

**Comment by ghenry22** [comment]
Thanks for getting in touch by email, I'll close this.
