### ISSUE TITLE
Directory names containing colon (":") character are not displayed properly

### ISSUE THREAD

**Issue by fkrivsky** [airsonic-advanced/airsonic-advanced#572]
## Problem description

Directory names containing colon are mangled, e.g.:
![image](https://user-images.githubusercontent.com/68921465/125995560-b9926b12-790d-4b3a-b0dd-c94ed0f90e0d.png)

### Steps to reproduce

1. Have directory with colon character (":") in the name 
2. View it in the browse mode

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20210716160405
 * **Operating system**: Docker CE 20.10.7 @ Ubuntu 20.04
 * **Java version**: Apache Tomcat/9.0.46, java 14.0.2, Linux (217.3 MB / 256.0 MB)
 * **Proxy server**: None
 * **Client**: Vivaldi 4.0.2312.38 (Stable channel) (64-bit)
 * **Language**: English

**Comment by randomnicode** [comment]
Unable to reproduce this

**Comment by fkrivsky** [comment]
So maybe it's caused by SMB? 
My music dir is mounted from a NAS via SMB.
