### ISSUE TITLE
Stop target=_parent?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [airsonic-advanced/airsonic-advanced#573]
I'm using the latest version as of today, in Docker, and from within an iframe (Organizr); the frustrating thing is that Airsonic always breaks out of Orgainzr's iframe, I haven't looked but probably by using something like `target=_parent`.

I want to keep AS within my Organizr frame, Can there be an option added to prevent AS from behaving this way?

**Comment by randomnicode** [comment]
There doesn't seem to be any target="_parent" anywhere in the codebase. If you find any instances of it, could you point them out?

Mostly when targets are used they are:
- _blank: for opening in a new page/tab
- _top: for logout
- main: for opening in the named "main" iframe

There don't seem to be any other instances of target
