### ISSUE TITLE
11.0.0-SNAPSHOT.20210803095157 breaks playback

### ISSUE THREAD

**Issue by hboetes** [airsonic-advanced/airsonic-advanced#583]
11.0.0-SNAPSHOT.20210803075200 still works, but 11.0.0-SNAPSHOT.20210803095157 breaks playback.

**Comment by randomnicode** [comment]
on which browser and what exactly about the playback is broken?

**Comment by Cytomax55** [comment]
I can no long play songs on airsonic using chrome when i updated to the following 2 snapshots
I can browse the server

11.0.0-SNAPSHOT.20210803095157

11.0.0-SNAPSHOT.20210805143941 


It still works great on firefox

**Comment by randomnicode** [comment]
Are there any errors in Chrome developer console?

**Comment by Cytomax55** [comment]
I found this in developer console... but i dont really know what im doing i hope this helps

` jQuery.Deferred exception: getJQueryUiDialogPlaylistSize is not defined ReferenceError: getJQueryUiDialogPlaylistSize is not defined
    at Object.init (https://airsonic.supersecretdomain.com/index:703:30)
    at HTMLDocument.<anonymous> (https://airsonic.supersecretdomain.com/index:1475:39)
    at e (https://airsonic.supersecretdomain.com/script/jquery-3.5.0.min.js:2:30005)
    at t (https://airsonic.supersecretdomain.com/script/jquery-3.5.0.min.js:2:30307) undefined
S.Deferred.exceptionHook @ jquery-3.5.0.min.js:2
t @ jquery-3.5.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.5.0.min.js:2
c @ jquery-3.5.0.min.js:2
fireWith @ jquery-3.5.0.min.js:2
fire @ jquery-3.5.0.min.js:2
c @ jquery-3.5.0.min.js:2
fireWith @ jquery-3.5.0.min.js:2
ready @ jquery-3.5.0.min.js:2
B @ jquery-3.5.0.min.js:2
jquery-3.5.0.min.js:2 Uncaught ReferenceError: getJQueryUiDialogPlaylistSize is not defined
    at Object.init (index:703)
    at HTMLDocument.<anonymous> (index:1475)
    at e (jquery-3.5.0.min.js:2)
    at t (jquery-3.5.0.min.js:2)
init @ index:703
(anonymous) @ index:1475
e @ jquery-3.5.0.min.js:2
t @ jquery-3.5.0.min.js:2
setTimeout (async)
S.readyException @ jquery-3.5.0.min.js:2
(anonymous) @ jquery-3.5.0.min.js:2
e @ jquery-3.5.0.min.js:2
t @ jquery-3.5.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.5.0.min.js:2
c @ jquery-3.5.0.min.js:2
fireWith @ jquery-3.5.0.min.js:2
fire @ jquery-3.5.0.min.js:2
c @ jquery-3.5.0.min.js:2
fireWith @ jquery-3.5.0.min.js:2
t @ jquery-3.5.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.5.0.min.js:2
c @ jquery-3.5.0.min.js:2
fireWith @ jquery-3.5.0.min.js:2
fire @ jquery-3.5.0.min.js:2
c @ jquery-3.5.0.min.js:2
fireWith @ jquery-3.5.0.min.js:2
ready @ jquery-3.5.0.min.js:2
B @ jquery-3.5.0.min.js:2
main.view?id=2367:302 Uncaught ReferenceError: getJQueryUiDialogPlaylistSize is not defined
    at init (main.view?id=2367:302)
    at onload (main.view?id=2367:1084)`

**Comment by dsiminiuk** [comment]
I'm running 11.0.0-SNAPSHOT.20210803095157 and playing works in Vivaldi 4.1.2369.11 (Stable channel). Chromium derivative.

**Comment by randomnicode** [comment]
this helps a lot, but is a weird error, considering this function has been defined.

Perhaps your copy of utils.js is outdated? Can you try emptying and deleting everything in your chrome cache and trying again?

**Comment by randomnicode** [comment]
you may try disabling the cache in Network tab of Chrome Developer Tools (Ctrl +Shift + I) then reloading the page (then you can enable the cache on again)

**Comment by Cytomax55** [comment]
Im not home right now but will be happy to do it later today when I get
home...
Let me know if there is anything else you need from me

**Comment by hboetes** [comment]
I just discovered that the cause of my problem was an anti Java-Script plugin which I just installed. My bad.
