### ISSUE TITLE
Lost admin password -- shame on me

### ISSUE THREAD

**Issue by imightbelosthere** [airsonic-advanced/airsonic-advanced#590]
## Problem description

Lost admin password (oops... I know....)

### Steps to reproduce
1. Change admin password
2. Remove the old admin/admin credential
3. Be dumb and forget the admin password... No recovery email set either... Genius!

## System information

 * **Airsonic version**: docker latest
 * **Operating system**: Docker
 * **Java version**: 14.0.2+12
 * **Proxy server**: None

## Additional notes

I have the EncryptionKeyPassword and KeySalt + the password stored in the form of a hash on the airsonic.script... Is there a way to calculate or "dehash" the password having these values?
Thanks

**Comment by dsiminiuk** [comment]
Not to beat a dead horse, but there is a "forgot password" function on the login page for exactly this. If you never set an email for your admin user (all users actually) or never set an SMTP server for email delivery for this function then, now you know why it is important.

The only thing I can suggest is if you have another user (any) that you know the password for, you might be able to copy the hashed password from that user to the admin user with an update statement directly in the db.

**Comment by dsiminiuk** [comment]
Having said that, I am not able to connect to my own database. I had done it before on an older iteration (perhaps not the Advanced build) but hsqldb.jar is not found on my machine so I need to do some reading to get back to being able to do updates.

**Comment by imightbelosthere** [comment]
Yeah bud I've messed up bad... I've worked this one around by deploying another instance of the docker image on a "test" docker server, and created a new credential with admin as password and replaced the text on the script file... I'm back in...

Guess what I've done next? Setup the password again, stored it in my key password safe thingy and configured an email! All is good with the world again :)

**Comment by monksy** [comment]
If you have another account that you have the password. 
Go into the database.

Update the user table for the user and add the "ADMIN" role to the roles field. (update).

Restart the app, and log into that account, go to users and reset the admin password there.
