### ISSUE TITLE
Credentials Settings error 404 with Docker

### ISSUE THREAD

**Issue by lifehackerhansol** [airsonic-advanced/airsonic-advanced#598]
## Problem description

The "add credentials" section has a hover info saying to delete old passwords go to Credentials Settings page. Clicking on said page returns a 404 error. 

I am unable to test non-Docker at this time. 

### Steps to reproduce

1. Get latest Docker image
2. Map `/airsonic/data` -> `/mnt/user/appdata/airsonicadvanced` 
  - this is how all other UnRAID Docker images does it, so I figured I'd keep the same structure. I highly doubt this would cause anything to go wrong
3. Login with default admin and password
4. Go to settings, try to make a new password, click on Credentials Settings link as it says you need to go there
5. **Whitelabel Error Page** saying error 404 not found

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20210815234208 (from About page, latest Docker image at time of writing)
 * **Operating system**: UnRAID 6.9.2
 * **Java version**: 14.0.2 (from About page, latest Docker image at time of writing)
 * **Proxy server**: None
 * **Client**: Edge 92.0.902.73
 * **Language**: English

**Comment by randomnicode** [comment]
you mean /var/airsonic instead of /airsonic/data?

also can't reproduce

**Comment by lifehackerhansol** [comment]
Am I reading the README wrong? I thought `/airsonic/data` within the container was supposed to bind to `/var/airsonic` in host?

I'll try the new config quick. Still makes me wonder what's up

**Comment by lifehackerhansol** [comment]
I should note. This is what comes up. 
![image](https://user-images.githubusercontent.com/37358975/130121669-d311d006-228c-4a6f-a5c9-4f1592ab5447.png)

All I'm doing is clicking credentials settings in this section here: 
![image](https://user-images.githubusercontent.com/37358975/130121765-6ba83376-cc68-4e81-9726-a71cbc6811d3.png)

**Comment by lifehackerhansol** [comment]
It seems I'm indeed wrong with the bind path. That however didn't solve the 404 error in the credentials settings tab (which is expected, it should have nothing to do with that).

For the hell of it, I decided to run it on Internet Explorer, even downloaded Firefox for the hell of it. Both produce the same 404 error.

**Comment by lifehackerhansol** [comment]
I pulled the latest image today. That specific notice in the above image still throws a 404 error.

However, I did find where the credentials tab was (I see I'm kind of blind lol). That link should still be fixed, though, but I have no idea how it'd be done.
