### ISSUE TITLE
Player buttons stacked vertically in Firefox

### ISSUE THREAD

**Issue by justin-mi** [airsonic-advanced/airsonic-advanced#609]
## Problem description

*In Firefox, the buttons on the player bar are stacked vertically, causing the player bar to be taller than it should be.*

### Steps to reproduce

*Airsonic-advanced was installed over airsonic.  Player bar in Firefox has its buttons stacked vertically instead of horizontally.  Player bar appears fine in Chromium.*

1. *Log into web interface in Firefox browser.*
2. *Player bar is instantly viewable with its buttons stacked vertically.*

## System information

 * **Airsonic version**: *11.0.0-SNAPSHOT.20210825033015 – August 24, 2021 at 8:30:15 PM PDT*
 * **Operating system**: *Debian GNU/Linux 10 (buster) x86_64*
 * **Java version**: *Java 11*
 * **Proxy server**: *Caddy*
 * **Client**: *Firefox 91.0.2*
 * **Language**: *English*

## Additional notes

*Player bar is ok in Chromium.*
screenshot off issue in Firefox:  https://i.imgur.com/a9ULbSe.png

**Comment by tylerhoot** [comment]
i can also verify that this is an issue with Firefox 92.0b9 (64-bit) I am hosting airsonic advanced on windows server 2019 with adoptium openjdk 11 the issue is the same and is fine in chromium or edge (chromium based)

**Comment by randomnicode** [comment]
This seems like your css style did not download fully. You should be in a row flex layout, but seems like you're not. Try and clean your browser cache, close and open a new browser. Check with the element inspector (Q) in firefox if you have to to verify.

We cannot reproduce this on firefox. It appears fine.

**Comment by patbakdev** [comment]
Same here. Clearing the cache worked for me.

**Comment by justin-mi** [comment]
Yes, we can close this.
