### ISSUE TITLE
Listenbrainz credentials: Username 'not required'

### ISSUE THREAD

**Issue by jr1234jr** [airsonic-advanced/airsonic-advanced#611]
## Problem description

Hi, I recently switched from Last.fm to Listenbrainz and I am now trying to reconfigure airsonic-advanced. My problem is that I cannot fill in my Listenbrainz Username, only password can by filled in. Scrobbling does not work for me although it seems to work according to airsonic.log. How is it possible to fill in Username as well to get scrobbling working?

<img width="486" alt="Bildschirmfoto 2021-08-31 um 13 45 43" src="https://user-images.githubusercontent.com/89846191/131496989-bfe3e6a9-d080-4313-b154-452ba489510b.png">

### Steps to reproduce

1. Settings
2. Credentials
3. Add credentials
4. App: Listenbrainz
5. Try to fill in Username

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20210822224240
 * **Operating system**: Debian 10
 * **Java version**: 11
 * **Proxy server**: Apache
 * **Client**: Safari
 * **Language**: ENG

**Comment by randomnicode** [comment]
Apologies, this is not the same as your Listenbrainz username/password.
You need a user token available from https://listenbrainz.org/profile and put that in.

**Comment by jr1234jr** [comment]
Thanks, it is working now :)
So the only issue here is that airsonic.log is misleading (it tells 'successfully registered' even if credentials are wrong).

**Comment by jesse-troy** [comment]
Sorry to resurrect this, but the previous post is correct. I see in the logs that it is successfully registered at listenbrainz, but I do not see any listens...

```


2022-03-25  12:07:52.331  INFO --- o.a.p.s.s.ListenBrainzScrobbler          :  Successfully registered now playing for song 'Skip Town' at  ListenBrainz: 2022-03-25T16:07:50.811617Z
--
2022-03-25 12:07:52.714  INFO ---  o.a.p.s.s.ListenBrainzScrobbler          : Successfully registered  submission for song 'Skip Town' at ListenBrainz:  2022-03-25T16:07:51.238336Z

```
There are no new listens in my feed on listenbrainz. This example is from right now, but I was testing this several hours ago and the activity is still not on my feed. 

How exactly am I supposed to enter my key (what field? both password fields?) and do I need to use a specific encryption option for this? Documentation?

And can we fix the log issue where it is apparently not "Successfully registered"?

**Comment by randomnicode** [comment]
> How exactly am I supposed to enter my key (what field? both password fields?) and do I need to use a specific encryption option for this? Documentation?

Read the Credentials tab of your Settings page. The documentation is there.
All third party apps/sites need to have their credentials in a decodable encryption format. Encrypted AES-GCM is a good idea.
For ListenBrainz, you don't enter your username/password, just your API key in the "password" field (the "username" section will be unselectable).
