### ISSUE TITLE
Move airsonic.log to /var/log does not work

### ISSUE THREAD

**Issue by litebito** [airsonic-advanced/airsonic-advanced#618]
## Problem description

Hi, I would like to move the airsonic.log file into the /var/log directory.
I've tried a few methods, but non of them work :

### Steps to reproduce

1. via arg via cli : 
java -Dairsonic.home=/var/airsonic -Dserver.port=4040 -Dlogging.path=/var/log -jar airsonic.war
java -Dairsonic.home=/var/airsonic -Dserver.port=4040 -Dlogging.file=/var/log/airsonic.log -jar airsonic.war

2. via application.properties file in the directory /var/airsonic/config
logging.level.org.airsonic=DEBUG
logging.file=/var/log/airsonic.log
server.port=4040

(I know it reads the properties file, because if I start with 
java -Dairsonic.home=/var/airsonic  -jar airsonic.war
it does start the app on port 4040 and sets the logging level to DEBUG)

somehow airsonic accepts any parameter, except the one for a logging location outside its home directory

## System information

 * **Airsonic version**: Version | 11.0.0-SNAPSHOT.20210908073208 – September 8, 2021 at 9:32:08 AM CEST
 * **Operating system**: CentOS 7 Linux  
 * **Java version**: Server | Apache Tomcat/9.0.48, java 16.0.1, Linux 
 * **Proxy server**: none 
 * **Client**: FF
 * **Language**: EN

**Comment by randomnicode** [comment]
Indeed, the logging file parameter actually is currently hardcoded.

Feel free to submit PRs to make it a configurable parameter? The file to start is [LoggingFileOverrideListener](https://github.com/airsonic-advanced/airsonic-advanced/blob/master/airsonic-main/src/main/java/org/airsonic/player/spring/LoggingFileOverrideListener.java)

**Comment by litebito** [comment]
@randomnicode I wish I could code it myself, but I'm not a developer

**Comment by randomnicode** [comment]
The parameter name is logging.file.name

You may add it to airsonic.properties file or -Dlogging.file.name=/var/airsonic.log

**Comment by The-Exterminator** [comment]
> 
> 
> Indeed, the logging file parameter actually is currently hardcoded.
> 
> Feel free to submit PRs to make it a configurable parameter? The file to start is [LoggingFileOverrideListener](https://github.com/airsonic-advanced/airsonic-advanced/blob/master/airsonic-main/src/main/java/org/airsonic/player/spring/LoggingFileOverrideListener.java)

Page 404, the file is not there

**Comment by randomnicode** [comment]
This issue was resolved in #643 . There is a configurable parameter now in place to specify log files and the file isn't there because it was deleted.
