### ISSUE TITLE
Tomcat 9 deployment does not work

### ISSUE THREAD

**Issue by jr1234jr** [airsonic-advanced/airsonic-advanced#622]
## Problem description

Tomcat 9 deployment of Airsonic-Advanced 11.0.0 does not work, while deploying 10.6.0 is succesful

### Steps to reproduce

sudo systemctl stop tomcat.service
sudo rm -R /var/airsonic
sudo mkdir /var/airsonic/
sudo chown -R tomcat:tomcat /var/airsonic/
sudo rm /opt/tomcat/webapps/airsonic.war
sudo rm -R /opt/tomcat/webapps/airsonic/
sudo rm -R /opt/tomcat/work/*
wget https://github.com/airsonic-advanced/airsonic-advanced/releases/download/11.0.0-SNAPSHOT.20210908073208/airsonic.war
sudo mv airsonic.war /opt/tomcat/webapps/airsonic.war
sudo chown tomcat:tomcat /opt/tomcat/webapps/airsonic.war
sudo systemctl daemon-reload
sudo systemctl start tomcat.service

## System information

 * **Airsonic version**: 11.0.0
 * **Operating system**: Debian 10
 * **Java version**: openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+7-post-Raspbian-2deb10u1)
OpenJDK Server VM (build 11.0.12+7-post-Raspbian-2deb10u1, mixed mode)
 * **Proxy server**: None

## Additional notes
In catalina.out one can see that tomcat is trying to deploy in a loop:
{...}
17-Sep-2021 11:03:19.414 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
17-Sep-2021 11:03:19.416 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
17-Sep-2021 11:03:19.417 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms512M
17-Sep-2021 11:03:19.418 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx1024M
17-Sep-2021 11:03:19.419 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseParallelGC
17-Sep-2021 11:03:19.420 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
17-Sep-2021 11:03:19.421 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/opt/tomcat
17-Sep-2021 11:03:19.422 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/opt/tomcat
17-Sep-2021 11:03:19.423 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/opt/tomcat/temp
17-Sep-2021 11:03:19.434 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib/arm-linux-gnueabihf/jni:/lib/arm-linux-gnueabihf:/usr/lib/arm-linux-gnueabihf:/usr/lib/jni:/lib:/usr/lib]
17-Sep-2021 11:03:22.083 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
17-Sep-2021 11:03:22.319 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [4454] milliseconds
17-Sep-2021 11:03:22.848 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
17-Sep-2021 11:03:22.850 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.53]
17-Sep-2021 11:03:22.994 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/opt/tomcat/webapps/airsonic.war]
17-Sep-2021 11:03:53.301 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
           _                       _          
     /\   (_)                     (_)         
    /  \   _ _ __  ___  ___  _ __  _  ___     
   / /\ \ | | '__|/ __|/ _ \| '_ \| |/ __|    
  / ____ \| | |   \__ \ (_) | | | | | (__     
 /_/    \_\_|_|   |___/\___/|_| |_|_|\___|    
                                               
                        11.0.0-SNAPSHOT

2021-09-17 11:04:10.064  INFO --- org.airsonic.player.Application          : Starting Application v11.0.0-SNAPSHOT using Java 11.0.12 on max2play with PID 12933 (/opt/tomcat/webapps/airsonic/WEB-INF/classes started by tomcat in /)
2021-09-17 11:04:10.084  INFO --- org.airsonic.player.Application          : No active profile set, falling back to default profiles: default
2021-09-17 11:04:32.095  INFO --- l.l.StandardLockService                  : Successfully acquired change log lock
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
17-Sep-2021 11:05:18.297 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.53
17-Sep-2021 11:05:18.317 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 6 2021 19:09:00 UTC
17-Sep-2021 11:05:18.318 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.53.0
17-Sep-2021 11:05:18.320 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
17-Sep-2021 11:05:18.320 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.4.51-v7+
17-Sep-2021 11:05:18.321 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          arm
17-Sep-2021 11:05:18.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-11-openjdk-armhf
17-Sep-2021 11:05:18.323 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.12+7-post-Raspbian-2deb10u1
17-Sep-2021 11:05:18.324 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Raspbian
17-Sep-2021 11:05:18.325 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /opt/tomcat
17-Sep-2021 11:05:18.327 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /opt/tomcat
17-Sep-2021 11:05:18.437 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
17-Sep-2021 11:05:18.438 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
17-Sep-2021 11:05:18.446 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
17-Sep-2021 11:05:18.447 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
17-Sep-2021 11:05:18.448 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
17-Sep-2021 11:05:18.449 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/opt/tomcat/conf/logging.properties
17-Sep-2021 11:05:18.450 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
17-Sep-2021 11:05:18.451 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
17-Sep-2021 11:05:18.452 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.security.egd=file:/dev/./urandom
17-Sep-2021 11:05:18.453 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
17-Sep-2021 11:05:18.454 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
17-Sep-2021 11:05:18.455 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
17-Sep-2021 11:05:18.456 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms512M
17-Sep-2021 11:05:18.458 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx1024M
17-Sep-2021 11:05:18.459 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseParallelGC
17-Sep-2021 11:05:18.460 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
17-Sep-2021 11:05:18.461 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/opt/tomcat
17-Sep-2021 11:05:18.463 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/opt/tomcat
17-Sep-2021 11:05:18.464 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/opt/tomcat/temp
17-Sep-2021 11:05:18.479 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib/arm-linux-gnueabihf/jni:/lib/arm-linux-gnueabihf:/usr/lib/arm-linux-gnueabihf:/usr/lib/jni:/lib:/usr/lib]
17-Sep-2021 11:05:21.253 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
17-Sep-2021 11:05:21.525 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [4873] milliseconds
17-Sep-2021 11:05:22.080 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
17-Sep-2021 11:05:22.083 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.53]
17-Sep-2021 11:05:22.250 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/opt/tomcat/webapps/airsonic.war]
17-Sep-2021 11:05:55.621 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
{...}

**Comment by The-Exterminator** [comment]
Remember this :

Make sure that the Tomcat service has access to your music folders, by adding the following lines to /etc/systemd/system/tomcat9.service.d/airsonic.conf (add as many ReadWritePaths lines as necessary):

[Service]
ReadWritePaths=/var/airsonic/

**Comment by jr1234jr** [comment]
Hi,

issue could be solved by installing tomcat9 via apt-get instead of curl.

thanks
