### ISSUE TITLE
Compilation albums being split by multiple unique artists

### ISSUE THREAD

**Issue by jeffvli** [airsonic-advanced/airsonic-advanced#631]
## Problem description

When scanning in albums, if there are multiple unique `Artist` tags in the same `Album`, then the album will be split up into multiple separate albums with only the specified songs with the unique artist in them.

I'm coming from vanilla airsonic, where this wasn't the case, and albums were automatically grouped together if they were part of the same `Album` tag or folder. I've noticed this same thing with Navidrome, but [they have documented a couple required tags for the album to be grouped together](https://www.navidrome.org/docs/faq/#i-have-an-album-with-tracks-by-different-artists-why-is-it-broken-up-into-lots-of-separate-albums-each-with-their-own-artist). Having tried those tags, they don't seem to be the same for airsonic-advanced.

In that case, is there a specific tag that is required for all tracks of the album for them to be grouped together?

What I have tried:
- Set `Album Artist` the same for all tracks
- Set `Compilation` to true for all tracks
- Set `Part of Compilation` to true for all tracks
- Set `TCMP` to true for all tracks
- Set `Release Type` to album

### Steps to reproduce

1. Have album with multiple different unique artists (not separated by `;`)
2. Scan library
3. View albums

## System information

 * **Airsonic version**: Docker:latest

**Comment by troycarpenter** [comment]
The way I've done this for previous "sonic" type servers.  Note that you say you've already tried this, but maybe you will spot something different.

1. Artist (TPE1) tag is whomever is performing.
2. Album Artist (TPE2) tag is "Various Artists", or whatever (this works when a track has a guest artist in the artist tag, but you want the track classified with the main artist).
3. Place all tracks from the album in a common album folder.  Don't forget the folder layout, which is "FOLDER -> ARTIST -> ALBUM".  When I do this, I put the album in a folder which is the same as the Album Artist tag.

For instance: Soundtracks->Disney->Cars is where I would put tracks for the Disney Cars soundtrack, with Album Artist set to "Disney" for each track but the actual performer in the Artist tag.  I do that for all my Disney soundtracks, and on the artist list to the left of the screen, if I select the artist "Disney", I get all the soundtracks in the main window (and last.fm claims my media is incorrectly tagged when I do it this way).

I notice that in AA, only the Album Artist is indexed for searches, so there's no way to find the individual track based on the track artist.
