### ISSUE TITLE
Wrong redirection with reverse-proxy setup (nginx) to other port/site

### ISSUE THREAD

**Issue by nRaecheR** [airsonic-advanced/airsonic-advanced#635]
I'm trying to update from Airsonic-Advanced v10.6.0 to v11 (Docker Tag Latest from 27.9.2021). The installation works as expected when accessed directly through port 4040. When accessed through the reverse-proxy (port 8181), which has worked with Airsonic for years, the browser will be redirected to the default site of the webserver (port 443). Here's the proxy configuration of nginx: 

```
# vim: set autoindent smartindent ts=4 sw=4 sts=4 noet filetype=nginx:

server {
        listen 8181 ssl http2;

        server_name sub.domain.tld;

        include /config/nginx/ssl.conf;

        location / {
                proxy_set_header Upgrade           $http_upgrade;
                proxy_set_header Connection        "Upgrade";
                proxy_http_version 1.1;
                proxy_set_header X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
                proxy_set_header X-Forwarded-Host  $http_host;
                proxy_set_header Host              $http_host;
                proxy_max_temp_file_size           0;
                proxy_pass                         http://<localip-of-server>:4040/;
                proxy_redirect                     http:// https://;
                proxy_buffering 		   off;
                proxy_request_buffering            off;
                proxy_set_header Origin            '';
                client_max_body_size               0;
                }
}
```
The docker container will be started with this parameter added: 
```
-e "JAVA_OPTS=-Xmx2048m -Dserver.forward-headers-strategy=native"
```

The installation was migrated from Airsonic 10.6.0 to Airsonic-Advanced before. This migration has worked as expected. The redirection works with the reverse-proxy setup with 10.6.2 too.

### Steps to reproduce

1. Setup Airsonic-advanced "latest" as Podman container
2. Setup nginx "latest" as Podman container
3. Use site configuration above
4. Access the web-UI through  sub.domain.tld:8181
5. Login to site

The browser gets redirected to the default page of https://sub.domain.tld

## System information

 * **Airsonic version**: *Docker "Latest" version from 27.9.2021*
 * **Operating system**: *Podman 3.20 on Ubuntu 21.04, AMD64*
 * **Java version**: *From Docker "Latest" version from 27.9.2021*
 * **Proxy server**: *NGINX Docker Container, latest*

**Comment by cascooscuro** [comment]
Take a look at:
https://github.com/airsonic-advanced/airsonic-advanced/issues/453

and also don't forget context path change:

*server.context-path -> server.servlet.context-path (Airsonic will use the latter from 11.0 onwards)*

**Comment by nRaecheR** [comment]
Thank you for your answer. As you can see in the first post, I've already adapted the nginx proxy configuration to post #453. As far as I understand I don't need to modify the context-path because it will be served as / document of the webserver. The context path variable isn't set for the old 10.6.x installation though. Am I wrong?

The updated installation is working without the proxy as expected and the proxy setup with Airsonic_Advanced 10.6.0 too.

**Comment by cascooscuro** [comment]
Sorry, you are right. Somehow I understood that it was a path issue.

Have you checked nginx access logs to see if there's anything relevant?

**Comment by nRaecheR** [comment]
Nothing special, maybe you can see more, here's the access.log lines from the login attempt above: 

```
<clientip> - - [29/Sep/2021:16:48:19 +0200] "GET /login HTTP/2.0" 200 1125 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0"
<clientip> - - [29/Sep/2021:16:48:19 +0200] "GET /script/mousetrap-1.6.0.js HTTP/2.0" 304 0 "https://sub.domain.tld:8181/login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0"
<clientip> - - [29/Sep/2021:16:48:19 +0200] "GET /script/keyboard_shortcuts.js HTTP/2.0" 304 0 "https://sub.domain.tld:8181/login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0"
<clientip> - - [29/Sep/2021:16:48:19 +0200] "GET /icons/default_light/logo.png HTTP/2.0" 304 0 "https://sub.domain.tld:8181/login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0"
<clientip> - - [29/Sep/2021:16:48:24 +0200] "POST /login HTTP/2.0" 302 0 "https://sub.domain.tld:8181/login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0"
<clientip> - - [29/Sep/2021:16:48:24 +0200] "GET /index HTTP/2.0" 302 0 "https://sub.domain.tld:8181/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0"
<clientip> - - [29/Sep/2021:16:48:24 +0200] "GET /apps/dashboard/ HTTP/2.0" 200 13456 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0"
```
The /apps/dashboard is the default site on port 443.

**Comment by nanderson94** [comment]
Try adding in your nginx configuration:

```
proxy_set_header X-Forwarded-Port  $server_port;
```

[This StackOverflow answer](https://stackoverflow.com/a/68318932) indicates that embedded SpringBoot server will handle that header with `server.forward-headers-strategy=native` set.

**Comment by nRaecheR** [comment]
Yes, this fixes the problem. I've added the line to the proxy config file, reloaded it and now it works as expected. 

Thank you very much!

**Comment by PSilverQ** [comment]
> Yes, this fixes the problem. I've added the line to the proxy config file, reloaded it and now it works as expected.
> 
> Thank you very much!

How did you fix ? I met the same problem, I also add `erver.forward-headers-strategy=native`, it doesn't work at all, nginx reverse proxy always redirect to standard http/https port, I've been working for days.....

my Nginx conf
```
    location / {
           proxy_set_header Upgrade           $http_upgrade;
           proxy_set_header Connection        "Upgrade";
           proxy_http_version 1.1;
           proxy_set_header X-Real-IP         $remote_addr;
           proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
           proxy_set_header X-Forwarded-Proto https;
           proxy_set_header X-Forwarded-Host  $http_host;
           proxy_set_header X-Forwarded-Port  $server_port;
           proxy_set_header Host              $http_host;
           proxy_max_temp_file_size           0;
           proxy_pass                         http://0.0.0.0:4040;
           proxy_redirect                     http:// https://;
           proxy_buffering off;
           proxy_request_buffering off;
           proxy_set_header Origin            '';
           client_max_body_size 0;
        }

```

nginx version
```
# nginx -v
nginx version: nginx/1.14.1
```

Docker run arguments

```
docker run \
    -d \
    --name=airsonic \
    -u 1000:1000 \
    -e TZ=Asia/Shanghai \
    -e JAVA_OPTS=-Dserver.forward-headers-strategy=native \
    -p 4040:4040 \
    -p 4041:4041 \
    -v /home/music:/var/music \
    -v /home/data/airsonic/podcasts:/var/podcasts \
    -v /home/data/airsonic/playlists:/var/playlists \
    -v /home/data/airsonic/data:/var/airsonic \
    --restart unless-stopped \
    airsonicadvanced/airsonic-advanced:edge-latest
```

I reload nginx config and restart nginx service, when I access my proxy address ,like `https://mydomin:8181/login`, It always redirect to standard https/http port ,like `http://mydomin/login`,Obviously browser connect timeout.

**Comment by nRaecheR** [comment]
My nginx config looks like that: 

```
server {
        listen 8181 ssl http2;

        server_name sub.domain.ltd

        include /config/nginx/ssl.conf;

        location / {
                proxy_set_header Upgrade           $http_upgrade;
                proxy_set_header Connection        "Upgrade";
                proxy_http_version 1.1;
                proxy_set_header X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
                proxy_set_header X-Forwarded-Host  $http_host;
		proxy_set_header X-Forwarded-Port  $server_port;
                proxy_set_header Host              $http_host;
                proxy_max_temp_file_size           0;
                proxy_pass                         http://<local-ip-of-airsonic>:4040/;
                proxy_redirect                     http:// https://;
                proxy_buffering 		   off;
                proxy_request_buffering            off;
                proxy_set_header Origin            '';
                client_max_body_size               0;
                }
}

``` 

nginx version is 

``` 
nginx version: nginx/1.20.2
``` 

and the same docker JAVA envvar.

**Comment by PSilverQ** [comment]
> 

fixed .  I used the same conf with you while I have the wrong direction problem . At last I comment the line `proxy_set_header X-Forwarded-Proto https;`，problem disappear .

I don't know why ,I think It's maybe the Spring-framework header `X-Forwarded-Prot` support bug .I was inspired the issue: [Airsonic ignores port in Host and X-Forwarded-Host](https://github.com/airsonic/airsonic/issues/1809)

the issue reporter said:

> Solved - it's spring-framework issue. It's not processing port in "X-Forwarded-For". And for "X-Forwarded-Proto https" it's needs additional "X-Forwarded-Port".
