### ISSUE TITLE
Port 1900 is used from Synology Media Server

### ISSUE THREAD

**Issue by Julius1569** [airsonic-advanced/airsonic-advanced#662]
Hi all,

have the following issue, hope you can help.

## Problem description
Use Airsonic-Advanced on my Synology NAS DS720+. Everything works fine, until I installed the package Media Server from Synology. The Airsonic container was stopped, after installation from Media Server. The problem seems to be, that the Media Server also use port 1900.
What can I do?

## System information
- Airsonic Advanced, version from 29 October.
- Hardware: Synology NAS DS720+
- Airsonic Advanced runs in Docker container

*Include any extra notes here. Otherwise you may remove this section.*

**Comment by randomnicode** [comment]
are you using the docker version?
Do you have port 1900 bound to the airsonic-advanced container?

**Comment by Julius1569** [comment]
Thanks for your feedback. 
I use the standard Docker package from Synology, Version: 20.10.3 - 1239. 
The port1900 was automatically bound, during the installation of airsonic-advanced container.
If there isn't needed, I will delete it.
I get back to you, if I have delete the port, from the airsonic-advanced container.

**Comment by Julius1569** [comment]
Have delete the UDP port 1900 from Docker container. The container start and airsonic-advanced works. 
The issue now is, that the music service Airsonic don't appears in my Sonos controller app. The Sonos controller seem to be working with UDP port 1900. 
In airsonic-advanced, I get the message "No Sonos controller(s) found"
Have the following settings for Sonos in airsonic-advanced:
![Airsonic_Advanced_Sonos_Setup](https://user-images.githubusercontent.com/92916628/141683574-d27dcca4-6562-45d8-97eb-1d1b105827d8.png)

What can I do?

**Comment by randomnicode** [comment]
Not sure we get the problem here.
You seem to have 2 containers (Media Server and aa), both of which want to use port 1900 on the host because Sonos communicates via that port?

You need to choose which app should bind to 1900.

**Comment by Julius1569** [comment]
Problem is solved. In airsonic advanced container, I have changed the local port from 1900 > 19000 and it works. 
![2021-11-21 15_28_10-NAS_DS720plus - Synology NAS_local_Port_19000](https://user-images.githubusercontent.com/92916628/142766562-1f58be3a-4c14-43ab-84cf-d319579bda63.png)
Unfortunately I don't know exactly what "local port" means in this case, and what this setting does. It was simply an attempt.
Media Server is not a Docker container, it is a package from Synology Package Center. Media Server defintly use port 1900.
However, it works now and I am lucky.
Thanks for your help.

**Comment by randomnicode** [comment]
can we close this issue please now?

**Comment by Julius1569** [comment]
yes of course.
