### ISSUE TITLE
SubSonic API 1.15.0 and above?

### ISSUE THREAD

**Issue by count00zero** [airsonic-advanced/airsonic-advanced#688]
Regarding ping.view (for example)
When trying the new android app subtracks it worked instantly with navidrom but not with amapche-advanced & ampache.

After checking the logfiles the difference was within the usage of `ping` vs `ping.view`

Subsonic API v 1.15.0. allows the use of ping without .view
http://www.subsonic.org/pages/api.jsp#ping

Now austinried [over at subtracks changed his app](https://github.com/austinried/subtracks/issues/42), so that subsonic API version 1.14.0. (with .view) works as well.

Would it also be possible to extend airsonic and allow `ping` without `.view`?

**Comment by randomnicode** [comment]
not sure which version of airsonic advanced you're using?

airsonic-advanced does not need `.view` suffix for rest calls

https://github.com/airsonic-advanced/airsonic-advanced/blob/7b25979b55d8a7c68ecc963daee60b2c43f3bf82/airsonic-main/src/main/java/org/airsonic/player/controller/SubsonicRESTController.java#L167-L171

**Comment by count00zero** [comment]
very interesting ... when I tried the former version of the app - which just used ping - I couldn't get it to work.
Must have been me :)
