### ISSUE TITLE
Home panel shows nothing in docker installation

### ISSUE THREAD

**Issue by XrenynTheMage** [airsonic-advanced/airsonic-advanced#695]
## Problem description

When installing airsonic-advanced via Docker, music files are correctly imported and displayed in the left content pane, but the "Home" content pane to the center of the screen and all of its subcategories remain empty (see screenshot below).

![grafik](https://user-images.githubusercontent.com/37195767/145277241-fb2b6073-f898-4553-a8c2-9a110f5e6657.png)

I know the music files are imported properly since I can play them just fine, they simply don't end up on the home panel.
It doesn't seem to matter how much I use airsonic-advanced, the size of the music library, the browser used to access the web GUI (I tried Firefox and Chrome/Chromium), what device or operating system I install the Docker container on (I tried the latest x64 version of DietPi on my Raspberry Pi, x64 Windows 10 on my custom-built PC with an AMD Ryzen 1600 processor, and 64 bit Ubuntu 20.04.3 LTS on my ThinkPad Yoga L13 with an intel core i5 processor), or even whether I use docker-compose or docker-cli to start the container.

### Steps to reproduce

- Install Docker on any device with a folder containing mp3 files, and install the official airsonic-advanced docker image as outlined in https://hub.docker.com/r/airsonicadvanced/airsonic-advanced , while making sure the music path is set correctly. 
- Access the web interface using either Chrome or Firefox, log in using the default login credentials.

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20211208080314
 * **Operating system**: DietPi v7.8.2, Ubuntu 20.04.3 LTS, Microsoft Windows 10 Pro Version	10.0.19043 Build 19043

 * **Java version**: OpenJDK version 14.0.2
 * **Proxy server**: None
 * **Client**: Firefox 94.0.2, Google Chrome Version 96.0.4664.9, Chromium Version 96.0.4664.45
 * **Language**: English

**Comment by randomnicode** [comment]
can you check what chrome developer console says?

**Comment by XrenynTheMage** [comment]
I don't see any error messages, but you're free to inspect the chrome console logs for yourself: https://gist.github.com/XrenynTheMage/e4e12e3a84e4b47788a98c272f5c5a64

**Comment by randomnicode** [comment]
Are all your music files just in the root music folder? There's no hierarchy?

**Comment by XrenynTheMage** [comment]
Indeed, that is the case. Previously I have used MediaMonkey to organize and play my collection, which identifies artists and albums based on the tracks' metadata, and it may have put all my songs into the same folder last time I made it move my entire collection from one drive to another. Do you think I should just sort my music into subdirectories by artist or album?

**Comment by randomnicode** [comment]
> Do you think I should just sort my music into subdirectories by artist or album?

No, we are of the opinion that you should organize your music however you prefer.

The basis for the question was just trying to diagnose the issue, and it seems we've found it.
Airsonic-Advanced currently will display and show albums according to a folder hierarchy.
It's not the best means to do it, but currently it is the only means. This may change in the future.
