### ISSUE TITLE
Some Russian Text is not right visible 

### ISSUE THREAD

**Issue by masterwishx** [airsonic-advanced/airsonic-advanced#725]
Some russian test is unnreadble i was using HyperSQL  1.8 and then converted to MariaDB MySQL: 5.5.5-10.5.13-MariaDB
This text also in database so maybe its databse problem ...

Unraid (Linux x64)
binhex/arch-airsonic-advanced
10.6.0.20200424173747 – 24 апреля 2020 г. 20:37:47 IDT
Apache Tomcat/9.0.33, java 1.8.0_281, Linux (139,7 MB / 960,0 MB)

![image](https://user-images.githubusercontent.com/28630321/147368526-14b135d1-51e8-47ab-bea8-3ee1720b2a8d.png)
![image](https://user-images.githubusercontent.com/28630321/147368541-f65df71c-7aa0-42be-8532-400889e10849.png)

**Comment by randomnicode** [comment]
> 10.6.0.20200424173747

This is an old version. Switch to a newer version?

> This text also in database so maybe its databse problem

We agree. `utf8_general_ci` collation implies that you're using an older charset (`utf8`), which only allows 3 bytes per char.  You should likely be using `utf8mb4`, which is 4 bytes per char. Change your character set and your collation in your DB. This won't fix the issue with the existing data (you've already lost some data storing in `utf8` character set), but will likely solve the issue going forward. If you have the old HSQL db, you can try going from that to a DB that is `utf8mb4`.

You can read more about utf8 and utf8mb4 at MySQL or MariaDB or really all over the internet.

**Comment by masterwishx** [comment]
Thanks, sorry I forgot to write about utf8mb4. 
The container I'm using will update to new version when it will be stable release. 
Maybe I will try the original one. 
I already changed my Mariadb to utf8mb4 default
But don't remember if it was before I added airsonic. So I will try change it to utf8mb4.. 
In documentation of airsonic advanced wrote its need utf8. This why I asked. 
I'm not really converted db from hsql, I made from start and added all. 
So now to convert all to utf8mb4 I need to set db in utf8mb4 and also all tables. 
I will try do it..

**Comment by randomnicode** [comment]
>  In documentation of airsonic advanced wrote its need utf8. This why I asked.

Where? We've always tried to tell people to use utf8mb4. The legacy airsonic documentation told people to use utf8, which we disagreed with.

**Comment by masterwishx** [comment]
![image](https://user-images.githubusercontent.com/28630321/147499873-2e19527d-6fbb-4550-9496-0fafc31f91bb.png)
i will try to fix it to utf8mb4 ,should i use utf8mb4_general_ci ?

**Comment by randomnicode** [comment]
> The legacy airsonic documentation told people to use utf8, which we disagreed with.

As we wrote, that's the legacy airsonic documentation

> should i use utf8mb4_general_ci

that's a case-insensitive collation for utf8mb4. You can use it if you don't care about case sensitivity. When sorting capital letters and small case letters will not be distinguished.

**Comment by masterwishx** [comment]
> As we wrote, that's the legacy airsonic documentation

I got it. 

> that's a case-insensitive collation for utf8mb4.

What utf8mb4 you suggest for Airsonic Advanced?

**Comment by masterwishx** [comment]
Finnaly converted to utf8mb4_unicode_ci by scrypt https://github.com/fleio/utf8mb4-convert , readded music with russian text its fixed some , but some text still unreadble , like i said in total commander in windows all OK.

is utf8mb4_unicode_ci good or better utf8mb4_general_ci for more performace ?
i have only 4 cores cpu in unraid and a lot of dockers ?
not looking to fix what is left .
also all varchar is (384) should it be changed to varchar(255)  ? maybe by changingMySQL Varchar Maximum Length () if it needed?

**Comment by masterwishx** [comment]
i also installed the last version of docker airsonic-advanced and made new db in mariaDB utf8mb4_general_ci 
but there is also having problems with some russian text like in v10.6 ...
i thouth its databse problem , but i think the program (airsonic ) is reading catalogs and file names and put them to DB right?
11.0.0-SNAPSHOT.20211220002741

**Comment by randomnicode** [comment]
> i think the program (airsonic ) is reading catalogs and file names and put them to DB right?
11.0.0-SNAPSHOT.20211220002741

Yes, the program reads file and folder names from your disk (including metadata) and then puts it into the db.
Java itself shouldn't have a problem reading folder names unless you're running in a weird environment.
The db should have no issues handling different charsets once it's utf8mb4

Do the issues happen even when you don't use an external db?

**Comment by masterwishx** [comment]
> Do the issues happen even when you don't use an external db?

Yes, in v10.6 when I started using airsonic, first used hsqldb, after some time switched to mariadb. 
I think maybe some text in some old Russian code like koi8 or something...
But like I said in windows and total commander it's OK. But didn't checked how it's in Unraid where I'm using docker of airsonic. 
After changed to utf8mb4 it's more text looks OK
but some text still unreadable, even somehow in one catalog some listed song unreadble.

**Comment by masterwishx** [comment]
Finally problem solved.
After more searching on internet, the problem was in tags, some was v1 other v2. 3 but still. using mp3tag reading and saving to v2.3 utf16
The problem is gone. 
Thanks for helping
