### ISSUE TITLE
Airsonic crashing on start

### ISSUE THREAD

**Issue by khers** [airsonic-advanced/airsonic-advanced#729]
## Problem description

My airsonic service is failing to start because I have too many deleted entries in the podcast episode table. As noted in #505 some podcasts are seeing duplicated entries because the URL to the entry is not consistent (and is not required to be). I work around this by having a python script that asks airsonic to delete all the "SKIPPED" podcasts in the feeds I know to have this problem. However, that means that the data for the podcast episodes table is too large to be loaded by hsqldb. This was a problem in Subsonic as well and I used to fix it my manually deleting the lines in the db script that mentioned SKIPPED podcasts.

EDIT: forgot to mention that this work around no longer works so my airsonic is currently unusable.

Exception trace can be found at https://gist.github.com/khers/deca4ba9d3ba11e69bd4a403eb636b04
Honestly, I don't know how you Java devs make use of these stacks, they are inscrutable to me.

### Steps to reproduce

1. Subscribe to several podcasts that have URLs which change for an episode
2. Delete all the new "SKIPPED" episodes daily for several weeks
3. Airsonic will refuse to start

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20211208080314 – December 8, 2021 at 8:03:14 AM UTC [Commit: dc9c37c]
 * **Operating system**: Ubuntu 20.04
 * **Java version**: openjdk 13.0.7 2021-04-20
 * **Proxy server**: Apache from Ubuntu 20.04
 * **Client**: Firefox and DSub
 * **Language**: en_US

**Comment by randomnicode** [comment]
This seems like a db corruption issue.

Additionally, the lob file probably doesn't get truncated by just deleting the rows. You need to checkpoint to consolidate the rows.

Refer to HSQLDB documentation. Perhaps doing something like SHUTDOWN COMPACT or SHUTDOWN SCRIPT or CHECKPOINT DEFRAG on the db will help.

**Comment by randomnicode** [comment]
The dual entries on podcasts is indeed a problem that we'll look to fix

**Comment by khers** [comment]
Using DBeaver to open the database and run the commands you suggested seems to have fixed me, thanks!

Do you want to close this issue?
