### ISSUE TITLE
Push official images to a different registry, in addition to Docker Hub

### ISSUE THREAD

**Issue by Ryan-McD** [airsonic-advanced/airsonic-advanced#742]
## Problem description

Dockerhub rate limits can prevent pulling image for 6 hours

### Steps to reproduce

Running kubernetes

## Additional notes

Push airsonic-advanced (especially edge/latest) to an additional registry. e.g. GHCR or Quay

**Comment by randomnicode** [comment]
Done, pushing to GHCR now in additon to Docker Hub.

ghcr.io/airsonic-advanced/airsonic-advanced
