### ISSUE TITLE
Database crash after uploading file using the uploader?

### ISSUE THREAD

**Issue by DutchComputerKid** [airsonic-advanced/airsonic-advanced#744]
## Problem description
Another issue, but now Airsonic seems completely borked.

I wanted to upload a file using the More... menu, but when the upload finished I got a 502 and looking at Airsonic it spit out ~800 lines of errors. 
For full 'log' see this paste:  https://controlc.com/aedf8db8

First it complained about OutOfMemoryErrors, and I had to give it a good 4GB to get any more like out of it after which:

_java.sql.SQLException: error in script file line: 131 org.hsqldb.HsqlException: IO error: RowInputBinary 124078_

appeared, but looking for that error there is barely any info if at all.

### Steps to reproduce
1. Upload a file via the More page
2. Watch NGINX give you a 502.
3. Airsonic will now refuse to start anymore.

Behaviour should be easy to do, if one's wondering it was the zip file for [this](https://www.doujinstyle.com/?p=page&type=1&id=18001) single.

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20220110133315
 * **Operating system**: Debian GNU/Linux 11 (bullseye) x86_64
 * **Java version**: *AdoptOpenJDK 11 2021-04-20*
 * **Proxy server**: NGINX 1.20.2
 * **Client**: Opera GX, Chrome, Safari and Firefox do this.
 * **Language**: English

**Comment by randomnicode** [comment]
database seems likely corrupted. please use a backup and restore

**Comment by randomnicode** [comment]
can we close this?

**Comment by DutchComputerKid** [comment]
Complete forgot to, oops.
