### ISSUE TITLE
playback stop after 05:01

### ISSUE THREAD

**Issue by hasamba** [airsonic-advanced/airsonic-advanced#745]
## Problem description

Almost every song stopped playing after 05:01 min when using web player, no problem when using apps
pressing "next" after the playback stopped, sometimes work and sometime i have to refresh the connection

### Steps to reproduce

1. start playing an album with songs larger than 5 min
2. play

## System information

 * **Airsonic version**: *Docker: 11.0.0-SNAPSHOT.20220119073733 – January 19, 2022*
 * **client**: *Win 10*
 *  **server**: *Apache Tomcat/9.0.48, java 14.0.2, Linux (3.32 GB / 4.00 GB)*
 * **Client**: *latest firefox*
 * **Language**: *english*

## Additional notes
![image](https://user-images.githubusercontent.com/7392290/150643204-0a26f914-a020-4ab7-8435-565282f3822d.png)

nothing in the logs..
![image](https://user-images.githubusercontent.com/7392290/150643269-8c19edf0-fbe5-43dd-88d9-c8c141c5c1be.png)

**Comment by Yetangitu** [comment]
5 minutes equals 300 seconds, sounds like a timeout. Are you running Airsonic behind a reverse proxy like _nginx_ or _apache_? If so, check if the problem appears when connecting directly to Tomcat or add a longer timeout to the reverse proxy (e.g. in nginx add `proxy_read_timeout 36000s;` to the `/websocket` location section for a 10-hour timeout).

**Comment by hasamba** [comment]
i'm using nginx-proxy, 
in proxy.conf i see  `proxy_read_timeout 30m;`

is this the config you meant?

**Comment by Yetangitu** [comment]
Yes, 30 minutes should be sufficient so that casts doubt upon my suggestion. Try to connect directly to Tomcat to see whether it works without the reverse proxy.

**Comment by hasamba** [comment]
i cannot connect directly to tomcat, only through my subdomain... it's going through cloudflare and nginx...
i changed to 3600s (although the 30m came by default) and i think that it's fixed
i'll reopen if ill see it again

thanks alot for your help
