### ISSUE TITLE
Albums show up in random order when browsing to an artist and in cover view

### ISSUE THREAD

**Issue by jarrodCoombes** [airsonic-advanced/airsonic-advanced#751]
## Problem description

My music is in Artist/Album/Songs format. In the web interface, when I click on a specific artist on the A/Z list to the left the albums are listed in a completely random order, in fact if I click the name a second time the albums change their order. If I switch to list view, the albums are sorted by year, and this does not change with multiple clicks. There is not obvious way to set the sort order for the cover view.

When not in a specific artist, the cover view has all the albums listed in alphabetical order by artist, again with no obvious way on how to change the sort order.

### Steps to reproduce

1. Browse to the main page.
2. Click on a artist in the alpha list on the left
3. Set the view to album cover (not list) if need be.
4. Repeatedly click on the artist name on the left and watch the list of covers change order randomly.

## System information

 * **Airsonic version**: 10.6.0.20200424173747 – April 24, 2020 10:37:47 AM PDT
 * **Operating system**: Docker image on Unraid
 * **Java version**: Apache Tomcat/9.0.33, java 1.8.0_281, Linux (352.9 MB / 654.0 MB)
 * **Proxy server**: It is proxied via nginx on an ubuntu 20.04 LTS machine.
 * **Client**: Chrome browser, v97.0.4692.71
 * **Language**: English

**Comment by luxdi** [comment]
You might want to update to the latest snapshot. I had this problem too and was fixed in Issue #501 last year.

https://github.com/airsonic-advanced/airsonic-advanced/pull/501

**Comment by randomnicode** [comment]
> Airsonic version: 10.6.0.20200424173747 – April 24, 2020 10:37:47 AM PDT

You're on an extremely old version of AA. Upgrade to the latest snapshot please
