### ISSUE TITLE
Error 401 while trying to reach interface (docker version)

### ISSUE THREAD

**Issue by racine-p-a** [airsonic-advanced/airsonic-advanced#752]
Hello and thank you for your job

## Problem description

Can't access to airsonic interface --> error 401

### Steps to reproduce

1. Docker : `docker run --name=airsonic  -d -u root:root --net=airsonic -e TZ=America/Los_Angeles -e JAVA_OPTS=-Dserver.forward-headers-strategy=native -p 4040:4040 -p 4041:4041 -v /root/logiciels/airsonic/music:/var/music -v /root/logiciels/airsonic/podcasts:/var/podcasts -v /root/logiciels/airsonic/playlists:/var/playlists -v /root/logiciels/airsonic/data:/var/airsonic --restart unless-stopped airsonicadvanced/airsonic-advanced:latest` 
2. Wait few minutes for initialisation
3. `curl localhost:4040` --> `{"timestamp":"2022-01-25T10:11:20.761+00:00","status":401,"error":"Unauthorized","path":"/"}`

## System information

 * **Airsonic version**: docker latest
 * **Operating system**: Ubuntu 20.04 LTS
 * **Java version**: dockerized
 * **Client**: curl
 * **Language**: n/a

## Additional notes

I just wanted to test airsonic on a remote server. I copy/pasted the instructions from the docker page and github readme (with minor obvious adjustments) and launched it on my server ant tried to connect, and failure incoming.

I have no clue if the problem comes from a mistake i could have made or a problem in the docker image.

Hopes it helps.

Best regards :)

**Comment by racine-p-a** [comment]
Well after digging more and more, I have the same problem on all my docker containers now...
Sorry for this useless issue, I hope i did not waste the time of anyone.

**Comment by nioupola** [comment]
Hello,

I have the same issue. What did you change to make it works again?

Thanks!

edit: seems that `/` is denied but using `/login` or `/index` works. Maybe a change for default route when URI is not specifeid.
