### ISSUE TITLE
script to install the latest airsonic-advanced snapshot

### ISSUE THREAD

**Issue by hboetes** [airsonic-advanced/airsonic-advanced#764]
To make my life a bit easier, I wrote this script to download the latest snapshot of airsonic-advanced. Of course it's a simple hack, and you should adjust it to your own needs.

It also accepts arguments, so `sudo ./update-airsonic 2` installs the previous version.

You need to have curl installed.

```bash
#!/bin/sh
AIRSONICWAR=/usr/local/libexec/airsonic.war
AIRSONICDIR=/var/airsonic
AIRSONICLOG=$AIRSONICDIR/airsonic.log

alias restart='rcctl restart airsonic'

# https://github.com/airsonic-advanced/airsonic-advanced/issues/764

PATH=/bin:/usr/sbin:/usr/bin:/usr/local/bin
older=${1:-1}

eval $(unzip -qc /usr/local/libexec/airsonic.war WEB-INF/classes/build.properties | egrep '^(version|timestamp)=')
current="$version.$timestamp"

if ! latest=$(curl -s https://api.github.com/repos/airsonic-advanced/airsonic-advanced/tags | awk -F'"' '/name.*SNAPSHOT/ && ++i == '$older' {print $4}'); then
    echo "Couldn't get the latest airsonic snapshot version." >&2
    exit 1
fi

if [ "$latest" == "$current" ]; then
    echo "Already up to date"
    exit 0
fi

if ! whoami | grep -q root; then
    echo "Restart this script with root permissions to perform the upgrade, i.e.:" 2>&1
    echo "  sudo $0 $*" 2>&1
    exit 1
fi


if ! TMPFILE=$(mktemp /tmp/airsonic.war.XXXXXXXXXX); then
    echo 'mktemp failed!' >&2
    exit 1
fi

if ! curl -o $TMPFILE -L https://github.com/airsonic-advanced/airsonic-advanced/releases/download/$latest/airsonic.war; then
    echo "Download failed!" >&2
    exit 1
fi

# Create a backup
echo "backup old version"
rsync --delete -avP $AIRSONICDIR $AIRSONICDIR.bak
rsync $AIRSONICWAR $AIRSONICDIR.bak

sudo install -m 444 $TMPFILE $AIRSONICWAR
rm -f $TMPFILE
restart
echo "Now wait a minute! Yes literally!"
tail -n0 -f $AIRSONICLOG
```

**Comment by dsiminiuk** [comment]
@hboetes 

The only thing I can contribute here is to not hard code the major version. What happens when it goes to 11.0.1?
```
current="11.0.0-SNAPSHOT.$current"
```

You might try...
```
if ! current=$(unzip -qc /var/airsonic/airsonic.war WEB-INF/classes/build.properties | awk -F '=' '/^timestamp=/ {ts=$2}; /^version=/ {version=$2}; END {print version"."ts}')
```
This will get the version and timestamp out of the war file and output them in the correct format to compare to the online version and timestamp from this...
```
curl -s https://github.com/airsonic-advanced/airsonic-advanced/releases | fgrep "<a href=\"/airsonic-advanced/airsonic-advanced/releases/download/" | head -1 | awk -F/ '{print $6}'
```
Maybe you can improve this, but these are the snippets I'm using in my script.

**Comment by dsiminiuk** [comment]
And the current version line can be simplified and head removed as well...
```
curl -s https://github.com/airsonic-advanced/airsonic-advanced/releases | fgrep "<a href=\"/airsonic-advanced/airsonic-advanced/releases/download/" | awk -F/ 'NR==1{print $6}'
```

**Comment by hboetes** [comment]
@dsiminiuk, thanks for your suggestions! I will apply them and update the script soonish.

**Comment by dsiminiuk** [comment]
@hboetes  There are so many ways to do things in Linux; here is an improvement on the latest release line that eliminates the pipe through fgrep.
```
curl -s https://github.com/airsonic-advanced/airsonic-advanced/releases | awk -F/ '$0~/<a href=/ && $0~/releases\/download/ { if ($6 != ""); print $6; exit}'
```
I'm having too much fun!

**Comment by hboetes** [comment]
@dsiminiuk thanks for your suggestions, I've implemented a few of your ideas, albeit with a somewhat different method and added support for creating a backup.

**Comment by B16WLL** [comment]
@hboetes Thanks very much for your efforts. I've adapted the script for use with Airsonic running as systemd service on Ubuntu Linux, and to use wget for download (I like the visual feedback)
`#!/bin/sh
AIRSONICWAR=/var/airsonic/airsonic.war
AIRSONICDIR=/var/airsonic
AIRSONICLOG=$AIRSONICDIR/airsonic.log


# https://github.com/airsonic-advanced/airsonic-advanced/issues/764

PATH=/bin:/usr/sbin:/usr/bin:/usr/local/bin
older=${1:-1}

eval $(unzip -qc $AIRSONICWAR WEB-INF/classes/build.properties | egrep '^(version|timestamp)=')
current="$version.$timestamp"
echo "Currently installed version is '$current'."

if ! latest=$(curl -s https://api.github.com/repos/airsonic-advanced/airsonic-advanced/tags | awk -F'"' '/name.*SNAPSHOT/ && ++i == '$older' {print $4}'); then
    echo "Couldn't get the latest airsonic snapshot version." >&2
    exit 1
fi

if [ "$latest" == "$current" ]; then
    echo "Already up to date"
    exit 0
fi

if ! whoami | grep -q root; then
    echo "Restart this script with root permissions to perform the upgrade, i.e.:" 2>&1
    echo "  sudo $0 $*" 2>&1
    exit 1
fi

echo "Update available to version '$latest', installation will start."
echo "Shutting down Airsonic server, please wait."
systemctl stop airsonic
sleep 10
echo "Backing up airsonic.war to airsonic.bak"
# Delete an existing backup file
rm $AIRSONICDIR/airsonic.bak
mv $AIRSONICDIR/airsonic.war $AIRSONICDIR/airsonic.bak
echo "Downloading updated version, please wait."

if ! wget -O $AIRSONICWAR https://github.com/airsonic-advanced/airsonic-advanced/releases/download/$latest/airsonic.war; then
    echo "Download failed!" >&2
    echo "Restoring from backup"
    mv $AIRSONICDIR/airsonic.bak $AIRSONICDIR/airsonic.war
    exit 1
fi

systemctl start airsonic
echo "Installation complete, restarting Airsonic server, please allow two minutes!"
timeout 120 tail -n0 -f $AIRSONICLOG
exit 0
`
