### ISSUE TITLE
Podcast icons messed up after relative path change

### ISSUE THREAD

**Issue by nowheretobefound** [airsonic-advanced/airsonic-advanced#765]
Latest release boots now, but all podcasts gets the same icon. See screenshot :

![Screenshot_20220130_103128](https://user-images.githubusercontent.com/28619437/151694563-2521a404-ce4e-4439-8a85-9fde3f73b7d4.png)

**Comment by randomnicode** [comment]
Does a rescan fix it?

**Comment by nowheretobefound** [comment]
Nope, but it works in a different browser... Browser cache issue ?

**Comment by nowheretobefound** [comment]
Jepp, browser cache or rescan fixed it :) Please ignore this issue :+1:
