### ISSUE TITLE
Airsonic Advanced won't stay operational

### ISSUE THREAD

**Issue by Iamnome** [airsonic-advanced/airsonic-advanced#766]
## Problem description

Systemd unit starts up but fails after roughly 5 minutes.  Syslog shows a syscall 93 error, which I have looked at and is to do woth fchown, but I am unsure of the next steps.

### Steps to reproduce

Reboot system or restart service with systemctl start airsonic.service

## System information

Airsonic version = 11.0.0-SNAPSHOT.20220129040247
OS = Ubuntu server 20.04.3
Java = openjdk-17-jre

Syslog output:

Jan 30 09:55:41 music java[927]:            _                       _
Jan 30 09:55:41 music java[927]:      /\   (_)                     (_)
Jan 30 09:55:41 music java[927]:     /  \   _ _ __  ___  ___  _ __  _  ___
Jan 30 09:55:41 music java[927]:    / /\ \ | | '__|/ __|/ _ \| '_ \| |/ __|
Jan 30 09:55:41 music java[927]:   / ____ \| | |   \__ \ (_) | | | | | (__
Jan 30 09:55:41 music java[927]:  /_/    \_\_|_|   |___/\___/|_| |_|_|\___|
Jan 30 09:55:41 music java[927]:                                                
Jan 30 09:55:41 music java[927]:                         11.0.0-SNAPSHOT
Jan 30 09:55:42 music java[927]: 2022-01-30 09:55:42.066  INFO --- org.airsonic.player.Application          : Starting Application v11.0.0-SNAPSHOT using Java 17.0.1 with PID 927 (/var/airsonic/airsonic.war started by airsonic in /)
Jan 30 09:55:42 music java[927]: 2022-01-30 09:55:42.082  INFO --- org.airsonic.player.Application          : No active profile set, falling back to default profiles: default
Jan 30 09:55:52 music systemd[1]: systemd-fsckd.service: Succeeded.
Jan 30 09:55:53 music java[927]: 2022-01-30 09:55:53.253  INFO --- l.database.core.HsqlDatabase             : Set default schema name to PUBLIC
Jan 30 09:55:53 music java[927]: 2022-01-30 09:55:53.986  INFO --- l.l.StandardLockService                  : Successfully acquired change log lock
Jan 30 09:55:58 music java[927]: 2022-01-30 09:55:58.140  INFO --- l.c.StandardChangeLogHistoryService      : Reading from PUBLIC.DATABASECHANGELOG
Jan 30 09:55:59 music java[927]: 2022-01-30 09:55:59.107  INFO --- l.l.StandardLockService                  : Successfully released change log lock
Jan 30 09:55:59 music java[927]: 2022-01-30 09:55:59.282  INFO --- l.l.StandardLockService                  : Successfully acquired change log lock
Jan 30 09:55:59 music java[927]: 2022-01-30 09:55:59.423  INFO --- l.c.StandardChangeLogHistoryService      : Reading from PUBLIC.DATABASECHANGELOG
Jan 30 09:55:59 music java[927]: 2022-01-30 09:55:59.773  INFO --- l.l.StandardLockService                  : Successfully released change log lock
Jan 30 09:56:00 music java[927]: 2022-01-30 09:56:00.014  INFO --- o.a.p.service.SettingsService            : Java: 17.0.1+12-Ubuntu-120.04, OS: Linux, Memory (max bytes): 2097152000
Jan 30 09:56:00 music java[927]: 2022-01-30 09:56:00.306  INFO --- org.airsonic.player.Application          : Detected Tomcat web server
Jan 30 09:56:14 music java[927]: 2022-01-30 09:56:14.738  INFO --- o.a.p.s.TaskSchedulingService            : Task remote-playstatus-cleanup scheduled
Jan 30 09:56:15 music java[927]: 2022-01-30 09:56:15.062  INFO --- o.a.p.s.TaskSchedulingService            : Task podcast-channel-refresh--1 scheduled
Jan 30 09:56:15 music java[927]: 2022-01-30 09:56:15.063  INFO --- o.a.p.service.PodcastService             : Automatic default Podcast update scheduled to run every 1 hour(s), starting at 2022-01-30T10:01:15.061514045Z
Jan 30 09:56:15 music java[927]: 2022-01-30 09:56:15.188  INFO --- o.a.p.s.search.IndexManager              : Index was found (index version 19).
Jan 30 09:56:15 music java[927]: 2022-01-30 09:56:15.190  INFO --- o.a.p.s.TaskSchedulingService            : Task mediascanner-IndexingTask scheduled
Jan 30 09:56:15 music java[927]: 2022-01-30 09:56:15.190  INFO --- o.a.p.s.MediaScannerService              : Automatic media library scanning scheduled to run every 1 day(s), starting at 2022-01-31T03:00:00.188714902
Jan 30 09:56:16 music java[927]: 2022-01-30 09:56:16.224  INFO --- o.a.p.s.TaskSchedulingService            : Task db-backup scheduled
Jan 30 09:56:16 music java[927]: 2022-01-30 09:56:16.226  INFO --- o.a.p.service.DatabaseService            : Automatic DB backup scheduled to run every 24 hour(s), starting at 2022-01-30T10:01:16.224404824Z
Jan 30 09:56:24 music java[927]: 2022-01-30 09:56:24.025  INFO --- org.airsonic.player.Application          : Started Application in 49.637 seconds (JVM running for 59.112)
Jan 30 10:01:15 music java[927]: 2022-01-30 10:01:15.062  INFO --- o.a.p.service.PodcastService             : Starting scheduled default Podcast refresh.
Jan 30 10:01:15 music java[927]: 2022-01-30 10:01:15.066  INFO --- o.a.p.service.PodcastService             : Completed scheduled default Podcast refresh.
Jan 30 10:01:16 music java[927]: 2022-01-30 10:01:16.225  INFO --- o.a.p.service.DatabaseService            : Starting scheduled DB backup
Jan 30 10:01:16 music kernel: [  363.747994] kauditd_printk_skb: 7 callbacks suppressed
Jan 30 10:01:16 music kernel: [  363.747998] audit: type=1326 audit(1643536876.276:19): auid=4294967295 uid=1002 gid=1002 ses=4294967295 pid=927 comm="scheduling-1" exe="/usr/lib/jvm/java-17-openjdk-amd64/bin/java" sig=31 arch=c000003e syscall=93 compat=0 ip=0x7f8c4140e4fb code=0x80000000
Jan 30 10:01:16 music systemd[1]: airsonic.service: Main process exited, code=killed, status=31/SYS
Jan 30 10:01:16 music systemd[1]: airsonic.service: Failed with result 'signal'.
Jan 30 10:03:30 music systemd[1]: Started Session 3 of user jon.
Jan 30 10:03:32 music systemd[1]: session-3.scope: Succeeded.

Systemd unit

`[Unit]
Description=Airsonic Media Server
After=remote-fs.target network.target
AssertPathExists=/var/airsonic

[Service]
Type=simple
Environment="JAVA_JAR=/var/airsonic/airsonic.war"
Environment="JAVA_OPTS=-Xmx2000m"
Environment="AIRSONIC_HOME=/var/airsonic"
Environment="PORT=8080"
Environment="CONTEXT_PATH=/airsonic"
Environment="JAVA_ARGS="
EnvironmentFile=-/etc/sysconfig/airsonic
ExecStart=/usr/bin/java \
          $JAVA_OPTS \
          -Dserver.forward-headers-startegy=NATIVE \
          -Dairsonic.home=${AIRSONIC_HOME} \
          -Dserver.servlet.contextPath=${CONTEXT_PATH} \
          -Dserver.port=${PORT} \
          -jar ${JAVA_JAR} $JAVA_ARGS
User=airsonic
Group=airsonic

DevicePolicy=closed
DeviceAllow=char-alsa rw
NoNewPrivileges=yes
PrivateTmp=yes
PrivateUsers=yes
ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
RestrictNamespaces=yes
RestrictRealtime=yes
SystemCallFilter=~@clock @debug @module @mount @obsolete @privileged @reboot @setuid @swap
ReadWritePaths=/var/airsonic

#PrivateDevices=yes

ProtectSystem=full

#ProtectHome=true

#MemoryDenyWriteExecute=yes

[Install]
WantedBy=multi-user.target`

## Additional notes

I have deleted the db files to start fresh, all files in /var/airsonic belong to airsonic.  My airsonic used to work ok until recently.  I have had it on airsonic advanced for a month or so now but it failed when I was trying use the lastest war file at the time.

**Comment by Iamnome** [comment]
Ok, so I removed the sandboxing and everything is back to normal  Basically commented out everything below Group=airsonic down to [Install].  It worked with those options before so I guess something might have changed in systemd or my base OS?

**Comment by randomnicode** [comment]
Hard to say. There were a few faulty aa war releases in the middle also.

Glad to see it's working now.
