### ISSUE TITLE
Wrong folder name

### ISSUE THREAD

**Issue by cascooscuro** [airsonic-advanced/airsonic-advanced#767]
## Problem description

Folders whose name  contains dots are incorrectly displayed.

For example the folder "A.Armada" is detected as "A"
Another example: folder "U.S. Maple" is detected as "U.S"

### Steps to reproduce

clean installation with latest commit from master (https://github.com/airsonic-advanced/airsonic-advanced/commit/3e0444a53ae66cbd8c0dcd255998873a3ddcf567)

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20220130115440 – January 30, 2022 at 12:54:40 PM CET [Commit: 3e0444a53ae66cbd8c0dcd255998873a3ddcf567]
 * **Operating system**:  Linux Arch*
 * **Java version**: *Apache Tomcat/9.0.48, java 11.0.13, Linux *
 * **Proxy server**: *nginx
 * **Client**: *checked in web client an iSub iPhone app*
 * **Language**: en_US.UTF-8

## Additional notes

Have seen a few errors in the logs not sure if related: Gist included: https://gist.github.com/cascooscuro/42cd302757a2f7e98a7ba1edc4751fe6

**Comment by Yetangitu** [comment]
I posted a fix for this problem a while ago in the discussion around the relativepaths change. Since it was never picked up I'll submit a PR for it...
