### ISSUE TITLE
Installation from source

### ISSUE THREAD

**Issue by angelawong** [airsonic-advanced/airsonic-advanced#770]
I am trying to install from source and am not sure if I am doing the right thing:

```
$ wget https://github.com/airsonic-advanced/airsonic-advanced/archive/refs/tags/11.0.0-SNAPSHOT.20220130223117.zip
$ unzip 11.0.0-SNAPSHOT.20220130223117.zip
$ cd airsonic-advanced-11.0.0-SNAPSHOT.20220129204202
$ mvn clean package
```

Ran into this problem:
`[ERROR] Failed to execute goal on project airsonic-main: Could not resolve dependencies for project org.airsonic.player:airsonic-main:war:11.0.0-SNAPSHOT: Failed to collect dependencies at org.fourthline.cling:cling-core:jar:2.0.1: Failed to read artifact descriptor for org.fourthline.cling:cling-core:jar:2.0.1: Could not transfer artifact org.fourthline.cling:cling-core:pom:2.0.1 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [4thline-repo (http://4thline.org/m2, default, releases)] -> `

I tried to follow (https://github.com/airsonic-advanced/airsonic-advanced/issues/607) but could not resolve the issue. 

How can I resolve this problem? Please advise.

Thanks so much!

## System information

 * **Airsonic version**:
 11.0.0-SNAPSHOT.20220130223117
 * **Operating system**: 
No LSB modules are available.
Distributor ID:	Debian
Description: Debian GNU/Linux 11 (bullseye)
Release: 11
Codename: bullseye

 * **Java version**: 
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.13+8-post-Debian-1deb11u1, mixed mode, sharing)

**Comment by 4oo4** [comment]
I think you need to tell Maven to use the settings.xml file, to allow it to download that from an insecure (non-HTTPS) resource: https://stackoverflow.com/a/67835542

I also build mine from source for fun, this is what I've been using:
`mvn --settings=./.mvn/settings.xml -DskipTests -Dcheckstyle.skip=true clean package`

**Comment by randomnicode** [comment]
Updated [CONTRIBUTING.md](https://github.com/airsonic-advanced/airsonic-advanced/blob/master/CONTRIBUTING.md) file to reflect this reality.

**Comment by angelawong** [comment]
@4oo4 Thank you so much.

Based on your suggestions, I went to /opt/maven/conf/settings.xml and commented this section out:
```
    <!--mirror>
      <id>maven-default-http-blocker</id>
      <mirrorOf>external:http:*</mirrorOf>
      <name>Pseudo repository to mirror external repositories initially using HTTP.</name>
      <url>http://0.0.0.0/</url>
      <blocked>true</blocked>
    </mirror-->
```

It the above what you did?

I then ran:
`mvn --settings=./.mvn/settings.xml -DskipTests -Dcheckstyle.skip=true clean package`

Error message:
```
[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:
create-metadata (default) on project airsonic-main: 
Execution default of goal org.codehaus.mojo:buildnumber-maven-plugin:
1.4:create-metadata failed.: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: 
Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:
1.4:create-metadata (default) on project airsonic-main: 
Execution default of goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create-metadata failed.
```

What am I doing wrong? Please advise. Thanks so much!

**Comment by angelawong** [comment]
@randomnicode why is this issue closed? I am still having issues with it. Please advise.

**Comment by angelawong** [comment]
@randomnicode could you please open this ticket back up. I have not asked that the ticket be closed. Thanks so much!'

**Comment by 4oo4** [comment]
@angelawong You shouldn't have to edit settings.xml, that already has the necessary config to download the insecure dependencies, I believe. Just pointing maven to that should be enough. You should read up more on maven and then ask IRC or the subreddit for further help.

**Comment by randomnicode** [comment]
@angelawong 

- don't modify any files. reset `/opt/maven/conf/settings.xml` to the way it was
- the airsonic-advanced repo you cloned or wgetted already comes with a `.mvn/settings.xml` file
- simply cd into the airsonic root, and run ` mvn --settings=./.mvn/settings.xml -DskipTests -Dcheckstyle.skip=true clean package` instead of `mvn clean package`

Should look something like this:
```
$ wget https://github.com/airsonic-advanced/airsonic-advanced/archive/refs/tags/11.0.0-SNAPSHOT.20220130223117.zip
$ unzip 11.0.0-SNAPSHOT.20220130223117.zip
$ cd airsonic-advanced-11.0.0-SNAPSHOT.20220129204202
$ mvn --settings=./.mvn/settings.xml -DskipTests -Dcheckstyle.skip=true clean package
```

**Comment by angelawong** [comment]
Thank you @4oo4 and @randomnicode. Based on your instructions, this is what I did with the latest release:

```
~$ wget https://github.com/airsonic-advanced/airsonic-advanced/archive/refs/tags/11.0.0-SNAPSHOT.20220131041432.zip
~$ unzip 11.0.0-SNAPSHOT.20220131041432.zip
~$ cd airsonic-advanced-11.0.0-SNAPSHOT.20220131041432/
~/airsonic-advanced-11.0.0-SNAPSHOT.20220131041432$ 
mvn --settings=./.mvn/settings.xml -DskipTests -Dcheckstyle.skip=true clean package
```

This is what I got at the end of the process:
```
[INFO] Reactor Summary for Airsonic 11.0.0-SNAPSHOT:
[INFO] 
[INFO] Airsonic ........................................... SUCCESS [  0.945 s]
[INFO] Subsonic REST API .................................. SUCCESS [  6.546 s]
[INFO] Sonos API .......................................... SUCCESS [  7.511 s]
[INFO] Airsonic Main ...................................... FAILURE [  5.448 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.089 s
[INFO] Finished at: 2022-01-31T10:47:20-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:
create-metadata (default) on project airsonic-main: 
Execution default of goal org.codehaus.mojo:buildnumber-maven-plugin:
1.4:create-metadata failed.: NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :airsonic-main
```

Please advise. Any help would be most appreciated. Thanks so much.

**Comment by randomnicode** [comment]
Your issue is likely related to the fact that you don't have git installed and it is erroring out when it doesn't find an scm.

You can modify airsonic-main/pom.xml and add this line to get away with it, but not sure if you'll run into more issues.
```
<revisionOnScmFailure>UNKNOWN</revisionOnScmFailure>
```

**Comment by angelawong** [comment]
@randomnicode I do have git
```
$ git --version
git version 2.30.2

$ mvn --version
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /opt/maven
Java version: 11.0.13, vendor: Debian, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.10.0-9-amd64", arch: "amd64", family: "unix"

$ java --version
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.13+8-post-Debian-1deb11u1, mixed mode, sharing)
```

/etc/profile.d/maven.sh:
```
export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
export M2_HOME=/opt/maven
export PATH=${M2_HOME}/bin:${PATH}
```

I put <revisionOnScmFailure>UNKNOWN</revisionOnScmFailure> in airsonic-main/pom.xml
```
            <plugin>
              <groupId>org.codehaus.mojo</groupId>
              <artifactId>buildnumber-maven-plugin</artifactId>
              <executions>
                <execution>
                  <phase>generate-resources</phase>
                  <goals>
                    <goal>create-metadata</goal>
                  </goals>
                </execution>
              </executions>
              <configuration>
                <revisionOnScmFailure>UNKNOWN</revisionOnScmFailure>
                <timezone>UTC</timezone>
                <timestampFormat>yyyyMMddHHmmss</timestampFormat>
                <attach>true</attach>
                <!--make it available for jar/war classpath resource -->
                <addOutputDirectoryToResources>true</addOutputDirectoryToResources>
              </configuration>
            </plugin>
```

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:3.1.0:clean (default-clean) on project subsonic-rest-api: Failed to clean project: Failed to delete /home/awong/airsonic-advanced-11.0.0-SNAPSHOT.20220131041432/subsonic-rest-api/target/classes/subsonic-rest-api.xsd -> [Help 1]`

**Comment by randomnicode** [comment]
> Failed to delete /home/awong/airsonic-advanced-11.0.0-SNAPSHOT.20220131041432/subsonic-rest-api/target/classes/subsonic-rest-api.xsd

this is a filesystem issue, you likely have this directory or file open somewhere. see if you can manually delete it.

>  I do have git

Not in the source you downloaded, you won't see a .git folder because you grabbed a snapshot.
`$ wget https://github.com/airsonic-advanced/airsonic-advanced/archive/refs/tags/11.0.0-SNAPSHOT.20220130223117.zip`

try cloning the repo via git. Regardless, you've got the UNKNOWN fix in there, so this is a moot point.

**Comment by angelawong** [comment]
@randomnicode Thank you! It went a bit further when I did a git clone. Here is what I did:
```
$ git clone https://github.com/airsonic-advanced/airsonic-advanced.git
$ cd airsonic-advanced
$ mvn --settings=./.mvn/settings.xml -DskipTests -Dcheckstyle.skip=true clean package
```
This time around, it created an _airsonic-advanced/airsonic-main/target_ folder with the following in it:
```
airsonic
antrun
classes
generated
generated-sources
generated-test-sources
maven-archiver
maven-status
pmd.xml
site
test-classes
```

I just don't see the airsonic.war file:

**Errors:**
```
[INFO] --- maven-pmd-plugin:3.13.0:pmd (pmd) @ airsonic-main ---
[WARNING] There are 2 PMD processing errors:
[WARNING] /home/awong/airsonic-advanced/airsonic-main/src/main/webapp/WEB-INF/jsp/credentialsSettings.jsp: PMDException: 
Error while parsing /home/awong/airsonic-advanced/airsonic-main/src/main/
webapp/WEB-INF/jsp/credentialsSettings.jsp

/home/awong/airsonic-advanced/airsonic-main/src/main/webapp/WEB-INF/jsp/sonosSettings.jsp: 
PMDException: 
Error while parsing /home/awong/airsonic-advanced/airsonic-main/src/main/webapp/WEB-INF/jsp/sonosSettings.jsp
```


```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Airsonic 11.0.0-SNAPSHOT:
[INFO] 
[INFO] Airsonic ........................................... SUCCESS [  0.877 s]
[INFO] Subsonic REST API .................................. SUCCESS [  6.397 s]
[INFO] Sonos API .......................................... SUCCESS [  7.666 s]
[INFO] Airsonic Main ...................................... FAILURE [ 58.281 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:13 min
[INFO] Finished at: 2022-02-04T00:32:12-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:3.3.1:war (default-war)
on project airsonic-main: Error assembling WAR: Problem creating war:
Execution exception: Java heap space -> [Help 1]
```

Please advise.

Thanks so much,
Angela

**Comment by randomnicode** [comment]
> Execution exception: Java heap space -> [Help 1]

You need more memory. Please read a maven tutorial about how to use maven, specifically to allocate more memory. Google your issue.
E.g. 
https://stackoverflow.com/questions/12498738/maven-out-of-memory-build-failure
https://stackoverflow.com/questions/42505638/maven-failing-to-assemble-war-java-heap-space-issue-stanford-core-nlp

**Comment by angelawong** [comment]
Thanks @randomnicode for your help. I am really new at Maven so I am learning a lot from you at the moment. Through some research, this was recommended to increase memory. I hope I am doing it correctly. After doing so, I rebooted my server:
`$ java -XX:+PrintFlagsFinal -Xms1024m -Xmx2048m -Xss1024k -XX:PermSize=128m -XX:MaxPermSize=256m -version | grep -iE 'HeapSize|PermSize|ThreadStackSize'`

I am still getting the same error:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:3.3.1:war (default-war) on project airsonic-main: Error assembling WAR: Problem creating war: Execution exception: Java heap space -> [Help 1]`

What is the recommended Maven memory that is needed to build the Airsonic Advanced .war file? Please advise.

Thanks so much.

**Comment by randomnicode** [comment]
>  $ java -XX:+PrintFlagsFinal -Xms1024m -Xmx2048m -Xss1024k -XX:PermSize=128m -XX:MaxPermSize=256m -version | grep -iE 'HeapSize|PermSize|ThreadStackSize'

this isn't doing anything and it's not the correct way to increase maven memory.

> What is the recommended Maven memory that is needed to build the Airsonic Advanced .war file? Please advise.

We've never run into a memory issue while building

**Comment by angelawong** [comment]
@randomnicode if what I did was not the correct way to increase memory, what would be the correct way in doing so? This was where I got my instructions from: https://mkyong.com/java/find-out-your-java-heap-memory-size/

**Comment by 4oo4** [comment]
@angelawong Not sure if this helps, when I'm building mine I'm using [this](https://hub.docker.com/layers/csanchez/maven/3.8-adoptopenjdk-14/images/sha256-ff311059ef50a53b9a2ebec16f2e1edb02a6b89c2c7ecfe0f0fc4496055bbe05?context=explore) docker image (though there's probably a more up to date one I should switch to), this is what I get for the memory settings:

```
root@3f20bcfef5ab:/opt/java# java -XX:+PrintFlagsFinal -version | grep -iE 'HeapSize|PermSize|ThreadStackSize'
     intx CompilerThreadStackSize                  = 1024                                   {pd product} {default}
   size_t ErgoHeapSizeLimit                        = 0                                         {product} {default}
   size_t HeapSizePerGCThread                      = 43620760                                  {product} {default}
   size_t InitialHeapSize                          = 528482304                                 {product} {ergonomic}
   size_t LargePageHeapSizeThreshold               = 134217728                                 {product} {default}
   size_t MaxHeapSize                              = 8436842496                                {product} {ergonomic}
   size_t MinHeapSize                              = 8388608                                   {product} {ergonomic}
    uintx NonNMethodCodeHeapSize                   = 5839372                                {pd product} {ergonomic}
    uintx NonProfiledCodeHeapSize                  = 122909434                              {pd product} {ergonomic}
    uintx ProfiledCodeHeapSize                     = 122909434                              {pd product} {ergonomic}
   size_t SoftMaxHeapSize                          = 8436842496                             {manageable} {ergonomic}
     intx ThreadStackSize                          = 1024                                   {pd product} {default}
     intx VMThreadStackSize                        = 1024                                   {pd product} {default}
```

Also how much physical memory are you working with?

**Comment by randomnicode** [comment]
> if what I did was not the correct way to increase memory, what would be the correct way in doing so? This was where I got my instructions from: https://mkyong.com/java/find-out-your-java-heap-memory-size/

these instructions only tell you how to find your memory size. Not how to increase it.

Usually increasing memory available to maven involves modifying MAVEN_OPTS env variable and running maven in that environment. The specifics of this is beyond the realm of this avenue, and why we suggested going through a maven tutorial. Googling 'increase maven memory' will give plenty of hits.

Here are the release notes from the Maven 3.3.1 release, that say some on the matter: https://maven.apache.org/docs/3.3.1/release-notes.html
```
Starting with this release you can define JVM configuration via ${maven.projectBasedir}/.mvn/jvm.config file which means you can define the options for your build on a per project base. This file will become part of your project and will be checked in along with your project. So no need anymore for MAVEN_OPTS, .mavenrc files. So for example if you put the following JVM options into the ${maven.projectBasedir}/.mvn/jvm.config file

-Xmx2048m -Xms1024m -XX:MaxPermSize=512m -Djava.awt.headless=true

you don't need to remember of using this options in MAVEN_OPTS or switching between different configurations.
```

maybe create a jvm.config file in airsonic/.mvn and add these options in there.

**Comment by angelawong** [comment]
@randomnicode, thanks so much. I guess the reason I am doing this may be a round about way of trying to install it like I would Subsonic. I want to be able to make changes to the jsp files if I needed. Installing it via .war file does not allow me to change those files on the fly. That is why I am trying to install the application from source. If there is another way to install the application like I could with Subsonic, that would be great. I am not a Java programmer which is why this has been such a complicated process for me. With Subsonic it was just $ sudo dpkg -i subsonic-x.x.deb.  Once I got it installed, I could easily make changes within the app. Is there anything like this for airsonic-advanced?

**Comment by randomnicode** [comment]
Hmm, you could probably run airsonic in development mode which would make sure that the jsps get recompiled at every request.

you need to add the `airsonic.development` flag to the jvm system properties (something like `java -Dairsonic.development=true ...`). The flag is used here:

https://github.com/airsonic-advanced/airsonic-advanced/blob/c12511ea96d25dfc598a65e1a5dce8bcfb1433dd/airsonic-main/src/main/java/org/airsonic/player/TomcatApplication.java#L20-L42

Note that you're still running the war though.
You can unpack it and run it, which is what is done in the docker folder in an effort to speed up.
Take a look at the [Dockerfile](https://github.com/airsonic-advanced/airsonic-advanced/blob/master/install/docker/Dockerfile) to see the war being unpacked and [run.sh](https://github.com/airsonic-advanced/airsonic-advanced/blob/master/install/docker/run.sh) to see the unpacked run commands.

**Comment by angelawong** [comment]
@randomnicode, I increased the RAM on my server and it did the trick. I only had 1GB and was told that I needed at least 2GB to run Maven. Once I increased it, it worked like a charm. Thank you so much for all your help! I really appreciate it!
