### ISSUE TITLE
Duplicated podcasts and downloading very slow

### ISSUE THREAD

**Issue by Iamnome** [airsonic-advanced/airsonic-advanced#774]
## Problem description

Despite the previous fix, and starting my podcasts database from scratch, I still have multiple copies of each file.

Also the time to download and process seems to be quite long, I have a reasonable fibre link.

### Steps to reproduce

Add a podcast feed and wait for duplicates to appear.

Test retrieving a podcast using wget, and it downloads in 15s, however Airsonic seems to take much longer.  Currently not yet completed the first podcast feed after nearly 24 hours, although the duplicates aren't helping.

Podcast feed currently downloading/tested - https://rss.acast.com/redhanded

wget output - 

Connecting to dm4p36fbs3hl0.cloudfront.net (dm4p36fbs3hl0.cloudfront.net)|52.84.93.74|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 83906642 (80M) [audio/mpeg]
Saving to: ‘8019453.mp3’

8019453.mp3                                     100%[=====================================================================================================>]  80.02M  5.62MB/s    in 15s     

2022-01-31 07:37:09 (5.51 MB/s) - ‘8019453.mp3’ saved [83906642/83906642]

## System information

Airsonic = 11.0.0-SNAPSHOT.20220129040247
OS = Ubuntu server 20.04.3

**Comment by Iamnome** [comment]
It hasn't even finished this feed yet after over 24 hours, so I have no idea how it will perform, though historically it has been the same.

You say 548, Airsonic says 450 episodes in the GUI, I currently have this as a file count

```
root@music:/var/media/podcasts# find ./RedHanded -type f | wc -l
1092
root@music:/var/media/podcasts# 
```

I've tried another feed http://lizardpeoplepodcast.libsyn.com/rss with wget to get the first episode.

```
root@music:/var/media/podcasts# wget https://traffic.libsyn.com/secure/lizardpeoplepodcast/01.28.22_ele_mixdown.mp3
--2022-01-31 15:42:47--  https://traffic.libsyn.com/secure/lizardpeoplepodcast/01.28.22_ele_mixdown.mp3
Resolving traffic.libsyn.com (traffic.libsyn.com)... 204.16.246.216
Connecting to traffic.libsyn.com (traffic.libsyn.com)|204.16.246.216|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://hwcdn.libsyn.com/p/6/e/5/6e5f587f6941e122/01.28.22_ele_mixdown.mp3?c_id=120215405&cs_id=120215405&expiration=1643649786&hwt=5bb29f401c3d52ec554e7bf77ba0f2ae [following]
--2022-01-31 15:42:48--  https://hwcdn.libsyn.com/p/6/e/5/6e5f587f6941e122/01.28.22_ele_mixdown.mp3?c_id=120215405&cs_id=120215405&expiration=1643649786&hwt=5bb29f401c3d52ec554e7bf77ba0f2ae
Resolving hwcdn.libsyn.com (hwcdn.libsyn.com)... 205.185.216.42, 205.185.216.10
Connecting to hwcdn.libsyn.com (hwcdn.libsyn.com)|205.185.216.42|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 108609584 (104M) [audio/mpeg]
Saving to: ‘01.28.22_ele_mixdown.mp3’

01.28.22_ele_mixdown.mp3                        100%[=====================================================================================================>] 103.58M  5.86MB/s    in 18s     

2022-01-31 15:43:07 (5.67 MB/s) - ‘01.28.22_ele_mixdown.mp3’ saved [108609584/108609584]
```

Here is a quick snapshot of my incoming network traffic over about a two minute period using nload.  There is some outgoing because I use an NFS share hosted on the same physical machine but it won't past in.

```
Device enp0s3 [10.0.2.40] (1/2):

Incoming:

Curr: 1.34 MBit/s
Avg: 4.35 MBit/s
Min: 867.37 kBit/s
Max: 16.57 MBit/s
Ttl: 51.95 GByte
```

**Comment by Yetangitu** [comment]
I means to try by adding that feed to airsonic to see how it behaves. It is clear your connection is fast enough, the bottleneck lies elsewhere.

Does the airsonic log show anything (`airsonic.log` in the airsonic root directory) interesting? It tells when it starts to download an episode...

```
2022-01-29 23:24:25.305  INFO --- o.a.p.service.PodcastService             : Starting to download Podcast from https://feeds.soundcloud.com/stream/538878990-aronflam-del-54-dagen-efter-det-har-ar-en-svensk-tiger.mp3
```
...and when it has downloaded it...
```
2022-01-29 23:24:34.436  INFO --- o.a.p.service.PodcastService             : Downloaded 117468032 bytes from Podcast https://feeds.soundcloud.com/stream/538878990-aronflam-del-54-dagen-efter-det-har-ar-en-svensk-tiger.mp3
```
The difference - in this case ~9 seconds - is the download time. Check for those multiple downloads, do they have the same size? Maybe some of the downloads stalled, causing the download to be retried the next time?

**Comment by Iamnome** [comment]
There are plenty of logs, I used pastebin for a small snapshot from overnight https://pastebin.com/28Yuy5ce

Also the directory listing does show some size mismatches but what about the ones that match that are duplicated? https://pastebin.com/Hkrk3KUC

**Comment by Yetangitu** [comment]
What the logs show is first the presence of the annoying bug where it tries to get metadata from a file which has just started downloading, I'll look into that one of these hours because the log spam is irritating. It should, however, not cause the double/triple downloads as far as I can see given that I see the same log spam without double (let alone triple) downloads. I notice it starts the second and third download before the first one has been reported back as finished:

```
2022-01-31 00:01:51.419  INFO --- o.a.p.service.PodcastService             : Starting to download Podcast from https://pdst.fm/e/chtbl.com/track/4E942/audioboom.com/posts/7916563.mp3?modified=1627919160&source=rss&stitched=1
...
2022-01-31 00:03:05.335  INFO --- o.a.p.service.PodcastService             : Starting to download Podcast from https://pdst.fm/e/chtbl.com/track/4E942/audioboom.com/posts/7916563.mp3?modified=1627919160&source=rss&stitched=1
...
2022-01-31 00:03:23.020  INFO --- o.a.p.service.PodcastService             : Starting to download Podcast from https://pdst.fm/e/chtbl.com/track/4E942/audioboom.com/posts/7916563.mp3?modified=1627919160&source=rss&stitched=1
```
There is no discernable pattern in the interval between the download attempts - 74 seconds between attempt 1 and 2, ~18 seconds between 2 and 3. Maybe the many (4 in total) redirects between the media link in the RSS feed and the final download url lead it astray, it is worth looking into that. Does the "well-behaved" podcast redirect more than once from the content link to the download url?

I'll add that misbehaving feed to my test installation to see what happens.

**Comment by Iamnome** [comment]
Ok, I'll keep an eye on the current one downloading and report back.

I have it set to download all and keep all.  It was set to check every hour, which I didn't realise I hadn't changed, so I've now made that every day.

**Comment by Yetangitu** [comment]
While I could not duplicate the slow downloads - it downloaded the whole series in less than 10 minutes - I could get it to start downloading duplicates by clicking the _Check for new episodes_ link while it was still downloading the previous batch. This led to it downloading files which were marked as "completed" in the database. Clearly something is amiss here, I'll look into it one of these days.

**Comment by Iamnome** [comment]
You must be on a quick link to do that.  Gb fibre?

Ok, well I don't remember doing that, I'll see how the current one goes.  Thanks for taking a look.

**Comment by Yetangitu** [comment]
I just checked, this problem occurs when you manually click _Check for new episodes_  while such a check is already running. I got it to download 4 copies for the same file by setting it to download the last 10 episodes and clicking away on the refresh link. A simple lock should be sufficient to solve this problem (as if locks are ever simple, but...).

Yes, Gb fibre in the Swedish countryside, quite an upgrade from the "best effort" ADSL we had before that (years ago now).

**Comment by Iamnome** [comment]
Ok, maybe I did click it, but I don't remember doing it.  I'm sure lock files bring their own complications.

I live in the Welsh countryside up a hill.  We're stuck with 4G mobile broadband, which is ok most of the time, until they get the fibre the last half mile to us.  Apparently we'll be on Gb then.

ADSL would be about 2Mb here.

I keep my servers at our office as that's on fibre but only an 80M link.

Thanks again for having a look at this for me, even if it seems it might be my own making.

**Comment by Yetangitu** [comment]
I'm pretty sure you won't be the only one to click "refresh" while a refresh happens to be active so this problem needs to be fixed, maybe by adding another state (`DOWNLOADING`) to the `STATUS` column since I expect this to be a race condition between refresh jobs - they read the `STATUS` column for an episode, notice it says `SKIPPED` and start a download job for it, unaware of the fact that other refresh jobs did the same not long ago.

Wales, lovely country, a friend of mine who works at the university of Cumbria in Carlisle lives there which gives me reason to spend some time there now and again - occasionally coinciding with the Rail Ale festival which is of course purely coincidental. ADSL here was around the 2 Mbit mark as well, sold as "best effort". The change between that (with the accompanying mayhem when a thunderstorm rolled by, I had a stack of 4 modems which I kept on fixing between storms) and the fibre hookup was unreal but very much welcome.

**Comment by Yetangitu** [comment]
@Iamnome if you have a build environment handy I suggest you make a build with this PR applied to test whether it works for you. If you don't I can send a link to a WAR with these changes applied.
