### ISSUE TITLE
search in web interface is not working

### ISSUE THREAD

**Issue by cascooscuro** [airsonic-advanced/airsonic-advanced#775]
## Problem description

when you search for an artist or album, some results appear. If you try to click in any of those results this is what it shows:

![image](https://user-images.githubusercontent.com/5746813/151820051-c765c955-317f-44c6-b830-be9d38eca987.png)

### Steps to reproduce

*Using latest release with a clean installation after first media scan*

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20220131084502 – January 31, 2022 at 9:45:02 AM CET https://github.com/airsonic-advanced/airsonic-advanced/commit/ddc47dd586d067555937f59647cf0702f918e19e*
 * **Operating system**: *Linux Arch
    * **Java version**: *Apache Tomcat/9.0.48, java 11.0.13, Linux (1.47 GB / 2.30 GB)*
 * **Proxy server**: *Nginx
 * **Client**: *Airsonic web, Firefox
 * **Language**:LANG=en_US.UTF-8

## Additional notes
~~Not sure if related but albums with special characters (comma, apostrophe... like in "Drive:" or "Ocean's" are not discoverable. I opened an issue about it: *https://github.com/airsonic-advanced/airsonic-advanced/issues/644~~

**Comment by mamema** [comment]
search "Not found" issue also on my side here

**Comment by khers** [comment]
I see this as well.

Search from DSub is working normally but the same search on the web interface gives this result.

**Comment by nowheretobefound** [comment]
Same issue here.

**Comment by nowheretobefound** [comment]
Nothing in the server log.

This in the browser log when clicking artist :

`>>> SEND
destination:/app/mediafile/directory/get
content-length:32

{"ids":[],"paths":["Metallica"]}� stomp-4.0.8.min.js:9:2502
<<< MESSAGE
destination:/user/queue/mediafile/directory/get
content-type:application/json
subscription:sub-32
message-id:vivj4e42-7
content-length:26

{"contentType":"notFound"}� stomp-4.0.8.min.js:9:2502
>>> PING stomp-4.0.8.min.js:9:2502
>>> PING stomp-4.0.8.min.js:9:2502
`
Html for clickable artist :
`<a href="/airsonic/main.view?path=Metallica">Metallica</a>`


An artist lick that works (from the treeview ) :
`<a target="main" href="main.view?id=14598">Metallica</a>`
