### ISSUE TITLE
Latest Dockerhub container not releasing, or not detecting released changelog lock

### ISSUE THREAD

**Issue by monik3r** [airsonic-advanced/airsonic-advanced#785]
## Problem description

I'm opening this in a new thread as it didn't pertain to issue #782.  I recently pulled airsonicadvanced/airsonic-advanced:latest	and re-created the container (stopping image: sha256:a430e133de93142d7c83e6df568cc04b75ba72a628b89a660d7f4cbdd67ea0e9). When I attempt to start the new container I get the following output:

```
           _                       _
     /\   (_)                     (_)
    /  \   _ _ __  ___  ___  _ __  _  ___
   / /\ \ | | '__|/ __|/ _ \| '_ \| |/ __|
  / ____ \| | |   \__ \ (_) | | | | | (__
 /_/    \_\_|_|   |___/\___/|_| |_|_|\___|





2022-02-03 03:27:30.474  INFO --- org.airsonic.player.Application          : Starting Application using Java 14.0.2 on c586c0cb9abf with PID 1 (/app/WEB-INF/classes started by au in /var)
2022-02-03 03:27:30.477  INFO --- org.airsonic.player.Application          : No active profile set, falling back to default profiles: default
2022-02-03 03:27:35.084  INFO --- l.database.core.HsqlDatabase             : Set default schema name to PUBLIC
2022-02-03 03:27:35.241  INFO --- l.l.StandardLockService                  : Successfully acquired change log lock
2022-02-03 03:27:36.073  INFO --- l.c.StandardChangeLogHistoryService      : Reading from PUBLIC.DATABASECHANGELOG
2022-02-03 03:27:36.279  INFO --- l.l.StandardLockService                  : Successfully released change log lock
2022-02-03 03:27:36.295  INFO --- l.l.StandardLockService                  : Waiting for changelog lock....
2022-02-03 03:27:46.305  INFO --- l.l.StandardLockService                  : Waiting for changelog lock....
```

This leads me to believe that the standardlockservice thought it released the lock but may have not? 

### Steps to reproduce

Using a docker-compose file such as:
```
services:
  airsonic:
    image: airsonicadvanced/airsonic-advanced
    container_name: airsonic
    volumes:
      - "./data:/var/airsonic"
      - "./music:/var/music"
      - "./playlists:/var/playlists"
      - "./podcasts:/var/podcasts"
    restart: unless-stopped
```

Have version: 
sha256:a430e133de93142d7c83e6df568cc04b75ba72a628b89a660d7f4cbdd67ea0e9 working
`docker-compose pull && docker-compose up -d`

## System information

I am using the docker container with sha256:ebbe2b1048fb341faeed7baff0e77d2d1cd1ec62960087e81940bee2898c3896.  With docker and docker-compose.

## Additional notes

The previous version was working, I believe it was from January 12th. I have tried downgrading after backing up the db, and that did not work. 

I will try looking through possible solutions such as http://pmdzsite.online.fr/index.php?article40/unlock-standalone-airsonic-database. I do not have two instances running currently (or at any time).

Great project, and hopefully I'll be able to start the server again!

**Comment by randomnicode** [comment]
this is likely a db issue, not a container issue. somehow the container must've been shut down during migrations at startup, leaving an unclean lock row.

you need to delete the locking row in the databasechangeloglock table.

you can either open the db yourself with a tool like dbeaver and do that, or post your db here and one of us will do it for you. alternatively you can start anew by deleting the db folder.

**Comment by monik3r** [comment]
Thanks, that makes sense. Here is my db (please let me know if there is a better extension than .tar.gz): https://drive.google.com/file/d/10Rz_Ls6tV5rTcvNh1nipd2vLXNu66OGq/view?usp=sharing

**Comment by monik3r** [comment]
Hi,

I believe I fixed this locally by editing airsonic.script by hand. Before inserting data into DATABASECHANGELOG there was the following line:
`INSERT INTO DATABASECHANGELOGLOCK VALUES(1,TRUE,'2022-02-01 20:24:19.364000','244138408cbf (172.27.0.4)')`

Removing this line and waiting allowed for the service to start. What is interesting is that the new container hostname is not 244138408cbf and the ip is no longer the same (docker-compose re-created the network). Is this database behavior normal for the db in use? It's pretty common for containers to get a new IP when re-created, especially in larger compose files.

**Comment by randomnicode** [comment]
the lock row is deleted right after migrations finish so it's not particularly long-lasting. it's there to prevent two simultaneous migrations from happening at the same time.
a container executing a migration on a db won't have a row in the db for very long (only during startup phase). we would say the behavior is normal and not particularly relevant.

**Comment by randomnicode** [comment]
looks like this is resolved now. feel free to reopen if it isn't

**Comment by thfrei** [comment]
> Removing this line ` INSERT INTO DATABASECHANGELOGLOCK VALUES(1,TRUE,'2022-02-01 20:24:19.364000','244138408cbf (172.27.0.4)')` and waiting allowed for the service to start. 

Solved the problem for me too.

**Comment by Typhonragewind** [comment]
Sorry to reopen this, but I'm having the same issue after an install on a fresh VM (using the persisted data folders from before). To the best of my knowledge, Airsonic wasn't interrupted suddenly, but I could be wrong.
Additionally, monik3r fix did not work for me.

Could i trouble you for some assistance, please ?

**Comment by thfrei** [comment]
@Typhonragewind Do you have any additional error output or just the same message: `Waiting foro changelog lock...`?

**Comment by Typhonragewind** [comment]
> @Typhonragewind Do you have any additional error output or just the same message: `Waiting foro changelog lock...`?

Just the same message. That line in airsonic.script is as follows, without any container details: INSERT INTO DATABASECHANGELOGLOCK VALUES(1,FALSE,NULL,NULL)

**Comment by thfrei** [comment]
Well if you have an existing installation, maybe you can try to add a line that deletes any logs in this table? I am not sure how safe that is, so do this with caution. Something like delete or truncate?

I figure, the startup somehow checks the table to see if there are any logs. Maybe you have some logs from previous (failed) migrations or errors?

Also, some link in the first issues mentions a `memory` table that could be created, so maybe you can delete more/multiple lines in the `airsonic.script` => http://pmdzsite.online.fr/index.php?article40/unlock-standalone-airsonic-database

**Comment by Typhonragewind** [comment]
> Well if you have an existing installation, maybe you can try to add a line that deletes any logs in this table? I am not sure how safe that is, so do this with caution. Something like delete or truncate?
I have no clue how to do this, since so far SQL is a mystery to me, but it is a nice idea!

>Also, some link in the first issues mentions a memory table that could be created, so maybe you can delete more/multiple lines in the airsonic.script => http://pmdzsite.online.fr/index.php?article40/unlock-standalone-airsonic-database
Already tried that one, no luck :(

**Comment by thfrei** [comment]
> I have no clue how to do this, since so far SQL is a mystery to me, but it is a nice idea!

Just one thing: 
* If you deleted the line: `INSERT INTO DATABASECHANGELOGLOCK VALUES(1,FALSE,NULL,NULL)` I think it is wrong, since that is the command to actually "release" the lock (in my opinion).
* You must only delete the line that starts with: `INSERT INTO DATABASECHANGELOGLOCK VALUES(1,TRUE....`

Can you please check this?


Note: The columns in the table are as follows:
```
CREATE MEMORY TABLE PUBLIC.DATABASECHANGELOGLOCK(
 ID INTEGER NOT NULL,
 LOCKED BOOLEAN NOT NULL,
 LOCKGRANTED TIMESTAMP,
 LOCKEDBY VARCHAR(255),
 CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY(ID)
)
```
So you see, the second value should be `FALSE` to indicate, that it is NOT locked.

**Comment by Typhonragewind** [comment]
> * You must only delete the line that starts with: `INSERT INTO DATABASECHANGELOGLOCK VALUES(1,TRUE....`

There is no entry like that in airsonic.script, just the other empty one. It is the file i should be checking, right ?

Thank you for your patience!

**Comment by Typhonragewind** [comment]
[thfrei](https://github.com/thfrei) I came into my senses and restored a backup instead of losing more time over this issue...i had temporarily forgotten about my backups xD

So it seems, that upon my new installation, I forgot about the migration, which took a fair bit of time (8mins) and rebooted the server several times shortly after activating the docker container...so yeah, my bad!

Thanks for the help though :)

**Comment by Abraka** [comment]
Same problem here. Update from 11.0.0-SNAPSHOT.20220110133315 to latest docker image result in crash and loop. Thx god I did have a backup from yesterday, otherwise I would lost all my playlist and starred :( .
