### ISSUE TITLE
Feature request: use HTTP header for external user authentication

### ISSUE THREAD

**Issue by courtarro** [airsonic-advanced/airsonic-advanced#803]
I have Airsonic Advanced set up behind an Apache reverse proxy. I am having Apache handle authentication before AA receives any traffic from the outside world. Since Apache is handling authentication, I would like to have AA defer to that authentication through something like an extra header of my choosing. I could use something like X-AIRSONIC-USER and pass along the username, then have AA trust that the user has been authenticated, then applying the appropriate authorization rules based on the normal user database within AA.

Is this possible? Basically it would bypass the need to manage any passwords or other Airsonic-specific credentials within AA.

**Comment by randomnicode** [comment]
> Is this possible? Basically it would bypass the need to manage any passwords or other Airsonic-specific credentials within AA.

No. Anyone would then just put a user name in the header and bypass all security?

**Comment by courtarro** [comment]
When the server is listening on an interface that only Apache can access, this is not a risk. Imagine a Docker container running AA that's sitting on a private Docker network with only Apache in another container. Apache can access AA and provide the necessary header.

I've read more about this approach, which I've seen used in other tools like RStudio ([see here](https://docs.rstudio.com/ide/server-pro/2021.09.0+351.pro6/authenticating_users/proxied_authentication.html)). However, I'm learning that there are some security gotchas with an approach like this, so I'm willing to withdraw my request.
