### ISSUE TITLE
Postgresql docker env parameters do not seem to work

### ISSUE THREAD

**Issue by matejdro** [airsonic-advanced/airsonic-advanced#817]
Just want to mention that using `spring_datasource_url` parameters from the https://hub.docker.com/r/airsonicadvanced/airsonic-advanced do not seem to work. After applying them, airsonic will still use embedded database.

Editing `airsonic.properties` as mentioned https://airsonic.github.io/docs/database/#postgresql does work though.

I guess something changed and documentation was not updated?

**Comment by randomnicode** [comment]
Nothing has overtly changed. In fact the CI/CD pipeline tests external dbs on the basis of those very parameters.

Here's a sample run from the last merge: https://github.com/airsonic-advanced/airsonic-advanced/runs/5172036499?check_suite_focus=true

**Comment by matejdro** [comment]
Huh then I guess I screwed up something when I tried that. It works now with the edited properties so I won't touch it. Thanks for answering.
