### ISSUE TITLE
UPnP duration string out of spec

### ISSUE THREAD

**Issue by stephen-fralich** [airsonic-advanced/airsonic-advanced#825]
## Problem description

Airsonic Advanced's UPnP duration string does not match the UPnP specification. This can break the duration display on UPnP clients. At least one I'm aware of. This was formatted to spec in Airsonic, but is no longer in Airsonic Advanced. Eight minutes, seventeen seconds, and 493 factional seconds was 0:08:17.0 whereas right now it is 8:17.493. Padding on the minutes is required and I think the leading : is required even if there are no hours, so :08:17.493 I think is the least you can provide. I can say Airsonic (classic) and Plex both opt for 0:08:17.0 and 0:08:17.000 respectively.

Here's the code reference in the upnp service: https://github.com/airsonic-advanced/airsonic-advanced/blob/b035842aa3a8aaad03f90513eefe555601548d7b/airsonic-main/src/main/java/org/airsonic/player/service/upnp/CustomContentDirectory.java#L85-L94

Which calls this public utility function: https://github.com/airsonic-advanced/airsonic-advanced/blob/b035842aa3a8aaad03f90513eefe555601548d7b/airsonic-main/src/main/java/org/airsonic/player/util/StringUtil.java#L179-L190

## Additional notes

Specification for the duration string (top of page 67): http://web.archive.org/web/20211120151046/http://upnp.org/specs/av/UPnP-av-ContentDirectory-v1-Service.pdf

Excerpt from the specification:
'duration' type: string use: optional
The 'duration' attribute identifies the duration of the playback of the resource, at normal speed.
The form of the duration string is:
H*:MM:SS.F*, or H*:MM:SS.F0/F1
where :
H* means any number of digits (including no digits) to indicate elapsed hours
MM means exactly 2 digits to indicate minutes (00 to 59)
SS means exactly 2 digits to indicate seconds (00 to 59)
F* means any number of digits (including no digits) to indicate fractions of seconds
F0/F1 means a fraction, with F0 and F1 at least one digit long, and F0 < F1
The string may be preceded by an optional + or – sign, and the decimal point itself
may be omitted if there are no fractional second digits.

Airsonic Advanced upnp Item:
```
<item id="3857" parentID="3830" restricted="1">
  <dc:title>Your Hand In Mine</dc:title>
  <upnp:class>object.item.audioItem.musicTrack</upnp:class>
  <upnp:album>The Earth Is Not a Cold Dead Place</upnp:album>
  <upnp:artist>Explosions in the Sky</upnp:artist>
  <upnp:originalTrackNumber>5</upnp:originalTrackNumber>
  <upnp:albumArtURI>http://192.168.1.138:8080/airsonic/ext/coverArt.view?id=3830&amp;size=300&amp;jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbm9ueW1vdXMiLCJwYXRoIjoiZXh0L2NvdmVyQXJ0LnZpZXc_aWQ9MzgzMCZzaXplPTMwMCIsImlzcyI6ImFpcnNvbmljIiwiZXhwIjoxNjQ1ODA0NjIzfQ.r63NF0XnrUx9xvKbA8Qk5fpK0W5zbCxrj25X5sm8pqA</upnp:albumArtURI>
  <dc:date>2003-01-01</dc:date>
  <dc:description/>
  <res duration="8:17.493" protocolInfo="http-get:*:audio/mpeg:*">http://192.168.1.138:8080/airsonic/ext/stream?id=3857&amp;player=10&amp;jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbm9ueW1vdXMiLCJwYXRoIjoiZXh0L3N0cmVhbT9pZD0zODU3JnBsYXllcj0xMCIsImlzcyI6ImFpcnNvbmljIiwiZXhwIjoxNjQ1ODA0NjIzfQ.009ba23XYaC_02DNb4WNsQRJzX7TjnLJdbrmpY5zXv8</res>
</item>
```

Airsonic upnp item:
```
<item id="2034" parentID="1986" restricted="1">
  <dc:title>Your Hand In Mine</dc:title>
  <upnp:class>object.item.audioItem.musicTrack</upnp:class>
  <upnp:album>The Earth Is Not a Cold Dead Place</upnp:album>
  <upnp:artist>Explosions in the Sky</upnp:artist>
  <upnp:originalTrackNumber>5</upnp:originalTrackNumber>
  <upnp:albumArtURI>http://192.168.1.138:8080/ext/coverArt.view?id=1986&amp;size=300&amp;jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiL2V4dC9jb3ZlckFydC52aWV3P2lkPTE5ODYmc2l6ZT0zMDAiLCJleHAiOjE2NDU4MzEzNTF9.ePawcbcEY3ngP9pzuYcRBrinhZ4WiEFZVVbim3IAaLI</upnp:albumArtURI>
  <dc:date>2003-01-01</dc:date>
  <dc:description/>
  <res duration="0:08:17.0" protocolInfo="http-get:*:audio/flac:*">http://192.168.1.138:8080/ext/stream?id=2034&amp;player=2&amp;jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiL2V4dC9zdHJlYW0_aWQ9MjAzNCZwbGF5ZXI9MiIsImV4cCI6MTY0NTgzMTM1MX0.K7Jf7dRoqqPCWQM2aX1IXho4po9mXveUb6q36u-xn88</res>
</item>
```

**Comment by randomnicode** [comment]
Did the issue resolve? May we close this?

**Comment by stephen-fralich** [comment]
This specific issue is resolved and you can close this. The fix I submitted did fix the duration string, but it did not fix the display of the duration on my device unfortunately. My device continues to show all tracks as 351909:41:29. Do you know of any additional ways track duration is provided to upnp clients or any suggestions as to what might be a next step in investigating? Thanks for any suggestions you might have.

**Comment by randomnicode** [comment]
Explain more?
