### ISSUE TITLE
MariaDB Database issue with recent image

### ISSUE THREAD

**Issue by juerb** [airsonic-advanced/airsonic-advanced#826]
## Problem description
I've updated the docker image two days ago and I've encountered an database exception "Foreign key constraint is incorrectly formed" which leads to a app crash.

### Steps to reproduce
Update from airsonicadvanced/airsonic-advanced:edge-11.0.0-SNAPSHOT.20220206161637 to airsonicadvanced/airsonic-advanced:latest on a MariaDB setup.

## System information

 * **Airsonic version**: *the version listed on the About page*
 * **Operating system**: Docker on Ubuntu 20.04
 * **Java version**: 14.0.2

[airsonic_20220220T080142Z.log](https://github.com/airsonic-advanced/airsonic-advanced/files/8103621/airsonic_20220220T080142Z.log)

**Comment by randomnicode** [comment]
on your MariaDB, run `SHOW ENGINE INNODB STATUS` and see the entry for LATEST FOREIGN KEY ERROR

What does it say?

**Comment by juerb** [comment]
> ------------------------  
> LATEST FOREIGN KEY ERROR  
> ------------------------  
> 2022-02-20 09:08:54 0x7f084804d700 Error in foreign key constraint of table `airsonic`.`media_file`:
> Alter  table `airsonic`.`media_file` with foreign key `mfi_mfo_id_fk` constraint failed. There is no index in the referenced table where the referenced columns appear as the first columns.------------

**Comment by randomnicode** [comment]
possible issues:
- character sets (or collations) are different between the two tables can you check? `media_file` and `music_folder`. Run `SHOW CREATE TABLE table1`
- the column types are different between the two. maybe signed or unsigned int difference. can you check? `media_file.folder_id` and `music_folder.id`
- the table engines are different (maybe one is InnoDB and other is MySAM). Can you check? `SHOW TABLE STATUS LIKE 'table_name';`
-

**Comment by juerb** [comment]
Seems to be fine, I've attached the no-data dump.

- both have  CHARSET=`utf8mb4` and Collation=`utf8mb4_general_ci`
- `media_file.folder_id` is `Int(11)` and `music_folder.id` is `int(11)`
- All have `InnoDB` as engine 

[airsonic_schema.sql.gz](https://github.com/airsonic-advanced/airsonic-advanced/files/8125740/airsonic_schema.sql.gz)

**Comment by randomnicode** [comment]
do you have any entries in media_file where folder_id = -1 ? delete those please?

**Comment by juerb** [comment]
Unfortunately there are no entries with folder_id = -1.
They all are folder_id=1 except one Entry title="Podcasts" folder_id=2.

**Comment by randomnicode** [comment]
and your music_folder has at least rows with id = 1 and id = 2?

**Comment by juerb** [comment]
correct, music_folder has two rows:
```
+----+---------------+----------+---------+----------------------------+---------+
| id | path          | name     | enabled | changed                    | type    |
+----+---------------+----------+---------+----------------------------+---------+
|  1 | /var/music    | Music    |        | 2020-09-23 20:11:14.000000 | MEDIA   |
|  2 | /var/podcasts | Podcasts |        | 2022-02-07 14:07:30.784698 | PODCAST |
+----+---------------+----------+---------+----------------------------+---------+
```

**Comment by randomnicode** [comment]
if you run the index manually, does it give the same error?

you're adding a foreign key between media_file.folder_id and music_folder.id named mfi_mfo_id_fk with on delete and on update cascading

**Comment by randomnicode** [comment]
you can probably migrate over the favorites/play counts and stuff with a bit of manual finagling
