### ISSUE TITLE
M4a files not being transcoded and not playing

### ISSUE THREAD

**Issue by L-m-b** [airsonic-advanced/airsonic-advanced#830]
## Problem description

updating and revising the issue, simply put my browsers cannot play m4a ALAC audio, but every other format works, and the transcoder is not working despite being in my path AND binaries being unpacked to the transcode folder.

### Steps to reproduce

*have an m4a file and attempt to play it on an airsonic server that doesn't detect ffmpeg*

## System information

Windows 64 bit, java 17, ryzen/amd cpu nvidia graphics.

**Comment by L-m-b** [comment]
Note: found out why it wasn't using the binaries, nowhere on any subsonic docs does it say to give it access to use the ffmpeg.exe by extracting the BIN folder to the transcode folder directly, but apparently that is the only way it works.... WHY.

**Comment by randomnicode** [comment]
we've changed the resolution such that it first looks at the transcode folder and then the world at large so long as the path has it, it should be able to find it.

**Comment by randomnicode** [comment]
> nowhere on any subsonic docs does it say to give it access to use the ffmpeg.exe by extracting the BIN folder to the transcode folder directly, but apparently that is the only way it works.... WHY.

says right in the transcode section of the settings; even where to install it

**Comment by L-m-b** [comment]
i clearly must have missed it i will have a look.

**Comment by L-m-b** [comment]
Aaah, no its close but between original docs of Airsonic and that page as well as tutorials i assumed the entire archive being unpacked into the folder should have been right. yet again it didn't specify it needed the Executables on the 1st folder rather than being in a Subfolder.
Thanks anyway, I'll give the new binary a crack.
