### ISSUE TITLE
Airsonic stops when tries to make a DB backup

### ISSUE THREAD

**Issue by Dikakus** [airsonic-advanced/airsonic-advanced#846]
## Problem description

Airsonic stops when tries to make a DB backup. No clues in the log.

### Steps to reproduce

1. Configure daily DB backup.
2. Start airsonic.
3. After some minutes, exit with status 31/SYS:

```
pi@raspberrypi:~ $ sudo systemctl status airsonic
● airsonic.service - Airsonic Media Server
     Loaded: loaded (/etc/systemd/system/airsonic.service; enabled; vendor preset: enabled)
     Active: failed (Result: signal) since Tue 2022-03-01 10:33:59 CET; 12min ago
    Process: 11642 ExecStartPre=/bin/sleep 30 (code=exited, status=0/SUCCESS)
    Process: 11683 ExecStart=/usr/bin/java $JAVA_OPTS -Dairsonic.home=${AIRSONIC_HOME} -Dserver.forward-headers-strategy=native -Dserver.servlet.context-pat>
   Main PID: 11683 (code=killed, signal=SYS)
        CPU: 10min 19.527s

mar 01 10:33:20 raspberrypi java[11683]: 2022-03-01 10:33:20.439  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: Pop/Jimmy Sommerville, Bron>
mar 01 10:33:20 raspberrypi java[11683]: 2022-03-01 10:33:20.440  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: New Age/E/Eri Sugai/2006 - >
mar 01 10:33:20 raspberrypi java[11683]: 2022-03-01 10:33:20.444  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: Pop-0 | EventType: CREATED >
mar 01 10:33:20 raspberrypi java[11683]: 2022-03-01 10:33:20.444  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: New Age/E/Eri Sugai/2000 - >
mar 01 10:33:51 raspberrypi java[11683]: 2022-03-01 10:33:51.158  INFO --- o.a.p.service.PodcastService             : Starting scheduled default Podcast ref>
mar 01 10:33:51 raspberrypi java[11683]: 2022-03-01 10:33:51.163  INFO --- o.a.p.service.PodcastService             : Completed scheduled default Podcast re>
mar 01 10:33:59 raspberrypi java[11683]: 2022-03-01 10:33:59.112  INFO --- o.a.p.service.DatabaseService            : Starting scheduled DB backup
mar 01 10:33:59 raspberrypi systemd[1]: airsonic.service: Main process exited, code=killed, status=31/SYS
mar 01 10:33:59 raspberrypi systemd[1]: airsonic.service: Failed with result 'signal'.
mar 01 10:33:59 raspberrypi systemd[1]: airsonic.service: Consumed 10min 19.527s CPU time.

```

4. Disabling DB backup (manually) and launching the backup with the button fails as well.

## System information

- Airsonic version: 11.0.0-SNAPSHOT.20220222093559 (2022-02-22)
- Operating system: Raspbian GNU/Linux bullseye, aarch64
- Java version: 11.0.14+9-post-Raspbian-1deb11u1
- Proxy server: None
- Client: Opera
- Language: Spanish

## Additional notes

![image](https://user-images.githubusercontent.com/14204887/156147073-2d9dd895-b464-41d2-aeaa-d628fc8b6d58.png)

**Comment by jobenvil** [comment]
@Dikakus maybe you wanna check the AA logfile inside conf/airsonic.log or journalctl -xeu airsonic.service.

**Comment by Dikakus** [comment]
Hi @jobenvil . I'm running the standalone version of AA, so I've lauched journalctl -xeu airsonic.service --since 10:33:20:

```
mar 01 10:33:20 raspberrypi java[11683]: 2022-03-01 10:33:20.444  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: Pop-0 | EventType: CREATED >
mar 01 10:33:20 raspberrypi java[11683]: 2022-03-01 10:33:20.444  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: New Age/E/Eri Sugai/2000 - >
mar 01 10:33:51 raspberrypi java[11683]: 2022-03-01 10:33:51.158  INFO --- o.a.p.service.PodcastService             : Starting scheduled default Podcast ref>
mar 01 10:33:51 raspberrypi java[11683]: 2022-03-01 10:33:51.163  INFO --- o.a.p.service.PodcastService             : Completed scheduled default Podcast re>
mar 01 10:33:59 raspberrypi java[11683]: 2022-03-01 10:33:59.112  INFO --- o.a.p.service.DatabaseService            : Starting scheduled DB backup
mar 01 10:33:59 raspberrypi systemd[1]: airsonic.service: Main process exited, code=killed, status=31/SYS
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ An ExecStart= process belonging to unit airsonic.service has exited.
░░
░░ The process' exit code is 'killed' and its exit status is 31.
mar 01 10:33:59 raspberrypi systemd[1]: airsonic.service: Failed with result 'signal'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit airsonic.service has entered the 'failed' state with result 'signal'.
mar 01 10:33:59 raspberrypi systemd[1]: airsonic.service: Consumed 10min 19.527s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit airsonic.service completed and consumed the indicated resources.

```

**Comment by B16WLL** [comment]
I had this crash issue when attempting a backup too. It's the reason I switched to using a proper database. 
Which uncovered another [issue](https://github.com/airsonic-advanced/airsonic-advanced/issues/871#issue-1179896751)!

**Comment by johnmurrayvi** [comment]
Also experiencing this with the embedded HSQL db.

**Comment by tovine** [comment]
Sorry for necroposting, but let me guess: you're using the systemd template service file?
I ran into the same issue today, and it turns out the security settings in that file are too restrictive and denies `chown` that's called as part of the backup process (for some reason).

I fixed it by making this change compared to the [airsonic.service template](https://raw.githubusercontent.com/airsonic/airsonic/master/contrib/airsonic.service):

```diff
-SystemCallFilter=~@clock @debug @module @mount @obsolete @privileged @reboot @setuid @swap
+SystemCallFilter=@basic-io @file-system @chown @network-io @sync @timer @signal @process @system-service
```

Short explanation: the existing `SystemCallFilter` blocks all the listed groups, including `@privileged`, which as it turns out also includes the `chown` syscall.
Instead of listing blocked syscall groups, I looked into what syscalls airsonic _actually_ needs and listed those (resulting in an even more restricted, but accurate and correct set).

**Comment by Dikakus** [comment]
Hi, @tovine. Don't worry. It's great to solve things even though they are a little bit old, although I dind't remberber this issue because I already planned my DB backups with external tools. As you said, I'm using the systemd template service file. 

It's important to say I switched to advanced-airsonic kagemomiji fork a few months ago, but I'm checking this issue again just in case, after your comment.

First, I've tried to do a manual DB backup (my current DB is the internal HSQLDB) to test the current behavior and the backup succeeded:

```
2024-03-20 11:26:05.876 DEBUG --- o.a.p.u.LegacyHsqlMigrationUtil          : Performing HSQLDB database backup...
2024-03-20 11:26:43.786  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database backed up to /var/airsonic/backups/db.backup.20240320112605
2024-03-20 11:26:43.786  INFO --- o.a.p.service.DatabaseService            : Backed up DB to location: /var/airsonic/backups/db.backup.20240320112605
```

Then, I've tried to do a DB Export, but some exceptions have been thrown, including that the destination folder cannot be created:

```
2024-03-20 11:28:14.968  INFO --- l.database.core.HsqlDatabase             : Set default schema name to PUBLIC
2024-03-20 11:28:15.075  INFO --- l.command.core.DiffCommandStep           : Diff command completed
2024-03-20 11:28:20.753  INFO --- l.d.o.changelog.DiffToChangeLog          : changeSets count: 25
2024-03-20 11:28:20.754  INFO --- l.d.o.changelog.DiffToChangeLog          : var/airsonic/backups/airsonic.exportDB.20240320112814/0.xml does not exist, crea
ting and adding 25 changesets.
2024-03-20 11:28:20.755  WARN --- liquibase.resource.PathResource          : Failed to create parent directories for file /var/airsonic/backups/airsonic.expo
rtDB.20240320112814/0.xml
2024-03-20 11:28:23.558  INFO --- liquibase.command.CommandScope           : Command execution complete
2024-03-20 11:28:23.568  INFO --- o.a.p.service.DatabaseService            : DB Export failed!

liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: liquibase.exce
ption.UnexpectedLiquibaseException: Invalid string encoding on column.value. To resolve, remove the invalid character on the database and try again in change
Set /var/airsonic/backups/airsonic.exportDB.20240320112814/0.xml::1710930495076-1::airsonic-data. To resolve, remove the invalid character on the database an
d try again
```

The next step has been to change the airsonic.service file to set your suggestion, removing 

`SystemCallFilter=~@clock @debug @module @mount @obsolete @privileged @reboot @setuid @swap`

adding

`SystemCallFilter=@basic-io @file-system @chown @network-io @sync @timer @signal @process @system-service`

and executing a daemon reload and restarting the service, but it can't create the export folder neither (the same exceptions).

I hope this helps somebody else.

**Comment by tovine** [comment]
The exception `Invalid string encoding on column.value` could perhaps indicate an issue with some of the database contents? Hard to say for sure, but maybe some unsupported character set somewhere?

Regarding the "Failed to create parent directories" error I'd recommend checking the directory permissions to make sure the user/group your airsonic server process is running as actually has write permissions in the data directory; you might have to do a `chown -R <user>:<group> /var/airsonic` to fix this.
