### ISSUE TITLE
[Feature] JukeBox Bit Perfect Play

### ISSUE THREAD

**Issue by fangxx3863** [airsonic-advanced/airsonic-advanced#869]
## Problem description

In the new version, Airsonic forces use ffmpeg to downsample HiRes audio to 44.1kHz. 
I wish there was an option to play the original file. So I tried to modify the code, unfortunately my code level is too poor to do this. 
I think we can call mpv to play files, mpv can use socket to communicate, it may be able to replace AudioPlayer.java
My English is not good, please forgive some mistakes,thanks!

### Steps to reproduce

1. Play a 96kHz/24bits audio 
2. ffmpeg will downsample to 44.1kHz/16bits and started to play

## System information

 * **Airsonic version**: *11.0.0-SNAPSHOT.20220318050825*
 * **Operating system**: *Debian with docker*
 * **Java version**: *14*
 * **Proxy server**: *None*
 * **Client**: *DSub*
 * **Language**: *Chinese*

**Comment by randomnicode** [comment]
"Settings" -> "Transcoding tab" -> "Jukebox command" field describes the command used for jukebox play. You don't need to modify code. If you want the files to play with a different sample rate or just as they are, modify the command parameters accordingly.

**Comment by fangxx3863** [comment]
> "Settings" -> "Transcoding tab" -> "Jukebox command" field describes the command used for jukebox play. You don't need to modify code. If you want the files to play with a different sample rate or just as they are, modify the command parameters accordingly.

![image](https://user-images.githubusercontent.com/48589001/162351912-d2d536fa-23cc-40cd-a836-23b9869288a8.png)

This line is dead written 
I tried modifying the code to extract audio parameters by regex matching the ffmpeg command line
