### ISSUE TITLE
No more LastFM or ListenBRainz credential inputs

### ISSUE THREAD

**Issue by Fl0w3D** [airsonic-advanced/airsonic-advanced#870]
## Problem description

I believe since commit b78c268, the inputs for LastFM and ListenBrainz credentials are gone.
Checking the respective checkboxes do not display any fields to fill. It just adds a pixel or two of nothing.

### Steps to reproduce

1. Go to Personal Settings
2. Check LastFM or ListenBrainz checkboxes
3. Notice how no input fields show up

## System information

 * **Airsonic version**: 10.6.0.20200424173747
 * **Operating system**: ArchLinux
 * **Java version**: 11.0.15
 * **Proxy server**: None
 * **Client**: Firefox 98.0.2 and Chromium 99.0.4844.82
 * **Language**: French and English

**Comment by B16WLL** [comment]
You need to click 'Add Credentials' on the Credentials setttings tab.
![image](https://user-images.githubusercontent.com/102246595/159990776-a48c71f4-01b7-46a1-8e0e-586c530939f6.png)

**Comment by Fl0w3D** [comment]
Oh right, my bad, I switch from Airsonic recently and did not notice this change. Thanks!
Why is there a div or something still hidden/shown when the checkboxes are checked in Personal settings?
I think there should be some info icon close to these checkboxes to indicate that credentials are to be filled in the next tab (or maybe it's just me who didn't get it right!).
Anyway I close this issue, thanks again.
