### ISSUE TITLE
DSub sync/cache with Airsonic 11 dumps all files into main cache folder with no artist\album sub-folder structure

### ISSUE THREAD

**Issue by MitchMcHenry1** [airsonic-advanced/airsonic-advanced#873]
## Problem description

Finally upgraded from vanilla 10.6 to Advanced 11 this week and found a major problem syncing/caching new albums to DSub.  All newly synced/cached albums showed the same cover art in DSub even though it was correct in web.  Turns out with Airsonic 11 all synced/cached files get dumped into the main cache folder in DSub without any sub-folder structure (no artist\album folders).  Because all files are piled into one folder there's only one albumart.jpg, so all newly synced albums show same art.  And obviously, thousands of mp3s in a single folder with no organization is less than ideal.

### Testing/research steps
* Reverted back to _vanilla_ 10.6 and confirmed that syncing with DSub correctly reproduces artist\album subfolders in DSub cache
* Upgraded to _advanced_ 10.6 and confirmed that artist\album subfolders in DSub cache are still created as expected
* Finally, upgraded to 11 again and confirmed artist\album subfolders are no longer created in DSub cache and all files are dumped in main cache folder
* Thought transcoding could possibly have something to do with it, but confirmed transcoding settings and bins are same in all 3 cases (default flac -> mp3 settings with recent ffmpeg)

### Steps to reproduce

1. Connect DSub to Airsonic 11 server
2. In DSub, manually select any track or album to cache or use any of the automated syncing features
3. After DSub download completes, check cache folder.  Files will be in main cache folder instead of artist\album sub-folders
4. Do the same with any 10.6 server (vanilla or advanced) and cached files will be in artist\album sub-folders (expected behavior)

## System information

 * **Airsonic version**: airsonic.war.11.0.0-SNAPSHOT.20220320083637
 * **Operating system**: Windows 10
 * **Java version**: 17.0.2
 * **Proxy server**: IIS
 * **Client**: [DSub 5.5.1](https://github.com/daneren2005/Subsonic/releases/tag/5.5.1) (latest on Play store), Galaxy 20+ Android 12
 * **Language**: English

## Additional notes

Surprised that DSub local cache folders are controlled by server, but seems to be the case based on above testing.

Syncing with DSub is my primary use case, so have to stick with advanced 10.6 for now.  Really hope this can be fixed.  If anyone is aware of another android app that supports all of DSub's syncing options (playlists, recently added, starred, manual) I'd be willing to give it a shot.

**Comment by randomnicode** [comment]
> Surprised that DSub local cache folders are controlled by server, but seems to be the case based on above testing.

DSub local caches are not controlled by server. The server has no say or idea about what the stream does once it leaves the url.

This is a matter better raised as an issue on the DSub github since it does not really concern the server side, and there is nothing we can do about the issue.

**Comment by MitchMcHenry1** [comment]
@randomnicode - that's what I would have expected, but if that's the case then why does it work as expected with both vanilla and advanced 10.6 and not with 11?  DSub is exactly the same in all cases, only difference is 11.

**Comment by MitchMcHenry1** [comment]
Just wanted to confirm this was caused by a change in behavior in Airsonic 11.  On windows platform Airsonic 11 getMusicDirectory API returns backslashes in the path.  Base subsonic, madsonic and airsonic vanilla/adv 10.6 all return forward slashes regardless of platform.  The backslashes broke the path parsing in DSub, so cached files all ended up in the main cache folder.

DSub owner was nice enough to fix this, so my problem is resolved.  But I imagine this could cause problems with other clients as well.
