### ISSUE TITLE
Please add indexes for podcasts

### ISSUE THREAD

**Issue by dsmouse** [airsonic-advanced/airsonic-advanced#902]
## Problem description

I have what could be considered a large podcast collection; over 100 podcasts.  with the latest edge builds, it can take over 115 seconds to load the podcasts page. 

### Steps to reproduce
subscribe to a lot of big podcasts?

## System information

11.0.0-SNAPSHOT.20220320083637 in a k8s environment with NFS storage

## Additional notes

adding two indexes reduces the time to around 18 seconds. 
create index idx_podcast_channel_id on podcast_episode using btree ( channel_id );
create index idx_podcast_episode_guid on podcast_episode using btree ( episode_guid );

**Comment by dsmouse** [comment]
I guess I should say I'm using postgres via jdbc.

**Comment by ghenry22** [comment]
Actually I have a fairly small podcast collection by comparison, about 10 podcast channels.  Anywhre from 12 to 200 episodes per podcast.

I'm using the built in hsql db and it can also take up to 4 minutes to load the podcast channel list.  Both the web interface and the rest API are extremely slow to respond.  Interestingly the original vanilla subsonic loads the same set of podcasts without issue.
