### ISSUE TITLE
Raspberry Pi Compatibility

### ISSUE THREAD

**Issue by CrazyWolf13** [airsonic-advanced/airsonic-advanced#965]
Hey there
This looks awesome and is exactly what i would need. My Plan is to use this on my raspberrypi (its also a samba nas where i store my music and other files. Now is there a way to install this on a raspberrypi or would you say a raspi couldn't handle this application?
If yes, is there any detailed guide on how to do this?
Thank you for you answer and time.

**Comment by yllekz** [comment]
This works just fine on a Pi. Use the docker image.
